-- Расширение базы знаний, часть 3: ассортимент цветочных магазинов Mayflor и Ok-plants,
-- которого не было в базе: орхидеи, цитрусовые, цветущие кустарники, суккуленты и кактусы.
-- Латинские названия — актуальные (POWO); прежние названия в synonyms, чтобы распознавание
-- (Pl@ntNet, модель на телефоне) и поиск находили вид и по ним. Токсичность для животных — по ASPCA.
-- Миграция идемпотентна: повторный запуск и уже существующие записи ничего не дублируют.

insert into public.families (latin_name, name_ru) values
  ('Acanthaceae', 'Акантовые'),
  ('Amaranthaceae', 'Амарантовые'),
  ('Amaryllidaceae', 'Амариллисовые'),
  ('Apocynaceae', 'Кутровые'),
  ('Araceae', 'Ароидные'),
  ('Araliaceae', 'Аралиевые'),
  ('Araucariaceae', 'Араукариевые'),
  ('Arecaceae', 'Пальмы'),
  ('Argophyllaceae', 'Аргофилловые'),
  ('Asparagaceae', 'Спаржевые'),
  ('Asphodelaceae', 'Асфоделовые'),
  ('Asteraceae', 'Астровые'),
  ('Balsaminaceae', 'Бальзаминовые'),
  ('Boraginaceae', 'Бурачниковые'),
  ('Bromeliaceae', 'Бромелиевые'),
  ('Cactaceae', 'Кактусовые'),
  ('Calceolariaceae', 'Кальцеоляриевые'),
  ('Campanulaceae', 'Колокольчиковые'),
  ('Clusiaceae', 'Клузиевые'),
  ('Crassulaceae', 'Толстянковые'),
  ('Ericaceae', 'Вересковые'),
  ('Euphorbiaceae', 'Молочайные'),
  ('Gentianaceae', 'Горечавковые'),
  ('Gesneriaceae', 'Геснериевые'),
  ('Hydrangeaceae', 'Гортензиевые'),
  ('Lamiaceae', 'Яснотковые'),
  ('Melastomataceae', 'Меластомовые'),
  ('Myrtaceae', 'Миртовые'),
  ('Nyctaginaceae', 'Никтагиновые'),
  ('Oleaceae', 'Маслиновые'),
  ('Onagraceae', 'Кипрейные'),
  ('Orchidaceae', 'Орхидные'),
  ('Passifloraceae', 'Страстоцветные'),
  ('Primulaceae', 'Первоцветные'),
  ('Rosaceae', 'Розовые'),
  ('Rubiaceae', 'Мареновые'),
  ('Rutaceae', 'Рутовые'),
  ('Sarraceniaceae', 'Саррацениевые'),
  ('Solanaceae', 'Паслёновые'),
  ('Theaceae', 'Чайные'),
  ('Verbenaceae', 'Вербеновые')
on conflict (latin_name) do nothing;

insert into public.genera (family_id, latin_name, name_ru)
select f.id, g.latin_name, g.name_ru
from (values
  ('Crassulaceae', 'Adromischus', 'Адромискус'),
  ('Bromeliaceae', 'Aechmea', 'Эхмея'),
  ('Asparagaceae', 'Agave', 'Агава'),
  ('Bromeliaceae', 'Ananas', 'Ананас'),
  ('Araucariaceae', 'Araucaria', 'Араукария'),
  ('Primulaceae', 'Ardisia', 'Ардизия'),
  ('Cactaceae', 'Astrophytum', 'Астрофитум'),
  ('Nyctaginaceae', 'Bougainvillea', 'Бугенвиллия'),
  ('Campanulaceae', 'Brighamia', 'Бригамия'),
  ('Solanaceae', 'Browallia', 'Броваллия'),
  ('Calceolariaceae', 'Calceolaria', 'Кальцеолярия'),
  ('Theaceae', 'Camellia', 'Камелия'),
  ('Apocynaceae', 'Carissa', 'Карисса'),
  ('Orchidaceae', 'Cattleya', 'Каттлея'),
  ('Arecaceae', 'Chamaerops', 'Хамеропс'),
  ('Asteraceae', 'Chrysanthemum', 'Хризантема'),
  ('Rutaceae', 'Citrus', 'Цитрус'),
  ('Lamiaceae', 'Clerodendrum', 'Клеродендрум'),
  ('Clusiaceae', 'Clusia', 'Клузия'),
  ('Arecaceae', 'Cocos', 'Кокос'),
  ('Euphorbiaceae', 'Codiaeum', 'Кодиеум'),
  ('Gesneriaceae', 'Columnea', 'Колумнея'),
  ('Asparagaceae', 'Cordyline', 'Кордилина'),
  ('Argophyllaceae', 'Corokia', 'Корокия'),
  ('Crassulaceae', 'Cotyledon', 'Котиледон'),
  ('Orchidaceae', 'Cymbidium', 'Цимбидиум'),
  ('Boraginaceae', 'Ehretia', 'Эретия'),
  ('Amaryllidaceae', 'Eucharis', 'Эухарис'),
  ('Euphorbiaceae', 'Euphorbia', 'Молочай'),
  ('Gentianaceae', 'Exacum', 'Экзакум'),
  ('Araliaceae', 'Fatshedera', 'Фатсхедера'),
  ('Onagraceae', 'Fuchsia', 'Фуксия'),
  ('Asteraceae', 'Gynura', 'Гинура'),
  ('Asphodelaceae', 'Haworthia', 'Хавортия'),
  ('Araceae', 'Homalomena', 'Хомаломена'),
  ('Hydrangeaceae', 'Hydrangea', 'Гортензия'),
  ('Balsaminaceae', 'Impatiens', 'Бальзамин'),
  ('Amaranthaceae', 'Iresine', 'Ирезине'),
  ('Acanthaceae', 'Justicia', 'Юстиция'),
  ('Cactaceae', 'Kroenleinia', 'Кронлейния'),
  ('Verbenaceae', 'Lantana', 'Лантана'),
  ('Orchidaceae', 'Ludisia', 'Лудизия'),
  ('Apocynaceae', 'Mandevilla', 'Мандевилла'),
  ('Apocynaceae', 'Marsdenia', 'Марсдения'),
  ('Melastomataceae', 'Medinilla', 'Мединилла'),
  ('Orchidaceae', 'Miltoniopsis', 'Мильтониопсис'),
  ('Rutaceae', 'Murraya', 'Муррайя'),
  ('Primulaceae', 'Myrsine', 'Мирсина'),
  ('Myrtaceae', 'Myrtus', 'Мирт'),
  ('Gesneriaceae', 'Nematanthus', 'Нематантус'),
  ('Apocynaceae', 'Nerium', 'Олеандр'),
  ('Oleaceae', 'Olea', 'Маслина'),
  ('Orchidaceae', 'Oncidium', 'Онцидиум'),
  ('Crassulaceae', 'Pachyphytum', 'Пахифитум'),
  ('Apocynaceae', 'Pachypodium', 'Пахиподиум'),
  ('Acanthaceae', 'Pachystachys', 'Пахистахис'),
  ('Orchidaceae', 'Paphiopedilum', 'Пафиопедилум'),
  ('Passifloraceae', 'Passiflora', 'Пассифлора'),
  ('Rubiaceae', 'Pentas', 'Пентас'),
  ('Araliaceae', 'Plerandra', 'Плерандра'),
  ('Primulaceae', 'Primula', 'Первоцвет'),
  ('Ericaceae', 'Rhododendron', 'Рододендрон'),
  ('Rosaceae', 'Rosa', 'Роза'),
  ('Sarraceniaceae', 'Sarracenia', 'Саррацения'),
  ('Crassulaceae', 'Sempervivum', 'Молодило'),
  ('Gesneriaceae', 'Sinningia', 'Синнингия'),
  ('Solanaceae', 'Solanum', 'Паслён'),
  ('Orchidaceae', 'Vanda', 'Ванда'),
  ('Arecaceae', 'Washingtonia', 'Вашингтония')
) as g(family, latin_name, name_ru)
join public.families f on f.latin_name = g.family
on conflict (latin_name) do nothing;

insert into public.species
  (genus_id, slug, latin_name, common_names, synonyms, description, plant_type,
   difficulty, toxic_to_pets, toxic_to_humans, air_purifying)
select g.id, s.slug, s.latin_name, s.common_names::jsonb, s.synonyms, s.description::jsonb,
       s.plant_type, s.difficulty, s.toxic_pets, s.toxic_humans, s.air_purifying
from (values
  ('Agave', 'agave-attenuata', 'Agave attenuata',
   '{"ru": ["Агава оттянутая", "Лебединая шея"], "en": ["Fox tail agave"]}', '{}'::text[],
   '{"ru": "Мягкая агава без колючек: розетка сизых листьев на коротком стволе."}', 'суккулент', 1, true, false, false),
  ('Adromischus', 'adromischus-cristatus', 'Adromischus cristatus',
   '{"ru": ["Адромискус гребенчатый"], "en": ["Crinkle-leaf plant", "Key lime pie"]}', '{}'::text[],
   '{"ru": "Небольшой суккулент с волнистыми на концах листьями и воздушными корешками."}', 'суккулент', 2, null, false, false),
  ('Rhododendron', 'rhododendron-simsii', 'Rhododendron simsii',
   '{"ru": ["Азалия индийская", "Рододендрон Симса"], "en": ["Indian azalea", "Florist''s azalea"]}', '{"Azalea indica"}'::text[],
   '{"ru": "Пышно цветёт зимой; любит прохладу и кислый влажный грунт."}', 'кустарник', 4, true, true, false),
  ('Ananas', 'ananas-comosus', 'Ananas comosus',
   '{"ru": ["Ананас хохлатый", "Ананас"], "en": ["Pineapple"]}', '{}'::text[],
   '{"ru": "Бромелия с жёсткой розеткой; при хорошем свете даёт маленький плод."}', 'травянистое', 2, false, false, false),
  ('Araucaria', 'araucaria-heterophylla', 'Araucaria heterophylla',
   '{"ru": ["Араукария разнолистная", "Комнатная ель"], "en": ["Norfolk Island pine"]}', '{"Araucaria excelsa"}'::text[],
   '{"ru": "Хвойное деревце с ярусными ветвями, похожее на ёлочку."}', 'дерево', 3, null, false, true),
  ('Ardisia', 'ardisia-crenata', 'Ardisia crenata',
   '{"ru": ["Ардизия городчатая"], "en": ["Coral berry", "Christmas berry"]}', '{}'::text[],
   '{"ru": "Кустарник с блестящими листьями и гроздьями красных ягод зимой."}', 'кустарник', 3, null, false, false),
  ('Astrophytum', 'astrophytum-myriostigma', 'Astrophytum myriostigma',
   '{"ru": ["Астрофитум многорыльцевый", "Епископская шапка"], "en": ["Bishop''s cap cactus"]}', '{}'::text[],
   '{"ru": "Кактус без колючек из 4–6 рёбер, покрытых белыми точками."}', 'суккулент', 2, false, false, false),
  ('Impatiens', 'impatiens-walleriana', 'Impatiens walleriana',
   '{"ru": ["Бальзамин Уоллера", "Ванька мокрый"], "en": ["Busy Lizzie", "Impatiens"]}', '{}'::text[],
   '{"ru": "Сочные стебли и почти непрерывное цветение; на листьях бывают капельки."}', 'травянистое', 1, false, false, false),
  ('Brighamia', 'brighamia-insignis', 'Brighamia insignis',
   '{"ru": ["Бригамия замечательная", "Гавайская пальма"], "en": ["Hawaiian palm", "Vulcan palm"]}', '{}'::text[],
   '{"ru": "Редкое суккулентное растение с толстым стволом и душистыми жёлтыми цветками."}', 'суккулент', 3, null, false, false),
  ('Browallia', 'browallia-speciosa', 'Browallia speciosa',
   '{"ru": ["Броваллия красивая"], "en": ["Bush violet", "Sapphire flower"]}', '{}'::text[],
   '{"ru": "Кустик с синими и фиолетовыми звёздочками-цветками."}', 'травянистое', 2, true, true, false),
  ('Bougainvillea', 'bougainvillea-glabra', 'Bougainvillea glabra',
   '{"ru": ["Бугенвиллия гладкая"], "en": ["Paperflower", "Bougainvillea"]}', '{}'::text[],
   '{"ru": "Лиана с яркими прицветниками — малиновыми, фиолетовыми, белыми."}', 'лиана', 3, null, false, false),
  ('Washingtonia', 'washingtonia-robusta', 'Washingtonia robusta',
   '{"ru": ["Вашингтония мощная"], "en": ["Mexican fan palm"]}', '{}'::text[],
   '{"ru": "Веерная пальма с нитями по краям листьев; быстро растёт."}', 'пальма', 2, false, false, true),
  ('Gynura', 'gynura-aurantiaca', 'Gynura aurantiaca',
   '{"ru": ["Гинура оранжевая", "Пурпурная страсть"], "en": ["Purple passion"]}', '{}'::text[],
   '{"ru": "Бархатистые листья в фиолетовом опушении."}', 'травянистое', 2, false, false, false),
  ('Sinningia', 'sinningia-speciosa', 'Sinningia speciosa',
   '{"ru": ["Глоксиния", "Синнингия прекрасная"], "en": ["Gloxinia"]}', '{"Gloxinia speciosa"}'::text[],
   '{"ru": "Бархатные листья и крупные колокольчики; растёт из клубня и зимой отдыхает."}', 'травянистое', 3, false, false, false),
  ('Plerandra', 'plerandra-elegantissima', 'Plerandra elegantissima',
   '{"ru": ["Дизиготека изящнейшая", "Ложная аралия"], "en": ["False aralia"]}', '{"Dizygotheca elegantissima","Schefflera elegantissima"}'::text[],
   '{"ru": "Кружевные узкие зубчатые листья тёмно-бронзового цвета."}', 'дерево', 4, null, false, false),
  ('Iresine', 'iresine-herbstii', 'Iresine herbstii',
   '{"ru": ["Ирезине Гербста"], "en": ["Beefsteak plant", "Chicken gizzard"]}', '{}'::text[],
   '{"ru": "Сочные малиновые листья с яркими жилками."}', 'травянистое', 1, null, false, false),
  ('Citrus', 'citrus-microcarpa', 'Citrus × microcarpa',
   '{"ru": ["Каламондин", "Цитрофортунелла"], "en": ["Calamondin"]}', '{"× Citrofortunella microcarpa","Citrus mitis"}'::text[],
   '{"ru": "Компактный цитрус, одновременно цветёт и держит мелкие оранжевые плоды."}', 'дерево', 2, true, false, false),
  ('Calceolaria', 'calceolaria-herbeohybrida', 'Calceolaria × herbeohybrida',
   '{"ru": ["Кальцеолярия гибридная", "Башмачки"], "en": ["Pocketbook plant", "Slipper flower"]}', '{"Calceolaria herbeohybrida"}'::text[],
   '{"ru": "Однолетник с цветками-«кошельками» в крапинку; цветёт весной."}', 'травянистое', 3, false, false, false),
  ('Camellia', 'camellia-japonica', 'Camellia japonica',
   '{"ru": ["Камелия японская"], "en": ["Japanese camellia"]}', '{}'::text[],
   '{"ru": "Кустарник с глянцевыми листьями и цветками, похожими на розы; цветёт зимой."}', 'кустарник', 4, false, false, false),
  ('Carissa', 'carissa-macrocarpa', 'Carissa macrocarpa',
   '{"ru": ["Карисса крупноплодная", "Натальская слива"], "en": ["Natal plum"]}', '{"Carissa grandiflora"}'::text[],
   '{"ru": "Кустарник с душистыми белыми цветками и красными плодами; на ветвях колючки."}', 'кустарник', 2, null, false, false),
  ('Ehretia', 'ehretia-microphylla', 'Ehretia microphylla',
   '{"ru": ["Кармона", "Фукиенский чай"], "en": ["Fukien tea"]}', '{"Carmona retusa","Carmona microphylla"}'::text[],
   '{"ru": "Мелколистное деревце с белыми цветками — классика комнатного бонсай."}', 'дерево', 4, null, false, false),
  ('Clerodendrum', 'clerodendrum-thomsoniae', 'Clerodendrum thomsoniae',
   '{"ru": ["Клеродендрум Томсон"], "en": ["Bleeding glory-bower", "Bleeding heart vine"]}', '{}'::text[],
   '{"ru": "Лиана с белыми чашечками и алыми цветками."}', 'лиана', 3, null, false, false),
  ('Clusia', 'clusia-rosea', 'Clusia rosea',
   '{"ru": ["Клузия розовая", "Автографовое дерево"], "en": ["Autograph tree", "Pitch-apple"]}', '{"Clusia major"}'::text[],
   '{"ru": "Мясистые округлые листья, на которых остаются надписи."}', 'дерево', 1, null, false, true),
  ('Codiaeum', 'codiaeum-variegatum', 'Codiaeum variegatum',
   '{"ru": ["Кротон", "Кодиеум пёстрый"], "en": ["Croton", "Garden croton"]}', '{}'::text[],
   '{"ru": "Кожистые листья в жёлтых, оранжевых, красных и зелёных узорах."}', 'кустарник', 3, true, true, false),
  ('Cocos', 'cocos-nucifera', 'Cocos nucifera',
   '{"ru": ["Кокосовая пальма"], "en": ["Coconut palm"]}', '{}'::text[],
   '{"ru": "Молодая пальма, растущая прямо из ореха; в квартире живёт несколько лет."}', 'пальма', 4, false, false, false),
  ('Columnea', 'columnea-gloriosa', 'Columnea gloriosa',
   '{"ru": ["Колумнея великолепная"], "en": ["Goldfish plant"]}', '{}'::text[],
   '{"ru": "Ампельное растение с красными цветками-«рыбками»."}', 'эпифит', 3, false, false, false),
  ('Rosa', 'rosa-chinensis', 'Rosa chinensis',
   '{"ru": ["Роза комнатная", "Роза китайская"], "en": ["Miniature rose", "China rose"]}', '{"Rosa × chinensis"}'::text[],
   '{"ru": "Миниатюрные розы в горшке; летом лучше на балконе."}', 'кустарник', 3, false, false, false),
  ('Cordyline', 'cordyline-fruticosa', 'Cordyline fruticosa',
   '{"ru": ["Кордилина кустарниковая"], "en": ["Ti plant", "Good luck plant"]}', '{"Cordyline terminalis"}'::text[],
   '{"ru": "Розетки широких листьев с розовыми и красными полосами."}', 'дерево', 2, true, false, true),
  ('Corokia', 'corokia-cotoneaster', 'Corokia cotoneaster',
   '{"ru": ["Корокия кизильниковая"], "en": ["Wire netting bush"]}', '{}'::text[],
   '{"ru": "Кустарник с зигзагообразными ветками и мелкими листьями."}', 'кустарник', 2, null, false, false),
  ('Cotyledon', 'cotyledon-orbiculata', 'Cotyledon orbiculata',
   '{"ru": ["Котиледон округлый", "Свиное ухо"], "en": ["Pig''s ear"]}', '{}'::text[],
   '{"ru": "Суккулент с мясистыми сизыми листьями с красной каймой."}', 'суккулент', 1, true, false, false),
  ('Citrus', 'citrus-japonica', 'Citrus japonica',
   '{"ru": ["Кумкват"], "en": ["Kumquat"]}', '{"Fortunella margarita","Fortunella japonica"}'::text[],
   '{"ru": "Цитрус с мелкими плодами, которые едят вместе с кожурой."}', 'дерево', 3, true, false, false),
  ('Citrus', 'citrus-sinensis', 'Citrus × sinensis',
   '{"ru": ["Апельсин"], "en": ["Sweet orange", "Orange tree"]}', '{"Citrus sinensis"}'::text[],
   '{"ru": "Цитрусовое деревце с душистыми цветками; плоды в квартире мелкие."}', 'дерево', 3, true, false, false),
  ('Citrus', 'citrus-reticulata', 'Citrus reticulata',
   '{"ru": ["Мандарин"], "en": ["Mandarin orange"]}', '{}'::text[],
   '{"ru": "Компактный цитрус, охотно цветёт и плодоносит в горшке."}', 'дерево', 3, true, false, false),
  ('Lantana', 'lantana-camara', 'Lantana camara',
   '{"ru": ["Лантана камара"], "en": ["Lantana", "Shrub verbena"]}', '{}'::text[],
   '{"ru": "Кустарник с шапками цветков, меняющих цвет по мере распускания; ягоды ядовиты."}', 'кустарник', 2, true, true, false),
  ('Ludisia', 'ludisia-discolor', 'Ludisia discolor',
   '{"ru": ["Лудизия двуцветная", "Драгоценная орхидея"], "en": ["Jewel orchid"]}', '{"Haemaria discolor"}'::text[],
   '{"ru": "Орхидея ради листьев: бархатные бордовые листья с розовыми жилками."}', 'травянистое', 2, false, false, false),
  ('Mandevilla', 'mandevilla-sanderi', 'Mandevilla sanderi',
   '{"ru": ["Мандевилла Сандера", "Дипладения"], "en": ["Brazilian jasmine", "Dipladenia"]}', '{"Dipladenia sanderi"}'::text[],
   '{"ru": "Вьющаяся лиана с крупными розовыми и красными воронками все лето."}', 'лиана', 2, null, false, false),
  ('Medinilla', 'medinilla-magnifica', 'Medinilla magnifica',
   '{"ru": ["Мединилла великолепная"], "en": ["Rose grape", "Philippine orchid"]}', '{}'::text[],
   '{"ru": "Эффектные поникающие кисти розовых цветков под розовыми прицветниками."}', 'кустарник', 5, false, false, false),
  ('Myrsine', 'myrsine-africana', 'Myrsine africana',
   '{"ru": ["Мирсина африканская"], "en": ["Cape myrtle", "African boxwood"]}', '{}'::text[],
   '{"ru": "Мелколистный кустарник, похожий на самшит; хорош для бонсай."}', 'кустарник', 2, null, false, false),
  ('Myrtus', 'myrtus-communis', 'Myrtus communis',
   '{"ru": ["Мирт обыкновенный"], "en": ["Common myrtle"]}', '{}'::text[],
   '{"ru": "Ароматный кустарник с мелкими листьями и белыми цветками."}', 'кустарник', 3, null, false, true),
  ('Sempervivum', 'sempervivum-tectorum', 'Sempervivum tectorum',
   '{"ru": ["Молодило кровельное", "Каменная роза"], "en": ["Common houseleek", "Hens and chicks"]}', '{}'::text[],
   '{"ru": "Морозостойкий суккулент с розетками и множеством деток."}', 'суккулент', 1, false, false, false),
  ('Murraya', 'murraya-paniculata', 'Murraya paniculata',
   '{"ru": ["Муррайя метельчатая", "Апельсиновый жасмин"], "en": ["Orange jasmine"]}', '{"Murraya exotica"}'::text[],
   '{"ru": "Кустарник с душистыми белыми цветками и красными ягодами."}', 'кустарник', 3, null, false, false),
  ('Nematanthus', 'nematanthus-gregarius', 'Nematanthus gregarius',
   '{"ru": ["Нематантус", "Гиппоцирта"], "en": ["Goldfish plant", "Clog plant"]}', '{"Hypocyrta radicans"}'::text[],
   '{"ru": "Глянцевые листья и оранжевые цветки-«рыбки»."}', 'эпифит', 2, false, false, false),
  ('Nerium', 'nerium-oleander', 'Nerium oleander',
   '{"ru": ["Олеандр обыкновенный"], "en": ["Oleander"]}', '{}'::text[],
   '{"ru": "Кустарник с пышными цветками; все части очень ядовиты."}', 'кустарник', 2, true, true, false),
  ('Olea', 'olea-europaea', 'Olea europaea',
   '{"ru": ["Олива европейская", "Маслина"], "en": ["Olive tree"]}', '{}'::text[],
   '{"ru": "Серебристо-зелёное деревце; дома растёт медленно и может плодоносить."}', 'дерево', 2, false, false, false),
  ('Oncidium', 'oncidium-hybridum', 'Oncidium × hybridum',
   '{"ru": ["Онцидиум", "Танцующие куколки"], "en": ["Dancing-lady orchid"]}', '{"Oncidium hybridum"}'::text[],
   '{"ru": "Орхидея с ветвистыми кистями мелких жёлтых или коричневых цветков."}', 'эпифит', 3, false, false, false),
  ('Cymbidium', 'cymbidium-hybridum', 'Cymbidium × hybridum',
   '{"ru": ["Цимбидиум"], "en": ["Boat orchid", "Cymbidium"]}', '{"Cymbidium hybridum"}'::text[],
   '{"ru": "Крупная орхидея с длинными листьями и цветоносами до метра; цветёт зимой."}', 'травянистое', 3, false, false, false),
  ('Vanda', 'vanda-hybrida', 'Vanda × hybrida',
   '{"ru": ["Ванда"], "en": ["Vanda orchid"]}', '{"Vanda hybrida"}'::text[],
   '{"ru": "Орхидея с воздушными корнями, часто растёт в вазе без субстрата."}', 'эпифит', 5, false, false, false),
  ('Cattleya', 'cattleya-hybrida', 'Cattleya × hybrida',
   '{"ru": ["Каттлея"], "en": ["Cattleya orchid", "Corsage orchid"]}', '{"Cattleya hybrida"}'::text[],
   '{"ru": "Орхидея с крупными ароматными цветками с гофрированной губой."}', 'эпифит', 4, false, false, false),
  ('Paphiopedilum', 'paphiopedilum-hybridum', 'Paphiopedilum × hybridum',
   '{"ru": ["Пафиопедилум", "Венерин башмачок"], "en": ["Slipper orchid", "Lady''s slipper"]}', '{"Paphiopedilum hybridum"}'::text[],
   '{"ru": "Орхидея с цветком-«башмачком»; растёт в грунте и мирится с полутенью."}', 'травянистое', 3, false, false, false),
  ('Miltoniopsis', 'miltoniopsis-hybrida', 'Miltoniopsis × hybrida',
   '{"ru": ["Мильтония", "Анютины глазки-орхидея"], "en": ["Pansy orchid"]}', '{"Miltonia hybrida"}'::text[],
   '{"ru": "Орхидея с плоскими цветками, похожими на анютины глазки."}', 'эпифит', 4, false, false, false),
  ('Passiflora', 'passiflora-caerulea', 'Passiflora caerulea',
   '{"ru": ["Пассифлора голубая", "Страстоцвет"], "en": ["Blue passionflower"]}', '{}'::text[],
   '{"ru": "Лиана с необычными сложными цветками; цепляется усиками."}', 'лиана', 2, null, false, false),
  ('Pachypodium', 'pachypodium-lamerei', 'Pachypodium lamerei',
   '{"ru": ["Пахиподиум Ламера", "Мадагаскарская пальма"], "en": ["Madagascar palm"]}', '{}'::text[],
   '{"ru": "Колючий суккулентный ствол с пучком листьев наверху."}', 'суккулент', 2, true, true, false),
  ('Pachystachys', 'pachystachys-lutea', 'Pachystachys lutea',
   '{"ru": ["Пахистахис жёлтый", "Золотая креветка"], "en": ["Golden shrimp plant", "Lollipop plant"]}', '{}'::text[],
   '{"ru": "Кустарник с жёлтыми колосками-прицветниками и белыми цветками."}', 'кустарник', 3, null, false, false),
  ('Pachyphytum', 'pachyphytum-oviferum', 'Pachyphytum oviferum',
   '{"ru": ["Пахифитум яйценосный", "Лунный камень"], "en": ["Moonstones"]}', '{}'::text[],
   '{"ru": "Суккулент с округлыми листьями в перламутровом налёте."}', 'суккулент', 1, false, false, false),
  ('Pentas', 'pentas-lanceolata', 'Pentas lanceolata',
   '{"ru": ["Пентас ланцетолистный", "Египетская звезда"], "en": ["Egyptian starcluster"]}', '{}'::text[],
   '{"ru": "Шапки звёздчатых цветков — розовых, красных, белых."}', 'травянистое', 2, null, false, false),
  ('Primula', 'primula-vulgaris', 'Primula vulgaris',
   '{"ru": ["Примула обыкновенная", "Первоцвет"], "en": ["Primrose"]}', '{"Primula acaulis"}'::text[],
   '{"ru": "Весенний первоцвет с яркими цветками; после цветения можно высадить в сад."}', 'травянистое', 2, true, false, false),
  ('Sarracenia', 'sarracenia-purpurea', 'Sarracenia purpurea',
   '{"ru": ["Саррацения пурпурная"], "en": ["Purple pitcher plant"]}', '{}'::text[],
   '{"ru": "Хищное растение с кувшинами-ловушками в розетке."}', 'травянистое', 4, false, false, false),
  ('Solanum', 'solanum-pseudocapsicum', 'Solanum pseudocapsicum',
   '{"ru": ["Паслён ложноперечный", "Иерусалимская вишня"], "en": ["Jerusalem cherry"]}', '{}'::text[],
   '{"ru": "Кустик с яркими ягодами-шариками зимой; ягоды ядовиты."}', 'кустарник', 2, true, true, false),
  ('Marsdenia', 'marsdenia-floribunda', 'Marsdenia floribunda',
   '{"ru": ["Стефанотис обильноцветущий", "Мадагаскарский жасмин"], "en": ["Madagascar jasmine", "Bridal wreath"]}', '{"Stephanotis floribunda"}'::text[],
   '{"ru": "Лиана с белыми восковыми очень душистыми цветками."}', 'лиана', 4, false, false, false),
  ('Fatshedera', 'fatshedera-lizei', '× Fatshedera lizei',
   '{"ru": ["Фатсхедера Лизе"], "en": ["Tree ivy", "Aralia ivy"]}', '{"Fatshedera lizei"}'::text[],
   '{"ru": "Гибрид фатсии и плюща: крупные пальчатые листья на полулазящих стеблях."}', 'кустарник', 1, true, false, true),
  ('Fuchsia', 'fuchsia-hybrida', 'Fuchsia × hybrida',
   '{"ru": ["Фуксия гибридная"], "en": ["Fuchsia", "Lady''s eardrops"]}', '{"Fuchsia hybrida"}'::text[],
   '{"ru": "Цветки-«балеринки» свисают весь сезон; летом хорошо на балконе."}', 'кустарник', 3, false, false, false),
  ('Haworthia', 'haworthia-cooperi', 'Haworthia cooperi',
   '{"ru": ["Хавортия Купера"], "en": ["Cooper''s haworthia", "Window haworthia"]}', '{}'::text[],
   '{"ru": "Маленький суккулент с прозрачными «окошками» на кончиках листьев."}', 'суккулент', 1, false, false, false),
  ('Chamaerops', 'chamaerops-humilis', 'Chamaerops humilis',
   '{"ru": ["Хамеропс приземистый"], "en": ["European fan palm", "Mediterranean dwarf palm"]}', '{}'::text[],
   '{"ru": "Невысокая веерная пальма с несколькими стволами; выносит прохладу."}', 'пальма', 1, false, false, true),
  ('Homalomena', 'homalomena-rubescens', 'Homalomena rubescens',
   '{"ru": ["Хомаломена краснеющая"], "en": ["Queen of hearts", "King of hearts"]}', '{}'::text[],
   '{"ru": "Сердцевидные листья на красноватых черешках; похожа на филодендрон."}', 'травянистое', 2, true, true, true),
  ('Chrysanthemum', 'chrysanthemum-morifolium', 'Chrysanthemum × morifolium',
   '{"ru": ["Хризантема садовая", "Хризантема в горшке"], "en": ["Florist''s daisy", "Pot mum"]}', '{"Chrysanthemum morifolium"}'::text[],
   '{"ru": "Горшечная хризантема, цветёт осенью облаком мелких или крупных цветков."}', 'травянистое', 2, true, false, true),
  ('Exacum', 'exacum-affine', 'Exacum affine',
   '{"ru": ["Экзакум родственный", "Персидская фиалка"], "en": ["Persian violet"]}', '{}'::text[],
   '{"ru": "Невысокий кустик, усыпанный фиолетовыми звёздочками с жёлтым центром."}', 'травянистое', 2, false, false, false),
  ('Euphorbia', 'euphorbia-trigona', 'Euphorbia trigona',
   '{"ru": ["Молочай треугранный"], "en": ["African milk tree", "Cathedral cactus"]}', '{}'::text[],
   '{"ru": "Колонновидный суккулент с рёбрами и мелкими листьями; млечный сок едкий."}', 'суккулент', 1, true, true, false),
  ('Eucharis', 'eucharis-grandiflora', 'Eucharis × grandiflora',
   '{"ru": ["Эухарис крупноцветковый", "Амазонская лилия"], "en": ["Amazon lily"]}', '{"Eucharis amazonica"}'::text[],
   '{"ru": "Луковичное растение с широкими листьями и душистыми белыми цветками, похожими на нарцисс."}', 'травянистое', 2, true, true, false),
  ('Kroenleinia', 'kroenleinia-grusonii', 'Kroenleinia grusonii',
   '{"ru": ["Эхинокактус Грузони", "Золотая бочка"], "en": ["Golden barrel cactus"]}', '{"Echinocactus grusonii"}'::text[],
   '{"ru": "Шаровидный кактус с золотистыми колючками; растёт медленно и доживает до огромных размеров."}', 'суккулент', 1, false, false, false),
  ('Aechmea', 'aechmea-fasciata', 'Aechmea fasciata',
   '{"ru": ["Эхмея полосатая"], "en": ["Urn plant", "Silver vase"]}', '{"Billbergia rhodocyanea"}'::text[],
   '{"ru": "Бромелия с серебристыми полосатыми листьями и розовым соцветием."}', 'эпифит', 2, false, false, true),
  ('Justicia', 'justicia-carnea', 'Justicia carnea',
   '{"ru": ["Юстиция мясо-красная", "Якобиния"], "en": ["Brazilian plume flower"]}', '{"Jacobinia carnea"}'::text[],
   '{"ru": "Кустарник с плотными розовыми соцветиями-«султанами»."}', 'кустарник', 3, false, false, false),
  ('Hydrangea', 'hydrangea-macrophylla', 'Hydrangea macrophylla',
   '{"ru": ["Гортензия крупнолистная"], "en": ["Bigleaf hydrangea"]}', '{}'::text[],
   '{"ru": "Крупные шапки цветков; цвет зависит от кислотности почвы."}', 'кустарник', 3, true, true, false)
) as s(genus, slug, latin_name, common_names, synonyms, description, plant_type,
       difficulty, toxic_pets, toxic_humans, air_purifying)
join public.genera g on g.latin_name = s.genus
on conflict do nothing;

insert into public.care_profiles
  (species_id, light, water_interval_summer, water_interval_winter, soil_dryness_before_watering,
   humidity_min_pct, temp_min_c, temp_max_c, fertilize_interval_days, fertilize_months,
   repot_every_years, propagation, tips)
select sp.id, c.light, c.summer, c.winter, c.dryness::jsonb, c.humidity, c.tmin, c.tmax,
       c.fert_days, c.fert_months, c.repot, c.propagation, c.tips::jsonb
from (values
  ('agave-attenuata', 'direct', 14, 30, '{"ru": "полностью"}', 20, 8, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"детки"}'::text[],
   '{"ru": ["Сок может раздражать кожу", "Зимой полив раз в месяц"]}'),
  ('adromischus-cristatus', 'bright_indirect', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"листья"}'::text[],
   '{"ru": ["Не лейте на листья — легко загнивают"]}'),
  ('rhododendron-simsii', 'bright_indirect', 3, 4, '{"ru": "не пересыхает"}', 60, 10, 20, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Поливайте мягкой подкислённой водой", "Для бутонов нужна прохлада +10–15 °C", "Все части ядовиты"]}'),
  ('ananas-comosus', 'direct', 7, 14, '{"ru": "верхние 2–3 см"}', 50, 18, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"розетка плода","детки"}'::text[],
   '{"ru": ["Верхушку купленного ананаса можно укоренить", "Воду иногда наливайте в розетку"]}'),
  ('araucaria-heterophylla', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 50, 10, 22, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"семена","верхушечные черенки"}'::text[],
   '{"ru": ["Зимой прохлада +10–15 °C, иначе осыпается хвоя", "Не обрезайте верхушку — перестанет расти вверх"]}'),
  ('ardisia-crenata', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 12, 24, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"семена","черенки"}'::text[],
   '{"ru": ["Утолщения по краю листа — полезные бактерии, их нельзя удалять", "Ягоды держатся месяцами"]}'),
  ('astrophytum-myriostigma', 'direct', 14, 40, '{"ru": "полностью"}', 20, 8, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Зимой сухое содержание при +8–12 °C", "Не любит пересадок"]}'),
  ('impatiens-walleriana', 'bright_indirect', 3, 5, '{"ru": "не пересыхает"}', 50, 15, 26, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"черенки","семена"}'::text[],
   '{"ru": ["Легко укореняется в воде", "Прищипывайте для кустистости"]}'),
  ('brighamia-insignis', 'bright_indirect', 10, 20, '{"ru": "верхняя половина горшка"}', 50, 15, 28, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Сбрасывает листья при переохлаждении"]}'),
  ('browallia-speciosa', 'bright_indirect', 3, 6, '{"ru": "верхний слой"}', 50, 12, 25, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"семена","черенки"}'::text[],
   '{"ru": ["Прищипывайте для пышности", "Все части ядовиты"]}'),
  ('bougainvillea-glabra', 'direct', 5, 14, '{"ru": "верхние 2–3 см"}', 40, 10, 30, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Цветёт только на солнце", "Зимой прохлада и скупой полив", "На стеблях колючки"]}'),
  ('washingtonia-robusta', 'direct', 6, 12, '{"ru": "верхние 3 см"}', 40, 8, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Летом полезен балкон", "Черешки с шипами"]}'),
  ('gynura-aurantiaca', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 40, 15, 26, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Удаляйте бутоны — у цветков неприятный запах", "Не опрыскивайте опушённые листья"]}'),
  ('sinningia-speciosa', 'bright_indirect', 4, 30, '{"ru": "верхний слой"}', 60, 18, 26, 14,
   '{4,5,6,7,8}'::smallint[], 1, '{"клубни","листовые черенки"}'::text[],
   '{"ru": ["Поливайте по краю горшка, не на клубень", "Осенью листья отмирают — клубень хранят в прохладе"]}'),
  ('plerandra-elegantissima', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Сбрасывает листья от сквозняков и сухого воздуха"]}'),
  ('iresine-herbstii', 'direct', 3, 6, '{"ru": "верхний слой"}', 50, 12, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Без солнца теряет окраску", "Прищипывайте для густоты"]}'),
  ('citrus-microcarpa', 'direct', 4, 10, '{"ru": "верхние 2 см"}', 50, 12, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Самый неприхотливый комнатный цитрус", "Не переставляйте с бутонами"]}'),
  ('calceolaria-herbeohybrida', 'bright_indirect', 3, 4, '{"ru": "не пересыхает"}', 60, 10, 18, 14,
   '{2,3,4,5}'::smallint[], null, '{"семена"}'::text[],
   '{"ru": ["Держите в прохладе — в тепле быстро отцветает", "После цветения обычно выбрасывают"]}'),
  ('camellia-japonica', 'bright_indirect', 5, 7, '{"ru": "верхние 2 см"}', 60, 5, 20, 21,
   '{3,4,5,6,7}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Для бутонов нужна прохлада +8–12 °C", "Не переставляйте во время бутонизации — сбросит"]}'),
  ('carissa-macrocarpa', 'direct', 5, 10, '{"ru": "верхние 2 см"}', 40, 10, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Хорошо формируется обрезкой"]}'),
  ('ehretia-microphylla', 'bright_indirect', 3, 6, '{"ru": "верхний слой"}', 60, 15, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Не допускайте пересыхания — бонсай в маленьком горшке"]}'),
  ('clerodendrum-thomsoniae', 'bright_indirect', 4, 10, '{"ru": "верхние 2 см"}', 60, 12, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Для цветения нужна прохладная зимовка +12–15 °C", "Весной обрежьте побеги на треть"]}'),
  ('clusia-rosea', 'bright_indirect', 7, 14, '{"ru": "верхние 3 см"}', 40, 15, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Выносливая и медленная"]}'),
  ('codiaeum-variegatum', 'bright_indirect', 4, 8, '{"ru": "верхние 2 см"}', 60, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Сбрасывает листья от сквозняков и перемены места", "Сок ядовит"]}'),
  ('cocos-nucifera', 'direct', 4, 7, '{"ru": "верхний слой"}', 70, 20, 32, 21,
   '{4,5,6,7,8,9}'::smallint[], null, '{"семена"}'::text[],
   '{"ru": ["Орех не закапывайте — он питает растение", "Нужны тепло, свет и влажный воздух"]}'),
  ('columnea-gloriosa', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 16, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["После цветения укоротите плети"]}'),
  ('rosa-chinensis', 'direct', 3, 6, '{"ru": "верхний слой"}', 50, 5, 25, 14,
   '{4,5,6,7,8}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Зимой прохлада и покой", "Удаляйте отцветшие цветки", "Часто страдает от паутинного клеща"]}'),
  ('cordyline-fruticosa', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 50, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","отрезки ствола"}'::text[],
   '{"ru": ["Коричневые кончики — сухой воздух или жёсткая вода"]}'),
  ('corokia-cotoneaster', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 40, 5, 24, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Зимой прохлада +5–10 °C"]}'),
  ('cotyledon-orbiculata', 'direct', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Не стирайте восковой налёт с листьев"]}'),
  ('citrus-japonica', 'direct', 4, 10, '{"ru": "верхние 2 см"}', 50, 10, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"прививка","черенки"}'::text[],
   '{"ru": ["Зимой прохлада +10–15 °C для цветения"]}'),
  ('citrus-sinensis', 'direct', 4, 10, '{"ru": "верхние 2–3 см"}', 50, 12, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"прививка","черенки"}'::text[],
   '{"ru": ["Нужен максимум света зимой"]}'),
  ('citrus-reticulata', 'direct', 4, 10, '{"ru": "верхние 2–3 см"}', 50, 12, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"прививка","черенки"}'::text[],
   '{"ru": ["Поворачивайте осторожно — не любит перемещений"]}'),
  ('lantana-camara', 'direct', 3, 7, '{"ru": "верхние 2 см"}', 40, 8, 30, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Весной сильная обрезка", "Зимой прохлада +8–12 °C"]}'),
  ('ludisia-discolor', 'medium', 5, 7, '{"ru": "верхний слой"}', 60, 18, 26, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","деление"}'::text[],
   '{"ru": ["Растёт в земле, а не в коре", "Не выносит прямого солнца"]}'),
  ('mandevilla-sanderi', 'direct', 4, 10, '{"ru": "верхние 2 см"}', 50, 12, 30, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Млечный сок раздражает кожу", "Зимой прохлада и сокращённый полив"]}'),
  ('medinilla-magnifica', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 70, 18, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Нужна очень высокая влажность", "Для цветения — сухая прохладная зимовка +16 °C"]}'),
  ('myrsine-africana', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 40, 5, 26, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Хорошо переносит стрижку"]}'),
  ('myrtus-communis', 'direct', 3, 7, '{"ru": "верхний слой"}', 50, 5, 25, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Пересыхание кома губительно", "Зимой прохлада +5–10 °C"]}'),
  ('sempervivum-tectorum', 'direct', 10, 30, '{"ru": "полностью"}', 20, -20, 35, 30,
   '{5,6,7,8}'::smallint[], 3, '{"детки"}'::text[],
   '{"ru": ["Отлично растёт и на улице", "Розетка после цветения отмирает"]}'),
  ('murraya-paniculata', 'bright_indirect', 4, 8, '{"ru": "верхний слой"}', 60, 16, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"семена","черенки"}'::text[],
   '{"ru": ["Цветёт уже маленьким", "Любит кислую почву и мягкую воду"]}'),
  ('nematanthus-gregarius', 'bright_indirect', 5, 8, '{"ru": "верхний слой"}', 50, 14, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Зимой прохлада +14–16 °C для обильного цветения"]}'),
  ('nerium-oleander', 'direct', 3, 10, '{"ru": "верхние 2 см"}', 40, 5, 30, 14,
   '{4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Очень ядовит — не держите рядом с детьми и животными", "Зимой прохлада +8–12 °C"]}'),
  ('olea-europaea', 'direct', 7, 14, '{"ru": "верхняя половина горшка"}', 30, 5, 30, 21,
   '{5,6,7,8}'::smallint[], 3, '{"черенки"}'::text[],
   '{"ru": ["Для цветения нужна холодная зимовка +5–10 °C"]}'),
  ('oncidium-hybridum', 'bright_indirect', 5, 10, '{"ru": "кора подсыхает"}', 50, 14, 26, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Сморщенные псевдобульбы — недолив или гибель корней"]}'),
  ('cymbidium-hybridum', 'direct', 4, 10, '{"ru": "верхний слой"}', 50, 8, 25, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Без ночного похолодания осенью (+10–14 °C) не зацветёт", "Летом полезен балкон"]}'),
  ('vanda-hybrida', 'direct', 2, 4, '{"ru": "корни побелели"}', 70, 16, 30, 7,
   '{3,4,5,6,7,8,9}'::smallint[], null, '{"детки"}'::text[],
   '{"ru": ["Каждый день купайте корни или держите в высокой влажности", "Нужно очень много света"]}'),
  ('cattleya-hybrida', 'bright_indirect', 7, 12, '{"ru": "кора подсыхает"}', 50, 15, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Нужна разница дневной и ночной температуры", "Поливайте, когда кора полностью просохнет"]}'),
  ('paphiopedilum-hybridum', 'medium', 5, 8, '{"ru": "не пересыхает"}', 60, 16, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Не любит пересыхания — у неё нет псевдобульб", "Вода не должна попадать в центр розетки"]}'),
  ('miltoniopsis-hybrida', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 14, 24, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Не выносит жары выше +25 °C", "Гармошкой складывающиеся листья — пересыхание"]}'),
  ('passiflora-caerulea', 'direct', 4, 10, '{"ru": "верхние 2 см"}', 50, 8, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Весной сильно обрезайте — цветёт на молодых побегах"]}'),
  ('pachypodium-lamerei', 'direct', 7, 30, '{"ru": "полностью"}', 30, 15, 35, 21,
   '{5,6,7,8}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Зимой может сбросить листья — полив почти прекратить", "Сок ядовит"]}'),
  ('pachystachys-lutea', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 16, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Весной обрезайте для компактности"]}'),
  ('pachyphytum-oviferum', 'direct', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"листья"}'::text[],
   '{"ru": ["Не трогайте листья — налёт стирается"]}'),
  ('pentas-lanceolata', 'direct', 3, 6, '{"ru": "верхний слой"}', 50, 12, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"черенки","семена"}'::text[],
   '{"ru": ["Удаляйте отцветшие соцветия"]}'),
  ('primula-vulgaris', 'bright_indirect', 3, 4, '{"ru": "не пересыхает"}', 50, 5, 18, 14,
   '{2,3,4,5}'::smallint[], 1, '{"деление","семена"}'::text[],
   '{"ru": ["В тепле быстро отцветает — держите прохладно"]}'),
  ('sarracenia-purpurea', 'direct', 2, 5, '{"ru": "не пересыхает"}', 50, 0, 30, null,
   '{}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Только дистиллированная или дождевая вода, горшок в поддоне с водой", "Зимой обязателен холодный покой"]}'),
  ('solanum-pseudocapsicum', 'direct', 4, 7, '{"ru": "верхний слой"}', 50, 12, 25, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"семена","черенки"}'::text[],
   '{"ru": ["Ягоды ядовиты — осторожнее с детьми и животными"]}'),
  ('marsdenia-floribunda', 'bright_indirect', 4, 10, '{"ru": "верхние 2 см"}', 60, 14, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Зимой прохлада +14–16 °C", "Не поворачивайте горшок с бутонами"]}'),
  ('fatshedera-lizei', 'medium', 5, 10, '{"ru": "верхние 2 см"}', 40, 8, 24, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Нужна опора", "Любит прохладу"]}'),
  ('fuchsia-hybrida', 'bright_indirect', 3, 10, '{"ru": "верхний слой"}', 50, 5, 24, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Не любит жары выше +25 °C", "Зимой прохладный покой +5–10 °C"]}'),
  ('haworthia-cooperi', 'bright_indirect', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки"}'::text[],
   '{"ru": ["Прямое солнце обжигает «окошки»"]}'),
  ('chamaerops-humilis', 'direct', 7, 14, '{"ru": "верхние 3 см"}', 40, 0, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"семена","отпрыски"}'::text[],
   '{"ru": ["Отличная пальма для прохладных помещений"]}'),
  ('homalomena-rubescens', 'medium', 6, 10, '{"ru": "верхние 2–3 см"}', 50, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Выносит полутень"]}'),
  ('chrysanthemum-morifolium', 'direct', 3, 7, '{"ru": "верхний слой"}', 40, 5, 22, 14,
   '{4,5,6,7,8}'::smallint[], 1, '{"черенки","деление"}'::text[],
   '{"ru": ["В прохладе цветёт дольше", "Короткий день запускает цветение"]}'),
  ('exacum-affine', 'bright_indirect', 3, 5, '{"ru": "не пересыхает"}', 50, 15, 25, 14,
   '{4,5,6,7,8,9}'::smallint[], null, '{"семена"}'::text[],
   '{"ru": ["Обычно живёт один сезон"]}'),
  ('euphorbia-trigona', 'direct', 10, 25, '{"ru": "полностью"}', 30, 12, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Сок едкий — работайте в перчатках", "Высокие экземпляры нуждаются в опоре"]}'),
  ('eucharis-grandiflora', 'medium', 5, 10, '{"ru": "верхние 2 см"}', 50, 16, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 3, '{"детки"}'::text[],
   '{"ru": ["Цветёт в тесном горшке", "После цветения месяц покоя со скупым поливом"]}'),
  ('kroenleinia-grusonii', 'direct', 14, 40, '{"ru": "полностью"}', 20, 8, 35, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Нужен максимум солнца", "Зимой сухое содержание"]}'),
  ('aechmea-fasciata', 'bright_indirect', 7, 14, '{"ru": "верхний слой"}', 50, 16, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки"}'::text[],
   '{"ru": ["Воду наливайте в розетку, раз в месяц меняйте", "После цветения растите деток"]}'),
  ('justicia-carnea', 'bright_indirect', 4, 8, '{"ru": "верхний слой"}', 60, 14, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Весной сильная обрезка — иначе вытягивается"]}'),
  ('hydrangea-macrophylla', 'bright_indirect', 2, 7, '{"ru": "не пересыхает"}', 50, 5, 22, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Очень любит воду — не пересушивайте", "Зимой холодный покой +5–8 °C", "Кислая почва даёт голубые цветки"]}')
) as c(slug, light, summer, winter, dryness, humidity, tmin, tmax, fert_days, fert_months,
       repot, propagation, tips)
join public.species sp on sp.slug = c.slug
on conflict (species_id) do nothing;
