-- Расширение базы знаний: ещё 57 популярных комнатных растений с карточками ухода.
-- Латинские названия — актуальные (POWO); прежние названия в synonyms, чтобы распознавание
-- (Pl@ntNet, модель на телефоне) и поиск находили вид и по ним. Токсичность для животных — по ASPCA.
-- Миграция идемпотентна: повторный запуск и уже существующие записи ничего не дублируют.

insert into public.families (latin_name, name_ru) values
  ('Apocynaceae', 'Кутровые'),
  ('Araceae', 'Ароидные'),
  ('Araliaceae', 'Аралиевые'),
  ('Arecaceae', 'Пальмы'),
  ('Asparagaceae', 'Спаржевые'),
  ('Asphodelaceae', 'Асфоделовые'),
  ('Aspleniaceae', 'Костенцовые'),
  ('Begoniaceae', 'Бегониевые'),
  ('Bromeliaceae', 'Бромелиевые'),
  ('Cactaceae', 'Кактусовые'),
  ('Commelinaceae', 'Коммелиновые'),
  ('Crassulaceae', 'Толстянковые'),
  ('Euphorbiaceae', 'Молочайные'),
  ('Geraniaceae', 'Гераниевые'),
  ('Gesneriaceae', 'Геснериевые'),
  ('Marantaceae', 'Марантовые'),
  ('Moraceae', 'Тутовые'),
  ('Nephrolepidaceae', 'Нефролеписовые'),
  ('Orchidaceae', 'Орхидные'),
  ('Oxalidaceae', 'Кисличные'),
  ('Piperaceae', 'Перечные'),
  ('Primulaceae', 'Первоцветные'),
  ('Rubiaceae', 'Мареновые'),
  ('Strelitziaceae', 'Стрелитциевые'),
  ('Urticaceae', 'Крапивные')
on conflict (latin_name) do nothing;

insert into public.genera (family_id, latin_name, name_ru)
select f.id, g.latin_name, g.name_ru
from (values
  ('Apocynaceae', 'Adenium', 'Адениум'),
  ('Araceae', 'Aglaonema', 'Аглаонема'),
  ('Araceae', 'Alocasia', 'Алоказия'),
  ('Araceae', 'Anthurium', 'Антуриум'),
  ('Asparagaceae', 'Asparagus', 'Аспарагус'),
  ('Asparagaceae', 'Aspidistra', 'Аспидистра'),
  ('Aspleniaceae', 'Asplenium', 'Асплениум'),
  ('Asparagaceae', 'Beaucarnea', 'Бокарнея'),
  ('Begoniaceae', 'Begonia', 'Бегония'),
  ('Apocynaceae', 'Ceropegia', 'Церопегия'),
  ('Arecaceae', 'Chamaedorea', 'Хамедорея'),
  ('Rubiaceae', 'Coffea', 'Кофе'),
  ('Primulaceae', 'Cyclamen', 'Цикламен'),
  ('Orchidaceae', 'Dendrobium', 'Дендробиум'),
  ('Araceae', 'Dieffenbachia', 'Диффенбахия'),
  ('Asparagaceae', 'Dracaena', 'Драцена'),
  ('Arecaceae', 'Dypsis', 'Дипсис'),
  ('Crassulaceae', 'Echeveria', 'Эхеверия'),
  ('Araceae', 'Epipremnum', 'Эпипремнум'),
  ('Euphorbiaceae', 'Euphorbia', 'Молочай'),
  ('Moraceae', 'Ficus', 'Фикус'),
  ('Marantaceae', 'Goeppertia', 'Гёпперция'),
  ('Bromeliaceae', 'Guzmania', 'Гузмания'),
  ('Asphodelaceae', 'Haworthiopsis', 'Хавортиопсис'),
  ('Araliaceae', 'Hedera', 'Плющ'),
  ('Arecaceae', 'Howea', 'Ховея'),
  ('Apocynaceae', 'Hoya', 'Хойя'),
  ('Crassulaceae', 'Kalanchoe', 'Каланхоэ'),
  ('Marantaceae', 'Maranta', 'Маранта'),
  ('Araceae', 'Monstera', 'Монстера'),
  ('Nephrolepidaceae', 'Nephrolepis', 'Нефролепис'),
  ('Cactaceae', 'Opuntia', 'Опунция'),
  ('Oxalidaceae', 'Oxalis', 'Кислица'),
  ('Geraniaceae', 'Pelargonium', 'Пеларгония'),
  ('Piperaceae', 'Peperomia', 'Пеперомия'),
  ('Araceae', 'Philodendron', 'Филодендрон'),
  ('Urticaceae', 'Pilea', 'Пилея'),
  ('Arecaceae', 'Rhapis', 'Рапис'),
  ('Araliaceae', 'Schefflera', 'Шеффлера'),
  ('Cactaceae', 'Schlumbergera', 'Шлюмбергера'),
  ('Araceae', 'Scindapsus', 'Сциндапсус'),
  ('Crassulaceae', 'Sedum', 'Очиток'),
  ('Strelitziaceae', 'Strelitzia', 'Стрелитция'),
  ('Gesneriaceae', 'Streptocarpus', 'Стрептокарпус'),
  ('Araceae', 'Syngonium', 'Сингониум'),
  ('Araceae', 'Thaumatophyllum', 'Таумафиллум'),
  ('Commelinaceae', 'Tradescantia', 'Традесканция'),
  ('Asparagaceae', 'Yucca', 'Юкка')
) as g(family, latin_name, name_ru)
join public.families f on f.latin_name = g.family
on conflict (latin_name) do nothing;

insert into public.species
  (genus_id, slug, latin_name, common_names, synonyms, description, plant_type,
   difficulty, toxic_to_pets, toxic_to_humans, air_purifying)
select g.id, s.slug, s.latin_name, s.common_names::jsonb, s.synonyms, s.description::jsonb,
       s.plant_type, s.difficulty, s.toxic_pets, s.toxic_humans, s.air_purifying
from (values
  ('Philodendron', 'philodendron-hederaceum', 'Philodendron hederaceum',
   '{"ru": ["Филодендрон лазящий", "Филодендрон сердцевидный"], "en": ["Heartleaf philodendron"]}', '{"Philodendron scandens","Philodendron oxycardium"}'::text[],
   '{"ru": "Неприхотливая лиана с сердцевидными листьями, растёт в ампеле или по опоре."}', 'лиана', 1, true, true, true),
  ('Thaumatophyllum', 'thaumatophyllum-bipinnatifidum', 'Thaumatophyllum bipinnatifidum',
   '{"ru": ["Филодендрон селлоум", "Филодендрон двоякоперистый"], "en": ["Tree philodendron", "Lacy tree philodendron"]}', '{"Philodendron bipinnatifidum","Philodendron selloum"}'::text[],
   '{"ru": "Крупное растение с глубоко рассечёнными листьями, со временем образует короткий ствол."}', 'травянистое', 2, true, true, true),
  ('Monstera', 'monstera-adansonii', 'Monstera adansonii',
   '{"ru": ["Монстера Адансона", "Монстера косая"], "en": ["Swiss cheese vine", "Adanson''s monstera"]}', '{"Monstera friedrichsthalii"}'::text[],
   '{"ru": "Изящная лиана с листьями в дырочках, быстрее и компактнее деликатесной."}', 'лиана', 2, true, true, true),
  ('Epipremnum', 'epipremnum-pinnatum', 'Epipremnum pinnatum',
   '{"ru": ["Эпипремнум перистый"], "en": ["Dragon tail plant", "Centipede tongavine"]}', '{}'::text[],
   '{"ru": "Лиана, у взрослых растений листья становятся перистыми. Популярен сорт «Cebu Blue»."}', 'лиана', 1, true, true, true),
  ('Scindapsus', 'scindapsus-pictus', 'Scindapsus pictus',
   '{"ru": ["Сциндапсус расписной", "Сциндапсус пиктус"], "en": ["Satin pothos", "Silver philodendron"]}', '{}'::text[],
   '{"ru": "Лиана с бархатистыми листьями в серебристых пятнах."}', 'лиана', 1, true, true, true),
  ('Aglaonema', 'aglaonema-commutatum', 'Aglaonema commutatum',
   '{"ru": ["Аглаонема изменчивая", "Аглаонема"], "en": ["Chinese evergreen"]}', '{}'::text[],
   '{"ru": "Теневыносливое растение с пёстрыми листьями, растёт медленно."}', 'травянистое', 1, true, true, true),
  ('Dieffenbachia', 'dieffenbachia-seguine', 'Dieffenbachia seguine',
   '{"ru": ["Диффенбахия пятнистая", "Диффенбахия"], "en": ["Dumb cane"]}', '{"Dieffenbachia maculata","Dieffenbachia picta"}'::text[],
   '{"ru": "Крупнолистное растение с пёстрыми листьями; сок сильно раздражает слизистые."}', 'травянистое', 2, true, true, true),
  ('Alocasia', 'alocasia-amazonica', 'Alocasia × amazonica',
   '{"ru": ["Алоказия амазонская", "Алоказия Поли"], "en": ["African mask plant", "Elephant ear"]}', '{"Alocasia amazonica","Alocasia ''Polly''"}'::text[],
   '{"ru": "Эффектные стреловидные листья с белыми жилками. Капризна к переливу и сухому воздуху."}', 'травянистое', 4, true, true, false),
  ('Anthurium', 'anthurium-andraeanum', 'Anthurium andraeanum',
   '{"ru": ["Антуриум Андре", "Мужское счастье"], "en": ["Flamingo flower", "Anthurium"]}', '{}'::text[],
   '{"ru": "Цветёт почти круглый год яркими глянцевыми покрывалами."}', 'эпифит', 3, true, true, true),
  ('Syngonium', 'syngonium-podophyllum', 'Syngonium podophyllum',
   '{"ru": ["Сингониум ножколистный"], "en": ["Arrowhead plant", "Arrowhead vine"]}', '{}'::text[],
   '{"ru": "Лиана со стреловидными листьями; есть розовые и пёстрые сорта."}', 'лиана', 1, true, true, true),
  ('Ficus', 'ficus-lyrata', 'Ficus lyrata',
   '{"ru": ["Фикус лировидный"], "en": ["Fiddle-leaf fig"]}', '{}'::text[],
   '{"ru": "Дерево с крупными скрипковидными листьями — главный интерьерный фикус."}', 'дерево', 3, true, false, true),
  ('Ficus', 'ficus-benjamina', 'Ficus benjamina',
   '{"ru": ["Фикус Бенджамина"], "en": ["Weeping fig"]}', '{}'::text[],
   '{"ru": "Деревце с мелкими листьями, хорошо формируется обрезкой."}', 'дерево', 3, true, false, true),
  ('Ficus', 'ficus-pumila', 'Ficus pumila',
   '{"ru": ["Фикус карликовый"], "en": ["Creeping fig"]}', '{}'::text[],
   '{"ru": "Стелющийся фикус с мелкими листьями, цепляется за опору воздушными корнями."}', 'лиана', 2, true, false, false),
  ('Dracaena', 'dracaena-marginata', 'Dracaena marginata',
   '{"ru": ["Драцена окаймлённая", "Драцена маргината"], "en": ["Madagascar dragon tree"]}', '{"Dracaena reflexa var. angustifolia"}'::text[],
   '{"ru": "Стволистое растение с пучками узких листьев, выносит полутень."}', 'дерево', 1, true, false, true),
  ('Dracaena', 'dracaena-fragrans', 'Dracaena fragrans',
   '{"ru": ["Драцена душистая", "Драцена массанжеана"], "en": ["Corn plant"]}', '{"Dracaena deremensis"}'::text[],
   '{"ru": "Стволистая драцена с широкими листьями; пахуче цветёт в возрасте."}', 'дерево', 1, true, false, true),
  ('Dracaena', 'dracaena-sanderiana', 'Dracaena sanderiana',
   '{"ru": ["Драцена Сандера", "Счастливый бамбук"], "en": ["Lucky bamboo"]}', '{"Dracaena braunii"}'::text[],
   '{"ru": "Растёт в воде или грунте, стебли часто скручивают спиралью."}', 'травянистое', 1, true, false, false),
  ('Dracaena', 'dracaena-angolensis', 'Dracaena angolensis',
   '{"ru": ["Сансевиерия цилиндрическая"], "en": ["Cylindrical snake plant", "African spear"]}', '{"Sansevieria cylindrica"}'::text[],
   '{"ru": "Суккулент с плотными цилиндрическими листьями; переносит засуху."}', 'суккулент', 1, true, false, true),
  ('Beaucarnea', 'beaucarnea-recurvata', 'Beaucarnea recurvata',
   '{"ru": ["Бокарнея отогнутая", "Нолина", "Слоновья нога"], "en": ["Ponytail palm"]}', '{"Nolina recurvata"}'::text[],
   '{"ru": "Запасает воду в раздутом основании ствола, листья свисают фонтаном."}', 'суккулент', 1, false, false, false),
  ('Aspidistra', 'aspidistra-elatior', 'Aspidistra elatior',
   '{"ru": ["Аспидистра высокая", "Чугунное растение"], "en": ["Cast iron plant"]}', '{}'::text[],
   '{"ru": "Почти неубиваемое растение для тёмных углов и прохладных комнат."}', 'травянистое', 1, false, false, true),
  ('Yucca', 'yucca-gigantea', 'Yucca gigantea',
   '{"ru": ["Юкка слоновая", "Юкка гигантская"], "en": ["Spineless yucca"]}', '{"Yucca elephantipes","Yucca guatemalensis"}'::text[],
   '{"ru": "Стволистое растение с жёсткими листьями, летом любит балкон."}', 'дерево', 1, true, false, true),
  ('Asparagus', 'asparagus-setaceus', 'Asparagus setaceus',
   '{"ru": ["Аспарагус перистый"], "en": ["Asparagus fern", "Lace fern"]}', '{"Asparagus plumosus"}'::text[],
   '{"ru": "Кружевное растение с тонкими веточками, похоже на папоротник."}', 'травянистое', 2, true, true, false),
  ('Haworthiopsis', 'haworthiopsis-attenuata', 'Haworthiopsis attenuata',
   '{"ru": ["Хавортия полосатая", "Хавортиопсис"], "en": ["Zebra haworthia", "Zebra plant"]}', '{"Haworthia attenuata","Haworthia fasciata"}'::text[],
   '{"ru": "Небольшой суккулент с белыми полосками на листьях; хорош для подоконника."}', 'суккулент', 1, false, false, false),
  ('Echeveria', 'echeveria-elegans', 'Echeveria elegans',
   '{"ru": ["Эхеверия изящная", "Каменная роза"], "en": ["Mexican snowball"]}', '{}'::text[],
   '{"ru": "Розетка сизых мясистых листьев; на солнце краснеет по краям."}', 'суккулент', 2, false, false, false),
  ('Kalanchoe', 'kalanchoe-blossfeldiana', 'Kalanchoe blossfeldiana',
   '{"ru": ["Каланхоэ Блоссфельда"], "en": ["Flaming Katy", "Florist kalanchoe"]}', '{}'::text[],
   '{"ru": "Суккулент с шапками ярких цветков; цветёт зимой и весной."}', 'суккулент', 1, true, false, false),
  ('Sedum', 'sedum-morganianum', 'Sedum morganianum',
   '{"ru": ["Очиток Моргана", "Ослиный хвост"], "en": ["Burro''s tail", "Donkey tail"]}', '{}'::text[],
   '{"ru": "Ампельный суккулент с плетями мясистых листьев."}', 'суккулент', 2, false, false, false),
  ('Schlumbergera', 'schlumbergera-truncata', 'Schlumbergera truncata',
   '{"ru": ["Шлюмбергера", "Декабрист", "Рождественник"], "en": ["Christmas cactus", "Thanksgiving cactus"]}', '{"Zygocactus truncatus"}'::text[],
   '{"ru": "Лесной кактус без колючек, цветёт к Новому году."}', 'эпифит', 1, false, false, false),
  ('Opuntia', 'opuntia-microdasys', 'Opuntia microdasys',
   '{"ru": ["Опунция мелковолосистая", "Кроличьи ушки"], "en": ["Bunny ears cactus"]}', '{}'::text[],
   '{"ru": "Кактус с плоскими сегментами в пучках мелких колючек-глохидий."}', 'суккулент', 1, false, false, false),
  ('Maranta', 'maranta-leuconeura', 'Maranta leuconeura',
   '{"ru": ["Маранта беложильчатая", "Молитвенное растение"], "en": ["Prayer plant"]}', '{}'::text[],
   '{"ru": "Вечером складывает узорчатые листья вверх, как ладони."}', 'травянистое', 3, false, false, false),
  ('Goeppertia', 'goeppertia-orbifolia', 'Goeppertia orbifolia',
   '{"ru": ["Калатея круглолистная", "Калатея орбифолия"], "en": ["Calathea orbifolia"]}', '{"Calathea orbifolia"}'::text[],
   '{"ru": "Крупные круглые листья в серебристую полоску. Требует влажного воздуха."}', 'травянистое', 4, false, false, false),
  ('Goeppertia', 'goeppertia-makoyana', 'Goeppertia makoyana',
   '{"ru": ["Калатея Макоя", "Калатея павлинья"], "en": ["Peacock plant"]}', '{"Calathea makoyana"}'::text[],
   '{"ru": "Листья с рисунком, похожим на перо павлина."}', 'травянистое', 4, false, false, false),
  ('Dypsis', 'dypsis-lutescens', 'Dypsis lutescens',
   '{"ru": ["Хризалидокарпус", "Дипсис желтоватый", "Арека"], "en": ["Areca palm", "Butterfly palm"]}', '{"Chrysalidocarpus lutescens"}'::text[],
   '{"ru": "Кустистая перистая пальма, растёт несколькими стволами."}', 'пальма', 2, false, false, true),
  ('Chamaedorea', 'chamaedorea-elegans', 'Chamaedorea elegans',
   '{"ru": ["Хамедорея изящная"], "en": ["Parlor palm"]}', '{"Neanthe bella"}'::text[],
   '{"ru": "Небольшая теневыносливая пальма для комнат."}', 'пальма', 1, false, false, true),
  ('Howea', 'howea-forsteriana', 'Howea forsteriana',
   '{"ru": ["Ховея Форстера", "Кентия"], "en": ["Kentia palm"]}', '{"Kentia forsteriana"}'::text[],
   '{"ru": "Элегантная крупная пальма, выносит полутень и сухой воздух."}', 'пальма', 2, false, false, true),
  ('Rhapis', 'rhapis-excelsa', 'Rhapis excelsa',
   '{"ru": ["Рапис высокий", "Бамбуковая пальма"], "en": ["Lady palm"]}', '{}'::text[],
   '{"ru": "Веерная пальма с бамбукоподобными стволиками, выносливая и медленная."}', 'пальма', 2, false, false, true),
  ('Dendrobium', 'dendrobium-nobile', 'Dendrobium nobile',
   '{"ru": ["Дендробиум благородный"], "en": ["Noble dendrobium"]}', '{}'::text[],
   '{"ru": "Орхидея с тростниковыми псевдобульбами; цветёт после прохладного сухого периода."}', 'эпифит', 4, false, false, false),
  ('Streptocarpus', 'streptocarpus-ionanthus', 'Streptocarpus ionanthus',
   '{"ru": ["Сенполия", "Узамбарская фиалка"], "en": ["African violet"]}', '{"Saintpaulia ionantha"}'::text[],
   '{"ru": "Компактное растение с бархатистыми листьями, цветёт почти круглый год."}', 'травянистое', 3, false, false, false),
  ('Begonia', 'begonia-rex', 'Begonia rex',
   '{"ru": ["Бегония королевская"], "en": ["Rex begonia", "Painted-leaf begonia"]}', '{}'::text[],
   '{"ru": "Декоративнолистная бегония с яркими узорчатыми листьями."}', 'травянистое', 3, true, false, false),
  ('Begonia', 'begonia-maculata', 'Begonia maculata',
   '{"ru": ["Бегония пятнистая", "Бегония горошек"], "en": ["Polka dot begonia"]}', '{}'::text[],
   '{"ru": "Бамбуковидная бегония с листьями в серебристый горошек и красной изнанкой."}', 'травянистое', 2, true, false, false),
  ('Pilea', 'pilea-peperomioides', 'Pilea peperomioides',
   '{"ru": ["Пилея пеперомиевидная", "Китайское денежное дерево"], "en": ["Chinese money plant"]}', '{}'::text[],
   '{"ru": "Круглые листья-монетки на длинных черешках; даёт много деток."}', 'травянистое', 1, false, false, false),
  ('Peperomia', 'peperomia-obtusifolia', 'Peperomia obtusifolia',
   '{"ru": ["Пеперомия туполистная"], "en": ["Baby rubber plant"]}', '{}'::text[],
   '{"ru": "Компактное растение с толстыми глянцевыми листьями, запасает воду."}', 'травянистое', 1, false, false, true),
  ('Peperomia', 'peperomia-argyreia', 'Peperomia argyreia',
   '{"ru": ["Пеперомия серебристая", "Пеперомия арбузная"], "en": ["Watermelon peperomia"]}', '{"Peperomia sandersii"}'::text[],
   '{"ru": "Листья с полосками как у арбуза на красных черешках."}', 'травянистое', 2, false, false, false),
  ('Tradescantia', 'tradescantia-zebrina', 'Tradescantia zebrina',
   '{"ru": ["Традесканция зебрина", "Зебрина"], "en": ["Wandering dude", "Inch plant"]}', '{"Zebrina pendula"}'::text[],
   '{"ru": "Быстрорастущее ампельное растение с серебристо-фиолетовыми листьями."}', 'травянистое', 1, true, false, true),
  ('Nephrolepis', 'nephrolepis-exaltata', 'Nephrolepis exaltata',
   '{"ru": ["Нефролепис возвышенный", "Папоротник"], "en": ["Boston fern", "Sword fern"]}', '{}'::text[],
   '{"ru": "Пышный папоротник, любит влагу и прохладу."}', 'папоротник', 3, false, false, true),
  ('Asplenium', 'asplenium-nidus', 'Asplenium nidus',
   '{"ru": ["Асплениум гнездовой", "Костенец"], "en": ["Bird''s nest fern"]}', '{}'::text[],
   '{"ru": "Папоротник с цельными волнистыми листьями, собранными в «гнездо»."}', 'эпифит', 2, false, false, true),
  ('Schefflera', 'schefflera-arboricola', 'Schefflera arboricola',
   '{"ru": ["Шеффлера древовидная"], "en": ["Dwarf umbrella tree"]}', '{"Heptapleurum arboricola"}'::text[],
   '{"ru": "Деревце с пальчатыми листьями-«зонтиками», есть пёстрые сорта."}', 'дерево', 1, true, false, true),
  ('Hedera', 'hedera-helix', 'Hedera helix',
   '{"ru": ["Плющ обыкновенный"], "en": ["English ivy", "Common ivy"]}', '{}'::text[],
   '{"ru": "Вьющееся растение, любит прохладу; ядовиты листья и ягоды."}', 'лиана', 2, true, true, true),
  ('Oxalis', 'oxalis-triangularis', 'Oxalis triangularis',
   '{"ru": ["Кислица треугольная", "Оксалис"], "en": ["Purple shamrock", "False shamrock"]}', '{"Oxalis regnellii"}'::text[],
   '{"ru": "Фиолетовые листья-бабочки складываются на ночь; растёт из клубеньков."}', 'травянистое', 2, true, true, false),
  ('Euphorbia', 'euphorbia-pulcherrima', 'Euphorbia pulcherrima',
   '{"ru": ["Пуансеттия", "Молочай красивейший", "Рождественская звезда"], "en": ["Poinsettia"]}', '{}'::text[],
   '{"ru": "Зимнее растение с яркими красными прицветниками."}', 'кустарник', 3, true, true, false),
  ('Euphorbia', 'euphorbia-milii', 'Euphorbia milii',
   '{"ru": ["Молочай Миля", "Терновый венец"], "en": ["Crown of thorns"]}', '{}'::text[],
   '{"ru": "Колючий суккулентный кустарник, цветёт почти непрерывно."}', 'суккулент', 1, true, true, false),
  ('Hoya', 'hoya-carnosa', 'Hoya carnosa',
   '{"ru": ["Хойя мясистая", "Восковой плющ"], "en": ["Wax plant"]}', '{}'::text[],
   '{"ru": "Лиана с восковыми листьями и душистыми соцветиями-звёздочками."}', 'лиана', 2, false, false, true),
  ('Ceropegia', 'ceropegia-woodii', 'Ceropegia woodii',
   '{"ru": ["Церопегия Вуда", "Цепочка сердец"], "en": ["String of hearts", "Rosary vine"]}', '{"Ceropegia linearis subsp. woodii"}'::text[],
   '{"ru": "Ампельный суккулент с нитями сердечек-листьев."}', 'суккулент', 1, false, false, false),
  ('Adenium', 'adenium-obesum', 'Adenium obesum',
   '{"ru": ["Адениум тучный", "Пустынная роза"], "en": ["Desert rose"]}', '{}'::text[],
   '{"ru": "Суккулентное деревце с утолщённым стволом и крупными цветками; очень ядовит."}', 'суккулент', 3, true, true, false),
  ('Strelitzia', 'strelitzia-reginae', 'Strelitzia reginae',
   '{"ru": ["Стрелитция королевская", "Райская птица"], "en": ["Bird of paradise"]}', '{}'::text[],
   '{"ru": "Крупное растение с цветками в форме головы птицы."}', 'травянистое', 3, true, false, false),
  ('Guzmania', 'guzmania-lingulata', 'Guzmania lingulata',
   '{"ru": ["Гузмания язычковая"], "en": ["Scarlet star", "Tufted airplant"]}', '{}'::text[],
   '{"ru": "Бромелия с ярким прицветником; после цветения материнская розетка отмирает."}', 'эпифит', 2, false, false, true),
  ('Pelargonium', 'pelargonium-hortorum', 'Pelargonium × hortorum',
   '{"ru": ["Пеларгония зональная", "Герань"], "en": ["Zonal geranium"]}', '{"Pelargonium zonale"}'::text[],
   '{"ru": "Обильно цветущее растение для солнечных окон и балконов."}', 'травянистое', 1, true, false, false),
  ('Cyclamen', 'cyclamen-persicum', 'Cyclamen persicum',
   '{"ru": ["Цикламен персидский"], "en": ["Florist''s cyclamen", "Persian cyclamen"]}', '{}'::text[],
   '{"ru": "Цветёт зимой; любит прохладу и не терпит жары."}', 'травянистое', 4, true, true, false),
  ('Coffea', 'coffea-arabica', 'Coffea arabica',
   '{"ru": ["Кофе аравийский", "Кофейное дерево"], "en": ["Arabian coffee", "Coffee plant"]}', '{}'::text[],
   '{"ru": "Вечнозелёное деревце с глянцевыми листьями, может цвести и плодоносить дома."}', 'дерево', 3, true, false, false)
) as s(genus, slug, latin_name, common_names, synonyms, description, plant_type,
       difficulty, toxic_pets, toxic_humans, air_purifying)
join public.genera g on g.latin_name = s.genus
on conflict do nothing;

insert into public.care_profiles
  (species_id, light, water_interval_summer, water_interval_winter, soil_dryness_before_watering,
   humidity_min_pct, temp_min_c, temp_max_c, fertilize_interval_days, fertilize_months,
   repot_every_years, propagation, tips)
select sp.id, c.light, c.summer, c.winter, c.dryness::jsonb, c.humidity, c.tmin, c.tmax,
       c.fert_days, c.fert_months, c.repot, c.propagation, c.tips::jsonb
from (values
  ('philodendron-hederaceum', 'medium', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 15, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Прищипывайте побеги для густоты", "Легко укореняется в воде"]}'),
  ('thaumatophyllum-bipinnatifidum', 'bright_indirect', 7, 12, '{"ru": "верхние 3–5 см"}', 45, 15, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Нужно много места: листья до метра", "Воздушные корни направляйте в горшок"]}'),
  ('monstera-adansonii', 'bright_indirect', 6, 10, '{"ru": "верхние 2–3 см"}', 50, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Любит опору или подвесное кашпо", "При сухом воздухе листья сохнут по краю"]}'),
  ('epipremnum-pinnatum', 'medium', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 15, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["На опоре листья крупнеют и рассекаются"]}'),
  ('scindapsus-pictus', 'medium', 8, 14, '{"ru": "верхние 3 см"}', 40, 16, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Скрученные листья — пора поливать", "Не любит холодных подоконников"]}'),
  ('aglaonema-commutatum', 'low', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 16, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление","черенки"}'::text[],
   '{"ru": ["Красные сорта требуют больше света, чем зелёные", "Сквозняки вызывают пятна на листьях"]}'),
  ('dieffenbachia-seguine', 'bright_indirect', 6, 10, '{"ru": "верхние 2–3 см"}', 50, 17, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"верхушечные черенки","отрезки ствола"}'::text[],
   '{"ru": ["Работайте в перчатках — сок едкий", "Поворачивайте горшок, чтобы ствол рос ровно"]}'),
  ('alocasia-amazonica', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление","клубеньки"}'::text[],
   '{"ru": ["Зимой может сбросить листья — сократите полив и ждите", "Протирайте листья: любит паутинный клещ"]}'),
  ('anthurium-andraeanum', 'bright_indirect', 6, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"деление","верхушечные черенки"}'::text[],
   '{"ru": ["Грунт — рыхлый, с корой и мхом", "Для цветения нужен яркий рассеянный свет"]}'),
  ('syngonium-podophyllum', 'medium', 6, 10, '{"ru": "верхние 2 см"}', 50, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Обрезайте длинные побеги, чтобы куст был плотным"]}'),
  ('ficus-lyrata', 'bright_indirect', 7, 14, '{"ru": "верхние 3–5 см"}', 40, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","воздушные отводки"}'::text[],
   '{"ru": ["Не переставляйте — сбрасывает листья", "Коричневые пятна по центру листа — перелив"]}'),
  ('ficus-benjamina', 'bright_indirect', 6, 12, '{"ru": "верхние 2–3 см"}', 50, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Сбрасывает листья от сквозняков и перемены места", "Хорошо переносит формирующую обрезку"]}'),
  ('ficus-pumila', 'medium', 4, 7, '{"ru": "верхний слой"}', 50, 12, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Не пересушивайте — листья быстро засыхают"]}'),
  ('dracaena-marginata', 'medium', 10, 20, '{"ru": "верхняя половина горшка"}', 30, 15, 30, 30,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"верхушечные черенки","отрезки ствола"}'::text[],
   '{"ru": ["Коричневые кончики — фтор в воде или сухой воздух", "Лучше недолить, чем перелить"]}'),
  ('dracaena-fragrans', 'medium', 8, 16, '{"ru": "верхние 3–5 см"}', 35, 15, 30, 30,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"верхушечные черенки","отрезки ствола"}'::text[],
   '{"ru": ["Выносит полутень, но пёстрые сорта бледнеют"]}'),
  ('dracaena-sanderiana', 'medium', 7, 10, '{"ru": "не пересыхает"}', 40, 16, 30, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["В воде меняйте воду раз в неделю", "Используйте отстоянную или фильтрованную воду"]}'),
  ('dracaena-angolensis', 'medium', 14, 30, '{"ru": "полностью"}', 20, 12, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"деление","листовые черенки"}'::text[],
   '{"ru": ["Не лейте в центр розетки"]}'),
  ('beaucarnea-recurvata', 'direct', 14, 30, '{"ru": "полностью"}', 20, 10, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена","боковые побеги"}'::text[],
   '{"ru": ["Горшок — широкий и неглубокий", "Зимой полив почти прекратить"]}'),
  ('aspidistra-elatior', 'low', 7, 14, '{"ru": "верхние 3 см"}', 30, 5, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 4, '{"деление"}'::text[],
   '{"ru": ["Прямое солнце обжигает листья", "Выносит прохладу до +5 °C"]}'),
  ('yucca-gigantea', 'direct', 10, 21, '{"ru": "верхняя половина горшка"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 3, '{"отрезки ствола","отпрыски"}'::text[],
   '{"ru": ["Зимой держите в светлом прохладном месте"]}'),
  ('asparagus-setaceus', 'bright_indirect', 4, 8, '{"ru": "верхние 1–2 см"}', 50, 12, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление","семена"}'::text[],
   '{"ru": ["Желтеет и осыпается от пересыхания", "Стебли колючие — работайте в перчатках"]}'),
  ('haworthiopsis-attenuata', 'bright_indirect', 14, 28, '{"ru": "полностью"}', 20, 10, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки"}'::text[],
   '{"ru": ["Лучше яркий рассеянный свет, чем прямое солнце"]}'),
  ('echeveria-elegans', 'direct', 10, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки","листья"}'::text[],
   '{"ru": ["Без солнца вытягивается", "Не опрыскивайте и не лейте на листья"]}'),
  ('kalanchoe-blossfeldiana', 'bright_indirect', 10, 20, '{"ru": "полностью"}', 20, 12, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Для повторного цветения — короткий день 6 недель осенью", "Отцветшие соцветия срезайте"]}'),
  ('sedum-morganianum', 'bright_indirect', 14, 28, '{"ru": "полностью"}', 20, 10, 30, 30,
   '{5,6,7,8}'::smallint[], 3, '{"листья","черенки"}'::text[],
   '{"ru": ["Листья осыпаются от касаний — повесьте повыше", "Пересаживайте только при необходимости"]}'),
  ('schlumbergera-truncata', 'bright_indirect', 7, 10, '{"ru": "верхние 2 см"}', 40, 12, 26, 21,
   '{4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Во время бутонизации не поворачивайте горшок", "Осенью месяц прохлады и редкого полива для закладки бутонов"]}'),
  ('opuntia-microdasys', 'direct', 14, 40, '{"ru": "полностью"}', 20, 5, 35, 30,
   '{5,6,7,8}'::smallint[], 3, '{"сегменты"}'::text[],
   '{"ru": ["Глохидии трудно вынуть из кожи — берите щипцами", "Зимой прохлада и почти без полива"]}'),
  ('maranta-leuconeura', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление","черенки"}'::text[],
   '{"ru": ["Поливайте мягкой водой комнатной температуры", "Сухие кончики — сухой воздух"]}'),
  ('goeppertia-orbifolia', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Держите на поддоне с мокрым керамзитом", "Жёсткая вода оставляет бурые края"]}'),
  ('goeppertia-makoyana', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Скрученные листья — сухой воздух или недолив"]}'),
  ('dypsis-lutescens', 'bright_indirect', 5, 10, '{"ru": "верхние 2–3 см"}', 50, 16, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление","семена"}'::text[],
   '{"ru": ["Коричневые кончики — сухой воздух", "Не обрезайте зелёные листья"]}'),
  ('chamaedorea-elegans', 'low', 6, 12, '{"ru": "верхние 2–3 см"}', 40, 15, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"семена"}'::text[],
   '{"ru": ["Хорошо растёт вдали от окна"]}'),
  ('howea-forsteriana', 'medium', 7, 14, '{"ru": "верхние 3–5 см"}', 40, 12, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Пересаживайте перевалкой — корни ломкие"]}'),
  ('rhapis-excelsa', 'medium', 7, 14, '{"ru": "верхние 3 см"}', 40, 10, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"деление"}'::text[],
   '{"ru": ["Зимой выносит прохладу +10 °C"]}'),
  ('dendrobium-nobile', 'bright_indirect', 5, 14, '{"ru": "кора подсыхает"}', 50, 10, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"детки","черенки псевдобульб"}'::text[],
   '{"ru": ["Осенью нужна прохлада +10–15 °C для закладки бутонов", "Зимой полив сократить до цветения"]}'),
  ('streptocarpus-ionanthus', 'bright_indirect', 5, 8, '{"ru": "верхний слой"}', 50, 18, 26, 14,
   '{2,3,4,5,6,7,8,9,10}'::smallint[], 1, '{"листовые черенки","деление"}'::text[],
   '{"ru": ["Поливайте в поддон или по краю горшка", "Капли на листьях оставляют пятна"]}'),
  ('begonia-rex', 'bright_indirect', 5, 8, '{"ru": "верхние 1–2 см"}', 50, 16, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"листовые черенки","деление"}'::text[],
   '{"ru": ["Не опрыскивайте листья — появляются пятна", "Повышайте влажность поддоном с водой"]}'),
  ('begonia-maculata', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 50, 16, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Прищипывайте верхушки — иначе вытягивается"]}'),
  ('pilea-peperomioides', 'bright_indirect', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 12, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки","черенки"}'::text[],
   '{"ru": ["Поворачивайте горшок раз в неделю — тянется к свету"]}'),
  ('peperomia-obtusifolia', 'medium', 10, 16, '{"ru": "верхняя половина горшка"}', 30, 15, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","листовые черенки"}'::text[],
   '{"ru": ["Перелив опаснее засухи"]}'),
  ('peperomia-argyreia', 'medium', 8, 14, '{"ru": "верхняя половина горшка"}', 40, 16, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"листовые черенки","деление"}'::text[],
   '{"ru": ["Черешки гниют от перелива"]}'),
  ('tradescantia-zebrina', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 40, 12, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Каждую весну омолаживайте черенками", "Без света теряет окраску"]}'),
  ('nephrolepis-exaltata', 'medium', 3, 6, '{"ru": "не пересыхает"}', 60, 12, 24, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление","столоны"}'::text[],
   '{"ru": ["Не допускайте пересыхания кома", "Вдали от батарей"]}'),
  ('asplenium-nidus', 'medium', 5, 8, '{"ru": "верхний слой"}', 50, 16, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"споры"}'::text[],
   '{"ru": ["Не лейте в центр розетки", "Не протирайте листья полиролью"]}'),
  ('schefflera-arboricola', 'bright_indirect', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 14, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","воздушные отводки"}'::text[],
   '{"ru": ["Обрезка весной делает крону пышной"]}'),
  ('hedera-helix', 'medium', 5, 10, '{"ru": "верхние 1–2 см"}', 40, 8, 24, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Зимой в тепле страдает от клеща — держите прохладнее"]}'),
  ('oxalis-triangularis', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 40, 12, 26, 21,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"клубеньки"}'::text[],
   '{"ru": ["Если листья увяли — это период покоя: прекратите полив на месяц"]}'),
  ('euphorbia-pulcherrima', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 50, 16, 24, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Сквозняк и холод — листопад", "Для окрашивания прицветников 8 недель короткого дня осенью"]}'),
  ('euphorbia-milii', 'direct', 10, 21, '{"ru": "полностью"}', 20, 12, 32, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Млечный сок едкий — перчатки обязательны"]}'),
  ('hoya-carnosa', 'bright_indirect', 10, 18, '{"ru": "полностью"}', 40, 15, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"черенки"}'::text[],
   '{"ru": ["Не срезайте отцветшие цветоносы — на них цветёт снова", "Не переставляйте во время бутонизации"]}'),
  ('ceropegia-woodii', 'bright_indirect', 10, 21, '{"ru": "полностью"}', 30, 12, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки","клубеньки"}'::text[],
   '{"ru": ["Плети укореняются, если уложить их на грунт"]}'),
  ('adenium-obesum', 'direct', 7, 30, '{"ru": "полностью"}', 20, 15, 35, 21,
   '{5,6,7,8}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Нужно максимум солнца", "Зимой в прохладе почти без полива"]}'),
  ('strelitzia-reginae', 'direct', 7, 14, '{"ru": "верхние 3–5 см"}', 40, 10, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"деление","семена"}'::text[],
   '{"ru": ["Цветёт в 4–5 лет и при тесном горшке", "Летом выносите на балкон"]}'),
  ('guzmania-lingulata', 'bright_indirect', 7, 14, '{"ru": "верхний слой"}', 60, 18, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки"}'::text[],
   '{"ru": ["Воду наливайте в розетку, раз в месяц меняйте", "Удобрения — половинная доза"]}'),
  ('pelargonium-hortorum', 'direct', 4, 10, '{"ru": "верхние 2 см"}', 30, 10, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"черенки","семена"}'::text[],
   '{"ru": ["Обрезайте весной для пышного куста", "Зимой — прохлада +12–15 °C"]}'),
  ('cyclamen-persicum', 'bright_indirect', 5, 4, '{"ru": "верхний слой"}', 50, 10, 20, 14,
   '{10,11,12,1,2,3}'::smallint[], 2, '{"клубни","семена"}'::text[],
   '{"ru": ["Поливайте в поддон — вода на клубне вызывает гниль", "Летом покой: полив сократить"]}'),
  ('coffea-arabica', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 50, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"семена","черенки"}'::text[],
   '{"ru": ["Не любит известковую воду", "Не переставляйте во время цветения"]}')
) as c(slug, light, summer, winter, dryness, humidity, tmin, tmax, fert_days, fert_months,
       repot, propagation, tips)
join public.species sp on sp.slug = c.slug
on conflict (species_id) do nothing;

-- С ростом базы у запроса бывает несколько совпадений («монстера» — два вида):
-- первым идёт вид, у которого запрос совпадает с названием целиком, затем — с началом названия.
create or replace function public.search_species(q text, lim int default 20)
returns setof public.species
language sql
stable
set search_path = public, extensions
as $$
  with names as (
    select s.id, lower(n) as name
      from public.species s,
           lateral (select s.latin_name
                    union all select unnest(s.synonyms)
                    union all select v from jsonb_each(s.common_names) e,
                                            jsonb_array_elements_text(e.value) v) as t(n)
  )
  select s.*
    from public.species s
   where s.search_text like '%' || lower(q) || '%'
      or s.search_tsv @@ plainto_tsquery('simple', q)
      or word_similarity(lower(q), s.search_text) > 0.4
   order by exists (select 1 from names n where n.id = s.id and n.name = lower(trim(q))) desc,
            exists (select 1 from names n where n.id = s.id and n.name like lower(trim(q)) || '%') desc,
            (s.search_text like '%' || lower(q) || '%') desc,
            word_similarity(lower(q), s.search_text) desc,
            s.latin_name
   limit least(lim, 50);
$$;
