-- Состав грунта (почвосмеси) для каждого вида.
-- Идея: вместо свободного текста в care_profiles.soil_mix держим небольшой справочник
-- проверенных рецептов (public.soil_mixes) — ароидный рыхлый, кактусовый, кислый для вересковых и т. д.
-- Каждый рецепт — компоненты в процентах (в сумме ровно 100), pH, дренаж, мульча сверху, горшок,
-- оценки влагоёмкости и воздухопроницаемости (1–5) и практические советы, включая готовый магазинный вариант.
-- Каждому виду назначен один рецепт (care_profiles.soil_mix_slug) и, где это действительно важно,
-- поправка под конкретный вид (care_profiles.soil_note).
-- Идентификаторы материалов фиксированы — сайт знает для них названия и цвета:
-- sod_soil, leaf_soil, peat, sphagnum_peat, coir, conifer_soil, humus, sand, perlite, vermiculite,
-- pumice, zeolite, akadama, lava, bark_fine, bark, sphagnum, charcoal, clay_pebbles, gravel.
-- Миграция идемпотентна: повторный запуск обновляет рецепты и назначения, ничего не дублируя.

create table if not exists public.soil_mixes (
  slug            text primary key,
  name            jsonb not null,
  summary         jsonb not null,
  components      jsonb not null check (jsonb_typeof(components) = 'array'),
  ph_min          numeric(3,1) not null,
  ph_max          numeric(3,1) not null,
  drainage        jsonb,
  top_layer       jsonb,
  pot             jsonb not null,
  water_retention smallint not null check (water_retention between 1 and 5),
  aeration        smallint not null check (aeration between 1 and 5),
  tips            jsonb not null default '{}',
  sort            smallint not null,
  check (ph_min <= ph_max)
);

-- База знаний: читают все (включая гостей), пишет только service_role (админка).
alter table public.soil_mixes enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies
                  where schemaname = 'public' and tablename = 'soil_mixes' and policyname = 'kb_read') then
    create policy kb_read on public.soil_mixes for select to anon, authenticated using (true);
  end if;
end $$;

alter table public.care_profiles
  add column if not exists soil_mix_slug text references public.soil_mixes(slug),
  add column if not exists soil_note jsonb;
create index if not exists care_profiles_soil_mix_slug_idx on public.care_profiles (soil_mix_slug);

insert into public.soil_mixes
  (slug, name, summary, components, ph_min, ph_max, drainage, top_layer, pot, water_retention, aeration, tips, sort)
values
  ('universal',
   '{"ru": "Универсальный для лиственных"}'::jsonb,
   '{"ru": "Для большинства лиственных и неприхотливых комнатных растений: держит влагу, но не закисает благодаря перлиту и коре."}'::jsonb,
   '[{"material": "peat", "pct": 40, "role": "base"}, {"material": "leaf_soil", "pct": 20, "role": "base"}, {"material": "perlite", "pct": 20, "role": "loosener"}, {"material": "bark_fine", "pct": 10, "role": "loosener"}, {"material": "vermiculite", "pct": 5, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Пластиковый или керамический горшок с отверстиями, на 2–3 см шире кома."}'::jsonb,
   3, 3,
   '{"ru": ["Готовый вариант: универсальный грунт для комнатных растений + 25% перлита.", "Покупной торфяной грунт часто слишком плотный — всегда добавляйте разрыхлитель.", "Уголь можно заменить цеолитом: он тоже впитывает лишнее и не даёт грунту закиснуть."]}'::jsonb,
   10),
  ('aroid_chunky',
   '{"ru": "Ароидный рыхлый"}'::jsonb,
   '{"ru": "Для монстер, филодендронов, антуриумов, сингониумов и эпипремнумов: их воздушным корням нужен крупный, дышащий субстрат с корой."}'::jsonb,
   '[{"material": "peat", "pct": 30, "role": "base"}, {"material": "bark_fine", "pct": 30, "role": "loosener"}, {"material": "perlite", "pct": 20, "role": "loosener"}, {"material": "coir", "pct": 10, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}, {"material": "humus", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Пластиковый горшок с отверстиями; для лиан сразу ставьте опору из кокоса или мха."}'::jsonb,
   3, 4,
   '{"ru": ["Готовый вариант: грунт для ароидных, либо универсальный грунт + 30% коры + 20% перлита.", "Воздушные корни можно направить в грунт или на моховую опору — не обрезайте их.", "Смесь должна рассыпаться в кулаке: если после сжатия остаётся плотный ком — добавьте коры."]}'::jsonb,
   20),
  ('aroid_moist',
   '{"ru": "Для алоказий и влаголюбивых ароидных"}'::jsonb,
   '{"ru": "Для алоказий, спатифиллумов и каладиумов: равномерно влажный, но быстро пропускающий воду грунт — корни любят влагу и боятся застоя."}'::jsonb,
   '[{"material": "peat", "pct": 30, "role": "base"}, {"material": "bark_fine", "pct": 25, "role": "loosener"}, {"material": "pumice", "pct": 20, "role": "drainage"}, {"material": "coir", "pct": 10, "role": "moisture"}, {"material": "sphagnum", "pct": 10, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Пластиковый горшок по размеру кома, с большим количеством отверстий; для алоказий удобен прозрачный — видно корни."}'::jsonb,
   3, 4,
   '{"ru": ["Готовый вариант: грунт для ароидных + 20% пемзы или перлита.", "Не берите горшок «на вырост»: лишний объём грунта у алоказий почти всегда закисает.", "Сфагнум нарежьте ножницами на кусочки 1–2 см, иначе он сваливается комками."]}'::jsonb,
   30),
  ('tropical_moist',
   '{"ru": "Марантовые и влаголюбивые тропики"}'::jsonb,
   '{"ru": "Для калатей, маранты, фиттоний и селагинелл: мягкий влагоёмкий грунт, который не пересыхает за день, но и не превращается в болото."}'::jsonb,
   '[{"material": "peat", "pct": 40, "role": "base"}, {"material": "leaf_soil", "pct": 20, "role": "base"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "coir", "pct": 10, "role": "moisture"}, {"material": "vermiculite", "pct": 10, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Широкий невысокий пластиковый горшок: корни марантовых неглубокие."}'::jsonb,
   4, 3,
   '{"ru": ["Готовый вариант: грунт для марантовых/калатей или универсальный + 20% перлита + 10% вермикулита.", "Поливайте мягкой отстоянной водой — жёсткая вода засоляет такой грунт, и кончики листьев сохнут.", "Вермикулит не заменяйте песком: песок утяжелит смесь и она станет плотной."]}'::jsonb,
   40),
  ('fern',
   '{"ru": "Для папоротников"}'::jsonb,
   '{"ru": "Для нефролеписа, адиантума и других наземных папоротников: лёгкий, лесной, слегка кислый грунт, долго сохраняющий влагу."}'::jsonb,
   '[{"material": "leaf_soil", "pct": 30, "role": "base"}, {"material": "peat", "pct": 30, "role": "base"}, {"material": "bark_fine", "pct": 15, "role": "loosener"}, {"material": "perlite", "pct": 10, "role": "loosener"}, {"material": "sphagnum", "pct": 10, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.0, 6.0, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Широкий пластиковый горшок или плошка; для нефролеписа хороша подвесная кашпо."}'::jsonb,
   4, 3,
   '{"ru": ["Готовый вариант: грунт для папоротников или универсальный + 20% коры + 10% сфагнума.", "Листовая земля — главное: папоротники живут в лесной подстилке.", "Если ком пересох — погрузите горшок в воду на 20 минут, сверху такой грунт промокает плохо."]}'::jsonb,
   50),
  ('palm_tree',
   '{"ru": "Пальмы, драцены и крупные деревца"}'::jsonb,
   '{"ru": "Для пальм, драцен, шеффлер и других крупных растений: более тяжёлый и питательный грунт на дерновой земле держит высокий ствол и не выдыхается годами."}'::jsonb,
   '[{"material": "sod_soil", "pct": 30, "role": "base"}, {"material": "peat", "pct": 25, "role": "base"}, {"material": "leaf_soil", "pct": 15, "role": "base"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "bark_fine", "pct": 10, "role": "loosener"}, {"material": "sand", "pct": 5, "role": "drainage"}]'::jsonb,
   6.0, 7.0, '{"material": "clay_pebbles", "cm": 3}'::jsonb, null,
   '{"ru": "Тяжёлый устойчивый горшок (керамика) — высокие растения опрокидываются; для пальм — высокий, по форме корней."}'::jsonb,
   3, 3,
   '{"ru": ["Готовый вариант: грунт для пальм или для драцен + 20% перлита.", "Крупные экземпляры не пересаживают, а ежегодно меняют верхние 5 см грунта.", "Дерновую землю лучше прогреть в духовке или пролить кипятком — в ней бывают вредители."]}'::jsonb,
   60),
  ('ficus',
   '{"ru": "Для фикусов"}'::jsonb,
   '{"ru": "Для фикусов: плотный, но воздухопроницаемый грунт средней питательности, в котором не закисают толстые корни."}'::jsonb,
   '[{"material": "sod_soil", "pct": 25, "role": "base"}, {"material": "peat", "pct": 25, "role": "base"}, {"material": "leaf_soil", "pct": 20, "role": "base"}, {"material": "bark_fine", "pct": 15, "role": "loosener"}, {"material": "perlite", "pct": 10, "role": "loosener"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 3}'::jsonb, null,
   '{"ru": "Пластиковый горшок для молодых растений, тяжёлый керамический — для высоких деревьев."}'::jsonb,
   3, 3,
   '{"ru": ["Готовый вариант: грунт для фикусов + 15% коры или перлита.", "Фикусы не любят частых пересадок — меняйте горшок, только когда корни оплели ком.", "Лировидному фикусу особенно важен дренаж: он сбрасывает листья при закисании корней."]}'::jsonb,
   70),
  ('cactus_succulent',
   '{"ru": "Кактусы и суккуленты"}'::jsonb,
   '{"ru": "Для кактусов, толстянок, алоэ, хавортий и сансевиерий: быстро просыхающий грунт с большим количеством минеральных частиц — корни не гниют между редкими поливами."}'::jsonb,
   '[{"material": "peat", "pct": 30, "role": "base"}, {"material": "pumice", "pct": 30, "role": "drainage"}, {"material": "sand", "pct": 15, "role": "drainage"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "zeolite", "pct": 5, "role": "additive"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   6.0, 7.0, '{"material": "clay_pebbles", "cm": 2}'::jsonb, '{"material": "gravel"}'::jsonb,
   '{"ru": "Неглазурованный глиняный горшок или пластик с отверстиями; широкий и невысокий для большинства видов."}'::jsonb,
   2, 4,
   '{"ru": ["Готовый вариант: грунт для кактусов + 30% пемзы.", "Пересаживайте в сухой грунт и не поливайте 5–7 дней, чтобы подсохли повреждённые корни.", "Гравий сверху защищает корневую шейку от гнили и не даёт смеси зарастать мхом."]}'::jsonb,
   80),
  ('mesembs_mineral',
   '{"ru": "Литопсы и мезембы (почти минеральный)"}'::jsonb,
   '{"ru": "Для литопсов, плейоспилосов и других «живых камней»: почти минеральная смесь, которая сохнет за день-два — единственный способ уберечь их от перелива."}'::jsonb,
   '[{"material": "pumice", "pct": 35, "role": "drainage"}, {"material": "lava", "pct": 20, "role": "drainage"}, {"material": "sand", "pct": 15, "role": "drainage"}, {"material": "peat", "pct": 10, "role": "base"}, {"material": "zeolite", "pct": 10, "role": "additive"}, {"material": "akadama", "pct": 10, "role": "moisture"}]'::jsonb,
   6.5, 7.5, null, '{"material": "gravel"}'::jsonb,
   '{"ru": "Глубокий узкий горшок (корень стержневой) из пластика или необожжённой глины; несколько литопсов — группой в одном горшке."}'::jsonb,
   1, 5,
   '{"ru": ["Готовый вариант: грунт для кактусов + 50% пемзы или цеолитового наполнителя без ароматизаторов.", "Отдельный дренажный слой не нужен — вся смесь и есть дренаж.", "Засыпьте «камешки» гравием до середины высоты — так они стоят ровно и не гниют у основания."]}'::jsonb,
   90),
  ('caudex',
   '{"ru": "Каудексы, адениумы и пахиподиумы"}'::jsonb,
   '{"ru": "Для адениумов, пахиподиумов, бокарней и других растений с утолщённым стволом: рыхлый, быстро сохнущий, но чуть питательнее кактусового грунт."}'::jsonb,
   '[{"material": "peat", "pct": 25, "role": "base"}, {"material": "pumice", "pct": 25, "role": "drainage"}, {"material": "perlite", "pct": 20, "role": "loosener"}, {"material": "bark_fine", "pct": 10, "role": "loosener"}, {"material": "sand", "pct": 10, "role": "drainage"}, {"material": "zeolite", "pct": 5, "role": "additive"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   6.0, 7.0, '{"material": "clay_pebbles", "cm": 3}'::jsonb, '{"material": "gravel"}'::jsonb,
   '{"ru": "Широкая невысокая плошка (для адениума — чтобы каудекс рос вширь); тяжёлая керамика для высоких пахиподиумов."}'::jsonb,
   2, 4,
   '{"ru": ["Готовый вариант: грунт для кактусов + 20% кокосового субстрата + 20% пемзы.", "Каудекс не заглубляют — при каждой пересадке его можно приподнимать.", "Летом такие растения пьют много, зимой при прохладе поливы почти прекращают."]}'::jsonb,
   100),
  ('orchid_bark',
   '{"ru": "Орхидеи-эпифиты (кора)"}'::jsonb,
   '{"ru": "Для фаленопсисов, дендробиумов, каттлей и онцидиумов: корни в природе висят на деревьях, поэтому им нужна крупная кора и воздух, а не земля."}'::jsonb,
   '[{"material": "bark", "pct": 75, "role": "base"}, {"material": "sphagnum", "pct": 15, "role": "moisture"}, {"material": "charcoal", "pct": 10, "role": "additive"}]'::jsonb,
   5.5, 6.5, null, null,
   '{"ru": "Прозрачный пластиковый горшок с отверстиями в дне и по бокам — корни фотосинтезируют и по ним видно, когда поливать."}'::jsonb,
   2, 5,
   '{"ru": ["Готовый вариант: кора для орхидей фракции 1–2 см; сфагнум добавьте сами.", "Кору перед посадкой прокипятите или замочите на сутки — сухая кора отталкивает воду.", "Меняйте субстрат раз в 2–3 года: разложившаяся кора становится трухой и душит корни."]}'::jsonb,
   110),
  ('orchid_terrestrial',
   '{"ru": "Наземные орхидеи"}'::jsonb,
   '{"ru": "Для пафиопедилумов, лудизии и цимбидиумов: мельче и влагоёмче коры для эпифитов, с долей торфа — их корни не должны пересыхать полностью."}'::jsonb,
   '[{"material": "bark_fine", "pct": 40, "role": "base"}, {"material": "sphagnum", "pct": 20, "role": "moisture"}, {"material": "peat", "pct": 15, "role": "base"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "charcoal", "pct": 10, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Непрозрачный пластиковый горшок, невысокий: корни наземных орхидей света не любят."}'::jsonb,
   3, 4,
   '{"ru": ["Готовый вариант: мелкая кора для орхидей + 20% сфагнума + 15% торфяного грунта.", "Лудизию сажают неглубоко — ползучий стебель лежит на поверхности.", "Субстрат меняют ежегодно: мелкая кора разлагается быстрее крупной."]}'::jsonb,
   120),
  ('air_epiphyte',
   '{"ru": "Ванды и атмосферные — без грунта"}'::jsonb,
   '{"ru": "Для ванд и серых тилландсий: субстрат им не нужен вовсе — корни или листья впитывают воду при купании, а в грунте гниют; кора лишь фиксирует растение."}'::jsonb,
   '[{"material": "bark", "pct": 80, "role": "base"}, {"material": "charcoal", "pct": 20, "role": "additive"}]'::jsonb,
   5.5, 6.5, null, null,
   '{"ru": "Подвесная корзинка-решётка или высокая стеклянная ваза без субстрата; тилландсии — на коряге, ракушке или проволочной подставке."}'::jsonb,
   1, 5,
   '{"ru": ["Готовый вариант: без грунта — крупные куски коры или угля только для фиксации в корзинке.", "Ванду купают: корни на 15–30 минут в воду, пока не позеленеют, затем полностью обсушивают.", "Тилландсию после купания кладут розеткой вниз — вода в пазухах вызывает гниль."]}'::jsonb,
   130),
  ('bromeliad_epiphyte',
   '{"ru": "Бромелии и эпифитные кактусы"}'::jsonb,
   '{"ru": "Для гузманий, эхмей, вриезий, шлюмбергеры и рипсалиса: лёгкий кислый субстрат с корой — в природе они растут на деревьях и в подстилке."}'::jsonb,
   '[{"material": "bark_fine", "pct": 40, "role": "base"}, {"material": "peat", "pct": 25, "role": "base"}, {"material": "sphagnum", "pct": 15, "role": "moisture"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.0, 6.0, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Небольшой устойчивый горшок: корневая система маленькая, розетке важнее не опрокинуться; эпифитные кактусы — в подвесном кашпо."}'::jsonb,
   2, 4,
   '{"ru": ["Готовый вариант: грунт для бромелий или грунт для орхидей + 30% торфяного грунта.", "У бромелий воду наливают в розетку, а субстрат лишь слегка увлажняют.", "Шлюмбергеру и рипсалис пересаживают сразу после цветения, не раньше."]}'::jsonb,
   140),
  ('gesneriad',
   '{"ru": "Геснериевые (фиалки, стрептокарпусы, глоксинии)"}'::jsonb,
   '{"ru": "Для сенполий, стрептокарпусов, глоксиний и эписций: очень лёгкий, пушистый торфяной грунт — нежные волосковые корни задыхаются в плотной земле."}'::jsonb,
   '[{"material": "peat", "pct": 50, "role": "base"}, {"material": "perlite", "pct": 20, "role": "loosener"}, {"material": "vermiculite", "pct": 15, "role": "moisture"}, {"material": "sphagnum", "pct": 10, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 1}'::jsonb, null,
   '{"ru": "Маленький пластиковый горшок: диаметр в 2–3 раза меньше розетки; возможен фитильный полив."}'::jsonb,
   3, 4,
   '{"ru": ["Готовый вариант: грунт для фиалок + 20% перлита + 10% вермикулита.", "Для фитильного полива увеличьте долю перлита до 40% — иначе грунт переувлажнится.", "Не утрамбовывайте грунт — только постучите горшком по столу."]}'::jsonb,
   150),
  ('acidic',
   '{"ru": "Кислый для вересковых"}'::jsonb,
   '{"ru": "Для азалий, гортензий, камелий, гардений и муррайи: кислый грунт на верховом торфе и хвойной земле — в нейтральном они не усваивают железо и желтеют."}'::jsonb,
   '[{"material": "sphagnum_peat", "pct": 40, "role": "base"}, {"material": "conifer_soil", "pct": 25, "role": "base"}, {"material": "bark_fine", "pct": 15, "role": "loosener"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "sphagnum", "pct": 5, "role": "moisture"}]'::jsonb,
   4.5, 5.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Широкий неглубокий пластиковый горшок: корни азалий поверхностные; для камелии — глубже."}'::jsonb,
   4, 3,
   '{"ru": ["Готовый вариант: грунт для азалий или рододендронов + 20% перлита.", "Поливайте мягкой водой; раз в месяц можно подкислить: несколько кристаллов лимонной кислоты на литр.", "Не используйте известковый песок и золу — они быстро нейтрализуют кислотность."]}'::jsonb,
   160),
  ('citrus_mediterranean',
   '{"ru": "Цитрусовые и средиземноморские"}'::jsonb,
   '{"ru": "Для лимонов, мандаринов, оливы, мирта, лавра и олеандра: питательный грунт на дерновой земле с песком — плотнее обычного, хорошо держит структуру годами."}'::jsonb,
   '[{"material": "sod_soil", "pct": 35, "role": "base"}, {"material": "leaf_soil", "pct": 20, "role": "base"}, {"material": "sand", "pct": 15, "role": "drainage"}, {"material": "humus", "pct": 10, "role": "additive"}, {"material": "peat", "pct": 10, "role": "base"}, {"material": "perlite", "pct": 10, "role": "loosener"}]'::jsonb,
   6.0, 7.0, '{"material": "clay_pebbles", "cm": 3}'::jsonb, null,
   '{"ru": "Керамический или деревянный горшок (кадка), глубиной не меньше ширины; обязательно с отверстиями."}'::jsonb,
   3, 3,
   '{"ru": ["Готовый вариант: грунт для цитрусовых + 15% перлита.", "Цитрусы пересаживают перевалкой весной, корневую шейку не заглубляют.", "Оливе, розмарину и олеандру дайте больше песка — они засухоустойчивее цитрусов."]}'::jsonb,
   170),
  ('carnivorous',
   '{"ru": "Хищные растения"}'::jsonb,
   '{"ru": "Для мухоловки, саррацении и непентеса: бедный и кислый субстрат без удобрений — корни хищников сгорают от любых солей."}'::jsonb,
   '[{"material": "sphagnum_peat", "pct": 50, "role": "base"}, {"material": "perlite", "pct": 30, "role": "loosener"}, {"material": "sphagnum", "pct": 20, "role": "moisture"}]'::jsonb,
   4.0, 5.0, null, null,
   '{"ru": "Пластиковый горшок с отверстиями, стоящий в поддоне с дистиллированной водой (кроме непентеса — подвесное кашпо)."}'::jsonb,
   5, 3,
   '{"ru": ["Готовый вариант: чистый верховой торф без удобрений + 30% перлита (перлит промойте).", "Никаких удобрений, золы и водопроводной воды — только дистиллированная, дождевая или осмос.", "Проверяйте состав торфа: «обогащённый» или «раскисленный» для хищных не подходит."]}'::jsonb,
   180),
  ('flowering',
   '{"ru": "Цветущие и балконные"}'::jsonb,
   '{"ru": "Для пеларгоний, фуксий, бальзаминов, хризантем и пряных трав: питательный влагоёмкий грунт для быстрого роста и обильного цветения."}'::jsonb,
   '[{"material": "peat", "pct": 40, "role": "base"}, {"material": "leaf_soil", "pct": 20, "role": "base"}, {"material": "humus", "pct": 15, "role": "additive"}, {"material": "perlite", "pct": 15, "role": "loosener"}, {"material": "vermiculite", "pct": 10, "role": "moisture"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Пластиковый горшок или балконный ящик с отверстиями; для однолетников — не меньше 1,5 л на куст."}'::jsonb,
   4, 3,
   '{"ru": ["Готовый вариант: грунт для цветущих растений + 15% перлита.", "Биогумус даёт запас питания на месяц; дальше подкармливайте каждые 1–2 недели.", "В жару в балконных ящиках грунт сохнет быстро — вермикулит и гидрогель выручают."]}'::jsonb,
   190),
  ('bonsai',
   '{"ru": "Бонсай и мелколистные деревца"}'::jsonb,
   '{"ru": "Для кармоны, фикуса микрокарпа и других деревьев-бонсай: зернистая смесь на акадаме, в которой корни ветвятся мелко и не загнивают в неглубокой плошке."}'::jsonb,
   '[{"material": "akadama", "pct": 40, "role": "base"}, {"material": "pumice", "pct": 25, "role": "drainage"}, {"material": "lava", "pct": 15, "role": "drainage"}, {"material": "bark_fine", "pct": 10, "role": "loosener"}, {"material": "peat", "pct": 10, "role": "base"}]'::jsonb,
   6.0, 7.0, '{"material": "lava", "cm": 1}'::jsonb, null,
   '{"ru": "Керамическая плошка для бонсай с крупными отверстиями, затянутыми сеткой, и проволокой для фиксации."}'::jsonb,
   3, 5,
   '{"ru": ["Готовый вариант: смесь для бонсай или акадама + 30% пемзы.", "Просейте компоненты от пыли — мелочь забивает поры и душит корни.", "Акадама темнеет, когда влажная, и светлеет, когда пора поливать — удобный индикатор."]}'::jsonb,
   200),
  ('bulbous',
   '{"ru": "Луковичные и клубневые"}'::jsonb,
   '{"ru": "Для гиппеаструма, эухариса, кливии и цикламена: рыхлый грунт с песком — луковица не должна стоять в сырости, а корни просят питания."}'::jsonb,
   '[{"material": "sod_soil", "pct": 30, "role": "base"}, {"material": "leaf_soil", "pct": 25, "role": "base"}, {"material": "peat", "pct": 15, "role": "base"}, {"material": "sand", "pct": 15, "role": "drainage"}, {"material": "perlite", "pct": 10, "role": "loosener"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   6.0, 7.0, '{"material": "clay_pebbles", "cm": 3}'::jsonb, null,
   '{"ru": "Тяжёлый глубокий горшок, лишь на 3–4 см шире луковицы: в тесноте луковичные цветут охотнее."}'::jsonb,
   2, 3,
   '{"ru": ["Готовый вариант: грунт для луковичных или универсальный + 20% песка и перлита.", "Луковицу гиппеаструма заглубляют на половину-треть, эухариса — на 1–2 см.", "Под донце насыпьте горсть чистого песка — это страхует от гнили."]}'::jsonb,
   210),
  ('epiphytic_vine',
   '{"ru": "Хойи, пеперомии и эпифитные лианы"}'::jsonb,
   '{"ru": "Для хой, пеперомий и мединиллы: воздушная смесь коры и перлита — в природе они растут на стволах и ветках, и корни гниют в плотном грунте."}'::jsonb,
   '[{"material": "bark_fine", "pct": 35, "role": "loosener"}, {"material": "peat", "pct": 25, "role": "base"}, {"material": "perlite", "pct": 25, "role": "loosener"}, {"material": "coir", "pct": 10, "role": "moisture"}, {"material": "charcoal", "pct": 5, "role": "additive"}]'::jsonb,
   5.5, 6.5, '{"material": "clay_pebbles", "cm": 2}'::jsonb, null,
   '{"ru": "Небольшой пластиковый горшок или подвесное кашпо: хойи цветут в тесноте."}'::jsonb,
   2, 5,
   '{"ru": ["Готовый вариант: грунт для орхидей + 30% универсального грунта + 20% перлита.", "Хою не пересаживают в большой горшок — это задерживает цветение на годы.", "Пеперомиям смесь можно чуть уплотнить (5–10% листовой земли) — они мельче и сохнут быстрее."]}'::jsonb,
   220)
on conflict (slug) do update set
  name = excluded.name, summary = excluded.summary, components = excluded.components,
  ph_min = excluded.ph_min, ph_max = excluded.ph_max, drainage = excluded.drainage,
  top_layer = excluded.top_layer, pot = excluded.pot, water_retention = excluded.water_retention,
  aeration = excluded.aeration, tips = excluded.tips, sort = excluded.sort;

update public.care_profiles c
   set soil_mix_slug = v.mix,
       soil_note = v.note::jsonb
  from (values
    ('acalypha-hispida', 'universal', null),
    ('adenium-obesum', 'caudex', '{"ru": "Каудекс при пересадке приподнимайте над грунтом — открытые корни формируют красивое основание."}'),
    ('adiantum-raddianum', 'fern', '{"ru": "Адиантум предпочитает почти нейтральную среду: добавьте щепоть доломитовой муки на литр смеси."}'),
    ('adromischus-cristatus', 'cactus_succulent', null),
    ('aechmea-fasciata', 'bromeliad_epiphyte', null),
    ('aeonium-arboreum', 'cactus_succulent', '{"ru": "Эониум пьёт больше других суккулентов: замените часть пемзы на 10% листовой земли."}'),
    ('aeschynanthus-radicans', 'gesneriad', '{"ru": "Эпифит: замените вермикулит на мелкую кору — смесь должна быть рыхлее, лучше в подвесном кашпо."}'),
    ('agave-attenuata', 'cactus_succulent', null),
    ('aglaonema-commutatum', 'aroid_chunky', null),
    ('alocasia-amazonica', 'aroid_moist', null),
    ('alocasia-baginda', 'aroid_moist', '{"ru": "Ювелирная алоказия: доведите пемзу до 30% и берите совсем маленький горшок."}'),
    ('alocasia-cuprea', 'aroid_moist', '{"ru": "Ювелирная алоказия: доведите пемзу до 30% и берите совсем маленький горшок."}'),
    ('alocasia-micholitziana', 'aroid_moist', null),
    ('alocasia-reginula', 'aroid_moist', '{"ru": "Ювелирная алоказия: доведите пемзу до 30% и берите совсем маленький горшок."}'),
    ('alocasia-zebrina', 'aroid_moist', null),
    ('aloe-vera', 'cactus_succulent', null),
    ('anacampseros-rufescens', 'cactus_succulent', '{"ru": "Мелкий суккулент: добавьте ещё 10% пемзы, торфа поменьше."}'),
    ('ananas-comosus', 'bromeliad_epiphyte', '{"ru": "Наземная бромелия: добавьте 20% листовой земли, горшок шире обычного."}'),
    ('anthurium-andraeanum', 'aroid_chunky', null),
    ('anthurium-clarinervium', 'aroid_chunky', '{"ru": "Бархатным антуриумам — до 40% коры и 10% сфагнума, горшок невысокий."}'),
    ('anthurium-hookeri', 'aroid_chunky', '{"ru": "Антуриум «птичье гнездо» — эпифит: коры можно до 40%, розетку не заглублять."}'),
    ('aphelandra-squarrosa', 'tropical_moist', null),
    ('araucaria-heterophylla', 'palm_tree', '{"ru": "Замените часть торфа на 20% хвойной земли — араукария любит слегка кислый грунт."}'),
    ('ardisia-crenata', 'universal', null),
    ('aristaloe-aristata', 'cactus_succulent', null),
    ('asparagus-setaceus', 'universal', '{"ru": "Мясистые корни-клубеньки быстро заполняют горшок — берите посуду на размер больше."}'),
    ('aspidistra-elatior', 'palm_tree', null),
    ('asplenium-nidus', 'fern', '{"ru": "Эпифитный папоротник: добавьте ещё 15% коры и не заглубляйте центр розетки."}'),
    ('astrophytum-myriostigma', 'cactus_succulent', '{"ru": "Астрофитумы любят известь: добавьте немного измельчённой яичной скорлупы."}'),
    ('aucuba-japonica', 'universal', null),
    ('beaucarnea-recurvata', 'caudex', null),
    ('begonia-maculata', 'gesneriad', '{"ru": "Для рослой бегонии добавьте 10% мелкой коры — стебли тростниковых бегоний гниют в сыром грунте."}'),
    ('begonia-rex', 'gesneriad', null),
    ('blechnum-gibbum', 'fern', null),
    ('bougainvillea-glabra', 'citrus_mediterranean', null),
    ('brighamia-insignis', 'caudex', null),
    ('browallia-speciosa', 'flowering', null),
    ('caladium-bicolor', 'aroid_moist', '{"ru": "Клубень сажают на 2–3 см; в период покоя грунт держат почти сухим."}'),
    ('calceolaria-herbeohybrida', 'flowering', null),
    ('callisia-repens', 'universal', null),
    ('camellia-japonica', 'acidic', null),
    ('carissa-macrocarpa', 'citrus_mediterranean', null),
    ('cattleya-hybrida', 'orchid_bark', '{"ru": "Каттлеям — крупная кора без сфагнума и полное просыхание между поливами."}'),
    ('ceropegia-woodii', 'cactus_succulent', null),
    ('chamaedorea-elegans', 'palm_tree', null),
    ('chamaerops-humilis', 'palm_tree', null),
    ('chlorophytum-comosum', 'universal', null),
    ('chlorophytum-orchidastrum', 'universal', null),
    ('chrysanthemum-morifolium', 'flowering', null),
    ('cissus-rhombifolia', 'universal', null),
    ('citrus-japonica', 'citrus_mediterranean', null),
    ('citrus-limon', 'citrus_mediterranean', null),
    ('citrus-microcarpa', 'citrus_mediterranean', null),
    ('citrus-reticulata', 'citrus_mediterranean', null),
    ('citrus-sinensis', 'citrus_mediterranean', null),
    ('clerodendrum-thomsoniae', 'universal', null),
    ('clivia-miniata', 'bulbous', '{"ru": "Кливия цветёт в тесноте: пересаживайте, только когда корни вылезают из горшка."}'),
    ('clusia-rosea', 'aroid_chunky', null),
    ('cocos-nucifera', 'palm_tree', '{"ru": "Орех не заглубляют — он остаётся наполовину над грунтом; добавьте 10% песка."}'),
    ('codiaeum-variegatum', 'universal', null),
    ('coffea-arabica', 'acidic', '{"ru": "Кофе менее требователен: половину верхового торфа можно заменить листовой землёй."}'),
    ('coleus-scutellarioides', 'flowering', null),
    ('columnea-gloriosa', 'gesneriad', '{"ru": "Эпифит: замените вермикулит на мелкую кору и сажайте в подвесное кашпо."}'),
    ('cordyline-fruticosa', 'palm_tree', null),
    ('corokia-cotoneaster', 'citrus_mediterranean', null),
    ('cotyledon-orbiculata', 'cactus_succulent', null),
    ('crassula-muscosa', 'cactus_succulent', null),
    ('crassula-ovata', 'cactus_succulent', null),
    ('crassula-perforata', 'cactus_succulent', null),
    ('crossandra-infundibuliformis', 'flowering', null),
    ('cryptanthus-bivittatus', 'bromeliad_epiphyte', '{"ru": "Наземная бромелия: добавьте 10% листовой земли."}'),
    ('ctenanthe-burle-marxii', 'tropical_moist', null),
    ('cupressus-macrocarpa', 'acidic', '{"ru": "Кипарису — плюс 15% дерновой земли для веса и структуры, и прохладная зимовка."}'),
    ('curio-rowleyanus', 'cactus_succulent', '{"ru": "Широкая неглубокая плошка; бусины не засыпайте грунтом — они гниют."}'),
    ('cycas-revoluta', 'caudex', '{"ru": "Саговник растёт медленно: горшок лишь чуть больше ствола, пересадка раз в 3–5 лет."}'),
    ('cyclamen-persicum', 'bulbous', '{"ru": "Клубень на треть выступает над грунтом; поливайте по краю горшка или через поддон."}'),
    ('cymbidium-hybridum', 'orchid_terrestrial', '{"ru": "Цимбидиуму нужен высокий горшок и более крупная кора: у него длинные толстые корни."}'),
    ('davallia-fejeensis', 'fern', '{"ru": "Мохнатые корневища стелются по поверхности — плошка, корневища не засыпать."}'),
    ('dendrobium-nobile', 'orchid_bark', null),
    ('dieffenbachia-seguine', 'aroid_chunky', null),
    ('dionaea-muscipula', 'carnivorous', null),
    ('dracaena-angolensis', 'cactus_succulent', null),
    ('dracaena-fragrans', 'palm_tree', null),
    ('dracaena-marginata', 'palm_tree', '{"ru": "Драцена окаймлённая боится перелива: добавьте ещё 10% перлита."}'),
    ('dracaena-reflexa', 'palm_tree', null),
    ('dracaena-sanderiana', 'universal', '{"ru": "Часто растёт в воде или гидрогеле: меняйте воду раз в 2 недели; в грунте — не пересушивать."}'),
    ('dracaena-trifasciata', 'cactus_succulent', '{"ru": "Широкий неглубокий тяжёлый горшок: корни поверхностные, а высокие листья валят лёгкий пластик."}'),
    ('dypsis-lutescens', 'palm_tree', null),
    ('echeveria-elegans', 'cactus_succulent', null),
    ('ehretia-microphylla', 'bonsai', '{"ru": "Кармона не терпит пересыхания — можно добавить 10% торфа или кокоса."}'),
    ('epiphyllum-oxypetalum', 'bromeliad_epiphyte', null),
    ('epipremnum-aureum', 'aroid_chunky', null),
    ('epipremnum-pinnatum', 'aroid_chunky', null),
    ('episcia-cupreata', 'gesneriad', null),
    ('eucharis-grandiflora', 'bulbous', null),
    ('euphorbia-meloformis', 'cactus_succulent', null),
    ('euphorbia-milii', 'cactus_succulent', null),
    ('euphorbia-pulcherrima', 'universal', null),
    ('euphorbia-trigona', 'cactus_succulent', null),
    ('exacum-affine', 'flowering', null),
    ('fatshedera-lizei', 'universal', null),
    ('fatsia-japonica', 'universal', null),
    ('ficus-altissima', 'ficus', null),
    ('ficus-benjamina', 'ficus', null),
    ('ficus-binnendijkii', 'ficus', null),
    ('ficus-cyathistipula', 'ficus', null),
    ('ficus-elastica', 'ficus', null),
    ('ficus-lyrata', 'ficus', '{"ru": "Для крупных экземпляров добавьте 10% коры: лировидный фикус особенно чувствителен к закисанию."}'),
    ('ficus-microcarpa', 'bonsai', '{"ru": "Если растёт как обычное деревце, а не бонсай, — подойдёт смесь для фикусов."}'),
    ('ficus-pumila', 'universal', null),
    ('ficus-triangularis', 'ficus', null),
    ('fittonia-albivenis', 'tropical_moist', null),
    ('fuchsia-hybrida', 'flowering', null),
    ('gardenia-jasminoides', 'acidic', null),
    ('gasteria-bicolor', 'cactus_succulent', null),
    ('gerbera-jamesonii', 'flowering', '{"ru": "Розетку не заглубляйте: у гербер корневая шейка легко загнивает."}'),
    ('goeppertia-lancifolia', 'tropical_moist', null),
    ('goeppertia-lietzei', 'tropical_moist', null),
    ('goeppertia-makoyana', 'tropical_moist', null),
    ('goeppertia-orbifolia', 'tropical_moist', null),
    ('goeppertia-roseopicta', 'tropical_moist', null),
    ('goeppertia-rufibarba', 'tropical_moist', null),
    ('graptopetalum-paraguayense', 'cactus_succulent', null),
    ('guzmania-lingulata', 'bromeliad_epiphyte', null),
    ('gymnocalycium-baldianum', 'cactus_succulent', null),
    ('gymnocalycium-mihanovichii', 'cactus_succulent', '{"ru": "Привитый гимнокалициум: следите, чтобы место прививки было над гравием."}'),
    ('gynura-aurantiaca', 'universal', null),
    ('haworthia-cooperi', 'cactus_succulent', null),
    ('haworthiopsis-attenuata', 'cactus_succulent', null),
    ('hedera-helix', 'universal', null),
    ('hibiscus-rosa-sinensis', 'citrus_mediterranean', null),
    ('hippeastrum-hybridum', 'bulbous', null),
    ('homalomena-rubescens', 'aroid_chunky', null),
    ('howea-forsteriana', 'palm_tree', null),
    ('hoya-carnosa', 'epiphytic_vine', null),
    ('hydrangea-macrophylla', 'acidic', '{"ru": "Кислый грунт даёт голубые соцветия, нейтральный — розовые."}'),
    ('hypoestes-phyllostachya', 'universal', null),
    ('impatiens-walleriana', 'flowering', null),
    ('iresine-herbstii', 'flowering', null),
    ('jasminum-polyanthum', 'universal', null),
    ('justicia-carnea', 'universal', null),
    ('kalanchoe-blossfeldiana', 'cactus_succulent', '{"ru": "Цветущему каланхоэ — плюс 10% листовой земли для питания."}'),
    ('kalanchoe-daigremontiana', 'cactus_succulent', null),
    ('kalanchoe-thyrsiflora', 'cactus_succulent', null),
    ('kalanchoe-tomentosa', 'cactus_succulent', null),
    ('kroenleinia-grusonii', 'cactus_succulent', null),
    ('lantana-camara', 'flowering', null),
    ('laurus-nobilis', 'citrus_mediterranean', null),
    ('lithops-lesliei', 'mesembs_mineral', null),
    ('livistona-chinensis', 'palm_tree', null),
    ('ludisia-discolor', 'orchid_terrestrial', null),
    ('mammillaria-elongata', 'cactus_succulent', null),
    ('mandevilla-sanderi', 'flowering', null),
    ('maranta-leuconeura', 'tropical_moist', null),
    ('marsdenia-floribunda', 'universal', null),
    ('medinilla-magnifica', 'epiphytic_vine', '{"ru": "Мединилле — плюс 10% сфагнума: она любит влажный воздух и ровно влажный субстрат."}'),
    ('melocactus-matanzanus', 'cactus_succulent', null),
    ('microsorum-musifolium', 'fern', null),
    ('miltoniopsis-hybrida', 'orchid_bark', '{"ru": "Мильтонии — мелкая кора с 25% сфагнума: она не выносит полного пересыхания."}'),
    ('monstera-adansonii', 'aroid_chunky', null),
    ('monstera-deliciosa', 'aroid_chunky', '{"ru": "Для крупных экземпляров добавьте 10% крупной коры и тяжёлый горшок под опору."}'),
    ('monstera-siltepecana', 'aroid_chunky', null),
    ('muehlenbeckia-complexa', 'universal', null),
    ('murraya-paniculata', 'acidic', null),
    ('musa-acuminata', 'universal', '{"ru": "Банан прожорлив: добавьте 15% биогумуса и берите объёмный горшок."}'),
    ('myrsine-africana', 'citrus_mediterranean', null),
    ('myrtus-communis', 'citrus_mediterranean', '{"ru": "Мирт боится пересушки кома — песка меньше, торфа чуть больше."}'),
    ('nematanthus-gregarius', 'gesneriad', null),
    ('neoregelia-carolinae', 'bromeliad_epiphyte', null),
    ('nepenthes-ventrata', 'carnivorous', '{"ru": "Непентесу нужна смесь рыхлее: половина сфагнума, 20% коры, подвесное кашпо без поддона с водой."}'),
    ('nephrolepis-exaltata', 'fern', null),
    ('nerium-oleander', 'citrus_mediterranean', null),
    ('ocimum-basilicum', 'flowering', null),
    ('olea-europaea', 'citrus_mediterranean', '{"ru": "Оливе — ещё 10% гравия или пемзы и грунт ближе к нейтральному."}'),
    ('oncidium-hybridum', 'orchid_bark', null),
    ('opuntia-microdasys', 'cactus_succulent', null),
    ('oxalis-triangularis', 'bulbous', null),
    ('pachira-aquatica', 'palm_tree', '{"ru": "Ствол пахиры гниёт при застое: добавьте 10% песка или пемзы."}'),
    ('pachyphytum-oviferum', 'cactus_succulent', null),
    ('pachypodium-lamerei', 'caudex', null),
    ('pachystachys-lutea', 'universal', null),
    ('paphiopedilum-hybridum', 'orchid_terrestrial', null),
    ('passiflora-caerulea', 'universal', null),
    ('pelargonium-hortorum', 'flowering', '{"ru": "Пеларгонии — без биогумуса и с 10% песка, иначе она «жирует» вместо цветения."}'),
    ('pentas-lanceolata', 'flowering', null),
    ('peperomia-argyreia', 'epiphytic_vine', null),
    ('peperomia-caperata', 'epiphytic_vine', null),
    ('peperomia-obtusifolia', 'epiphytic_vine', null),
    ('peperomia-prostrata', 'epiphytic_vine', null),
    ('phalaenopsis-hybrid', 'orchid_bark', null),
    ('philodendron-erubescens', 'aroid_chunky', null),
    ('philodendron-hederaceum', 'aroid_chunky', null),
    ('philodendron-melinonii', 'aroid_chunky', null),
    ('philodendron-pedatum', 'aroid_chunky', null),
    ('phlebodium-aureum', 'fern', '{"ru": "Корневища стелются по поверхности — добавьте 15% коры и не засыпайте их."}'),
    ('phoenix-roebelenii', 'palm_tree', null),
    ('pilea-cadierei', 'universal', null),
    ('pilea-peperomioides', 'universal', null),
    ('platycerium-bifurcatum', 'bromeliad_epiphyte', '{"ru": "Лучше всего растёт на блоке: доска с корой и подушкой сфагнума под щитовидными листьями."}'),
    ('pleiospilos-nelii', 'mesembs_mineral', null),
    ('plerandra-elegantissima', 'universal', null),
    ('pogonatherum-paniceum', 'tropical_moist', '{"ru": "Бамбуковая трава не выносит пересыхания — можно ставить в поддон с водой."}'),
    ('polyscias-fruticosa', 'universal', null),
    ('polyscias-scutellaria', 'universal', null),
    ('portulacaria-afra', 'cactus_succulent', '{"ru": "Для формирования как бонсай подойдёт и смесь для бонсай с 20% пемзы."}'),
    ('primula-vulgaris', 'flowering', null),
    ('radermachera-sinica', 'universal', null),
    ('rhaphidophora-tetrasperma', 'aroid_chunky', null),
    ('rhapis-excelsa', 'palm_tree', null),
    ('rhipsalis-baccifera', 'bromeliad_epiphyte', null),
    ('rhododendron-simsii', 'acidic', null),
    ('rosa-chinensis', 'flowering', '{"ru": "Розе — плюс 15% дерновой земли: ей нужен более плотный и питательный грунт."}'),
    ('salvia-rosmarinus', 'citrus_mediterranean', '{"ru": "Розмарину — больше песка (до 25%): он не выносит сырости у корней."}'),
    ('sarracenia-purpurea', 'carnivorous', null),
    ('saxifraga-stolonifera', 'universal', null),
    ('schefflera-arboricola', 'palm_tree', null),
    ('schlumbergera-truncata', 'bromeliad_epiphyte', null),
    ('scindapsus-pictus', 'aroid_chunky', null),
    ('sedum-morganianum', 'cactus_succulent', null),
    ('selaginella-martensii', 'tropical_moist', '{"ru": "Селагинелла идеальна для флорариума: слой керамзита, сверху эта смесь без перлита."}'),
    ('sempervivum-tectorum', 'cactus_succulent', null),
    ('sinningia-speciosa', 'gesneriad', '{"ru": "Клубень глоксинии заглубляйте на 2/3, макушка с почками остаётся над грунтом."}'),
    ('solanum-pseudocapsicum', 'flowering', null),
    ('soleirolia-soleirolii', 'tropical_moist', null),
    ('spathiphyllum-wallisii', 'aroid_moist', null),
    ('stapelia-grandiflora', 'cactus_succulent', null),
    ('strelitzia-reginae', 'palm_tree', '{"ru": "Мясистые хрупкие корни: глубокий горшок и пересадка перевалкой без разрыва кома."}'),
    ('streptocarpus-hybridus', 'gesneriad', null),
    ('streptocarpus-ionanthus', 'gesneriad', null),
    ('stromanthe-thalia', 'tropical_moist', null),
    ('syngonium-podophyllum', 'aroid_chunky', null),
    ('thaumatophyllum-bipinnatifidum', 'aroid_chunky', '{"ru": "Для крупных экземпляров добавьте 10% крупной коры и выбирайте тяжёлый широкий горшок."}'),
    ('tillandsia-cyanea', 'bromeliad_epiphyte', null),
    ('tillandsia-ionantha', 'air_epiphyte', null),
    ('tradescantia-fluminensis', 'universal', null),
    ('tradescantia-pallida', 'universal', null),
    ('tradescantia-zebrina', 'universal', null),
    ('vanda-hybrida', 'air_epiphyte', null),
    ('vriesea-splendens', 'bromeliad_epiphyte', null),
    ('washingtonia-robusta', 'palm_tree', null),
    ('xerosicyos-danguyi', 'caudex', null),
    ('yucca-gigantea', 'palm_tree', '{"ru": "Юкке — ещё 10% песка или пемзы: она засухоустойчива и боится перелива."}'),
    ('zamia-furfuracea', 'caudex', null),
    ('zamioculcas-zamiifolia', 'caudex', '{"ru": "Замиокулькасу — 10% листовой земли и тяжёлый горшок: клубни распирают пластик."}')
  ) v(slug, mix, note)
  join public.species s on s.slug = v.slug
 where c.species_id = s.id;
