-- Расширение базы знаний, часть 4: ассортимент магазина Unifleur, которого не было в базе:
-- фикусы, филодендроны, калатеи, алоказии, папоротники, суккуленты.
-- Латинские названия — актуальные (POWO); прежние названия в synonyms, чтобы распознавание
-- (Pl@ntNet, модель на телефоне) и поиск находили вид и по ним. Токсичность для животных — по ASPCA.
-- Миграция идемпотентна: повторный запуск и уже существующие записи ничего не дублируют.

insert into public.families (latin_name, name_ru) values
  ('Acanthaceae', 'Акантовые'),
  ('Aizoaceae', 'Аизовые'),
  ('Anacampserotaceae', 'Анакампсеросовые'),
  ('Apocynaceae', 'Кутровые'),
  ('Araceae', 'Ароидные'),
  ('Araliaceae', 'Аралиевые'),
  ('Asparagaceae', 'Спаржевые'),
  ('Asteraceae', 'Астровые'),
  ('Blechnaceae', 'Дербянковые'),
  ('Bromeliaceae', 'Бромелиевые'),
  ('Cactaceae', 'Кактусовые'),
  ('Crassulaceae', 'Толстянковые'),
  ('Cucurbitaceae', 'Тыквенные'),
  ('Cupressaceae', 'Кипарисовые'),
  ('Davalliaceae', 'Даваллиевые'),
  ('Euphorbiaceae', 'Молочайные'),
  ('Garryaceae', 'Гарриевые'),
  ('Marantaceae', 'Марантовые'),
  ('Moraceae', 'Тутовые'),
  ('Poaceae', 'Злаки'),
  ('Polygonaceae', 'Гречишные'),
  ('Polypodiaceae', 'Многоножковые'),
  ('Saxifragaceae', 'Камнеломковые')
on conflict (latin_name) do nothing;

insert into public.genera (family_id, latin_name, name_ru)
select f.id, g.latin_name, g.name_ru
from (values
  ('Euphorbiaceae', 'Acalypha', 'Акалифа'),
  ('Araceae', 'Alocasia', 'Алоказия'),
  ('Anacampserotaceae', 'Anacampseros', 'Анакампсерос'),
  ('Araceae', 'Anthurium', 'Антуриум'),
  ('Garryaceae', 'Aucuba', 'Аукуба'),
  ('Blechnaceae', 'Blechnum', 'Блехнум'),
  ('Asparagaceae', 'Chlorophytum', 'Хлорофитум'),
  ('Crassulaceae', 'Crassula', 'Толстянка'),
  ('Acanthaceae', 'Crossandra', 'Кроссандра'),
  ('Bromeliaceae', 'Cryptanthus', 'Криптантус'),
  ('Cupressaceae', 'Cupressus', 'Кипарис'),
  ('Davalliaceae', 'Davallia', 'Даваллия'),
  ('Asparagaceae', 'Dracaena', 'Драцена'),
  ('Euphorbiaceae', 'Euphorbia', 'Молочай'),
  ('Moraceae', 'Ficus', 'Фикус'),
  ('Asteraceae', 'Gerbera', 'Гербера'),
  ('Marantaceae', 'Goeppertia', 'Гёпперция'),
  ('Cactaceae', 'Gymnocalycium', 'Гимнокалициум'),
  ('Crassulaceae', 'Kalanchoe', 'Каланхоэ'),
  ('Cactaceae', 'Melocactus', 'Мелокактус'),
  ('Polypodiaceae', 'Microsorum', 'Микросорум'),
  ('Araceae', 'Monstera', 'Монстера'),
  ('Polygonaceae', 'Muehlenbeckia', 'Мюленбекия'),
  ('Araceae', 'Philodendron', 'Филодендрон'),
  ('Aizoaceae', 'Pleiospilos', 'Плейоспилос'),
  ('Poaceae', 'Pogonatherum', 'Погонатерум'),
  ('Araliaceae', 'Polyscias', 'Полисциас'),
  ('Saxifragaceae', 'Saxifraga', 'Камнеломка'),
  ('Apocynaceae', 'Stapelia', 'Стапелия'),
  ('Bromeliaceae', 'Tillandsia', 'Тилландсия'),
  ('Cucurbitaceae', 'Xerosicyos', 'Ксеросициос')
) as g(family, latin_name, name_ru)
join public.families f on f.latin_name = g.family
on conflict (latin_name) do nothing;

insert into public.species
  (genus_id, slug, latin_name, common_names, synonyms, description, plant_type,
   difficulty, toxic_to_pets, toxic_to_humans, air_purifying)
select g.id, s.slug, s.latin_name, s.common_names::jsonb, s.synonyms, s.description::jsonb,
       s.plant_type, s.difficulty, s.toxic_pets, s.toxic_humans, s.air_purifying
from (values
  ('Ficus', 'ficus-altissima', 'Ficus altissima',
   '{"ru": ["Фикус высочайший", "Фикус Альтиссима"], "en": ["Council tree", "Lofty fig"]}', '{}'::text[],
   '{"ru": "Фикус с крупными кожистыми листьями, у сортов — с жёлто-зелёной каймой."}', 'дерево', 2, true, false, true),
  ('Ficus', 'ficus-binnendijkii', 'Ficus binnendijkii',
   '{"ru": ["Фикус Биннендийка", "Фикус «Али»"], "en": ["Ficus Alii", "Narrow-leaf fig"]}', '{"Ficus maclellandii"}'::text[],
   '{"ru": "Фикус с длинными узкими поникающими листьями; меньше капризничает, чем Бенджамина."}', 'дерево', 2, true, false, true),
  ('Ficus', 'ficus-cyathistipula', 'Ficus cyathistipula',
   '{"ru": ["Фикус циатистипула"], "en": ["African fig"]}', '{}'::text[],
   '{"ru": "Фикус с глянцевыми листьями, расширенными к концу; бывает с плодами-шариками."}', 'дерево', 2, true, false, true),
  ('Ficus', 'ficus-triangularis', 'Ficus triangularis',
   '{"ru": ["Фикус треугольный"], "en": ["Triangle fig"]}', '{"Ficus natalensis subsp. leprieurii"}'::text[],
   '{"ru": "Кустистый фикус с листьями-треугольниками; есть пёстрый сорт."}', 'дерево', 2, true, false, true),
  ('Philodendron', 'philodendron-pedatum', 'Philodendron pedatum',
   '{"ru": ["Филодендрон педатум"], "en": ["Oak-leaf philodendron"]}', '{"Philodendron laciniatum"}'::text[],
   '{"ru": "Лиана с глубоко рассечёнными листьями необычной формы."}', 'лиана', 2, true, true, true),
  ('Philodendron', 'philodendron-melinonii', 'Philodendron melinonii',
   '{"ru": ["Филодендрон Мелинона"], "en": ["Melinon''s philodendron"]}', '{}'::text[],
   '{"ru": "Розетка крупных треугольных листьев на коротком стволе, не лазает."}', 'травянистое', 2, true, true, true),
  ('Goeppertia', 'goeppertia-rufibarba', 'Goeppertia rufibarba',
   '{"ru": ["Калатея рыжебородая", "Калатея «Голубой гром»"], "en": ["Velvet calathea", "Furry feather"]}', '{"Calathea rufibarba"}'::text[],
   '{"ru": "Узкие волнистые листья с бархатистой бордовой изнанкой."}', 'травянистое', 3, false, false, false),
  ('Goeppertia', 'goeppertia-lietzei', 'Goeppertia lietzei',
   '{"ru": ["Калатея Литце"], "en": ["Calathea lietzei", "White fusion"]}', '{"Calathea lietzei"}'::text[],
   '{"ru": "Листья с пёстрыми белыми мазками и фиолетовой изнанкой; популярен сорт «White Fusion»."}', 'травянистое', 4, false, false, false),
  ('Crassula', 'crassula-muscosa', 'Crassula muscosa',
   '{"ru": ["Толстянка плауновидная"], "en": ["Watch chain", "Princess pine"]}', '{"Crassula lycopodioides"}'::text[],
   '{"ru": "Суккулент с тонкими «цепочками» из чешуйчатых листьев."}', 'суккулент', 1, true, false, false),
  ('Kalanchoe', 'kalanchoe-thyrsiflora', 'Kalanchoe thyrsiflora',
   '{"ru": ["Каланхоэ метельчатоцветковое", "Каланхоэ «Лопасти»"], "en": ["Paddle plant", "Flapjack"]}', '{}'::text[],
   '{"ru": "Розетка округлых сизых листьев-«лопастей», краснеющих на солнце."}', 'суккулент', 1, true, false, false),
  ('Monstera', 'monstera-siltepecana', 'Monstera siltepecana',
   '{"ru": ["Монстера силтепекана"], "en": ["Silver monstera"]}', '{}'::text[],
   '{"ru": "Лиана с серебристыми листьями; у взрослых листья становятся зелёными с дырочками."}', 'лиана', 2, true, true, true),
  ('Anthurium', 'anthurium-hookeri', 'Anthurium hookeri',
   '{"ru": ["Антуриум Хукера"], "en": ["Bird''s nest anthurium"]}', '{}'::text[],
   '{"ru": "Розетка широких листьев, как у асплениума, — растение-«гнездо»."}', 'эпифит', 3, true, true, false),
  ('Alocasia', 'alocasia-reginula', 'Alocasia reginula',
   '{"ru": ["Алоказия «Чёрный бархат»"], "en": ["Black velvet alocasia"]}', '{}'::text[],
   '{"ru": "Небольшая алоказия с тёмными бархатными листьями и серебряными жилками."}', 'травянистое', 4, true, true, false),
  ('Alocasia', 'alocasia-baginda', 'Alocasia baginda',
   '{"ru": ["Алоказия багинда", "Алоказия «Драконья чешуя»"], "en": ["Dragon scale alocasia"]}', '{}'::text[],
   '{"ru": "Толстые листья с рельефом, похожим на чешую дракона."}', 'травянистое', 4, true, true, false),
  ('Alocasia', 'alocasia-micholitziana', 'Alocasia micholitziana',
   '{"ru": ["Алоказия Мичолица", "Алоказия «Фридек»"], "en": ["Green velvet alocasia", "Frydek"]}', '{}'::text[],
   '{"ru": "Бархатные тёмно-зелёные листья-стрелы с белыми жилками."}', 'травянистое', 4, true, true, false),
  ('Alocasia', 'alocasia-cuprea', 'Alocasia cuprea',
   '{"ru": ["Алоказия медно-красная"], "en": ["Mirror plant", "Red secret"]}', '{}'::text[],
   '{"ru": "Листья с металлическим медным блеском и выпуклыми жилками."}', 'травянистое', 4, true, true, false),
  ('Dracaena', 'dracaena-reflexa', 'Dracaena reflexa',
   '{"ru": ["Драцена отогнутая", "«Песнь Индии»"], "en": ["Song of India", "Pleomele"]}', '{"Pleomele reflexa"}'::text[],
   '{"ru": "Ветвистая драцена с короткими отогнутыми листьями; сорта с жёлтой каймой."}', 'дерево', 2, true, false, true),
  ('Euphorbia', 'euphorbia-meloformis', 'Euphorbia meloformis',
   '{"ru": ["Молочай дынеобразный"], "en": ["Melon spurge"]}', '{}'::text[],
   '{"ru": "Круглый ребристый суккулент, похожий на маленькую дыню."}', 'суккулент', 1, true, true, false),
  ('Polyscias', 'polyscias-scutellaria', 'Polyscias scutellaria',
   '{"ru": ["Полисциас щитовидный", "Полисциас «Фабиан»"], "en": ["Shield aralia", "Dinner plate aralia"]}', '{}'::text[],
   '{"ru": "Округлые кожистые листья-«тарелочки» на толстом стволе."}', 'дерево', 3, true, false, false),
  ('Chlorophytum', 'chlorophytum-orchidastrum', 'Chlorophytum orchidastrum',
   '{"ru": ["Хлорофитум оранжевый", "Хлорофитум «Огненная вспышка»"], "en": ["Fire flash", "Mandarin plant"]}', '{"Chlorophytum amaniense"}'::text[],
   '{"ru": "Широкие листья на ярко-оранжевых черешках."}', 'травянистое', 2, false, false, true),
  ('Tillandsia', 'tillandsia-cyanea', 'Tillandsia cyanea',
   '{"ru": ["Тилландсия синяя"], "en": ["Pink quill"]}', '{"Wallisia cyanea"}'::text[],
   '{"ru": "Бромелия с розовым плоским «пером» и фиолетовыми цветками; растёт в горшке."}', 'эпифит', 2, false, false, true),
  ('Gymnocalycium', 'gymnocalycium-baldianum', 'Gymnocalycium baldianum',
   '{"ru": ["Гимнокалициум Бальда"], "en": ["Dwarf chin cactus"]}', '{}'::text[],
   '{"ru": "Небольшой кактус с тёмно-красными цветками весной."}', 'суккулент', 1, false, false, false),
  ('Acalypha', 'acalypha-hispida', 'Acalypha hispida',
   '{"ru": ["Акалифа щетинистоволосистая", "Лисий хвост"], "en": ["Chenille plant", "Red-hot cat''s tail"]}', '{}'::text[],
   '{"ru": "Кустарник с длинными пушистыми красными соцветиями-«хвостами»."}', 'кустарник', 3, true, false, false),
  ('Anacampseros', 'anacampseros-rufescens', 'Anacampseros rufescens',
   '{"ru": ["Анакампсерос рыжеющий"], "en": ["Sand rose"]}', '{}'::text[],
   '{"ru": "Мелкий суккулент с розовыми листочками в белых волосках."}', 'суккулент', 2, false, false, false),
  ('Aucuba', 'aucuba-japonica', 'Aucuba japonica',
   '{"ru": ["Аукуба японская", "Золотое дерево"], "en": ["Japanese laurel", "Gold dust plant"]}', '{}'::text[],
   '{"ru": "Кустарник с глянцевыми листьями в золотистых крапинках; любит прохладу."}', 'кустарник', 1, true, false, true),
  ('Blechnum', 'blechnum-gibbum', 'Blechnum gibbum',
   '{"ru": ["Блехнум горбатый"], "en": ["Miniature tree fern", "Silver lady"]}', '{"Lomaria gibba","Oceaniopteris gibba"}'::text[],
   '{"ru": "Папоротник с розеткой перистых вай на коротком стволике."}', 'папоротник', 3, false, false, true),
  ('Davallia', 'davallia-fejeensis', 'Davallia fejeensis',
   '{"ru": ["Даваллия фиджийская", "Заячья лапка"], "en": ["Rabbit''s foot fern"]}', '{"Davallia solida var. fejeensis"}'::text[],
   '{"ru": "Кружевной папоротник с мохнатыми корневищами, свисающими через край горшка."}', 'папоротник', 2, false, false, true),
  ('Crossandra', 'crossandra-infundibuliformis', 'Crossandra infundibuliformis',
   '{"ru": ["Кроссандра воронковидная"], "en": ["Firecracker flower"]}', '{}'::text[],
   '{"ru": "Кустик с глянцевыми листьями и оранжево-лососевыми цветками."}', 'кустарник', 3, null, false, false),
  ('Cryptanthus', 'cryptanthus-bivittatus', 'Cryptanthus bivittatus',
   '{"ru": ["Криптантус двухполосый", "Земляная звёздочка"], "en": ["Earth star"]}', '{}'::text[],
   '{"ru": "Плоская звёздчатая розетка полосатых листьев; растёт в грунте."}', 'травянистое', 2, false, false, false),
  ('Xerosicyos', 'xerosicyos-danguyi', 'Xerosicyos danguyi',
   '{"ru": ["Ксеросициос Дэнги", "Денежная лиана"], "en": ["Silver dollar vine"]}', '{}'::text[],
   '{"ru": "Суккулентная лиана с круглыми мясистыми листьями-«монетками»."}', 'суккулент', 2, null, false, false),
  ('Saxifraga', 'saxifraga-stolonifera', 'Saxifraga stolonifera',
   '{"ru": ["Камнеломка побегоносная"], "en": ["Strawberry begonia", "Creeping saxifrage"]}', '{"Saxifraga sarmentosa"}'::text[],
   '{"ru": "Округлые листья с серебристыми жилками и дочерние розетки на усах."}', 'травянистое', 1, false, false, false),
  ('Melocactus', 'melocactus-matanzanus', 'Melocactus matanzanus',
   '{"ru": ["Мелокактус матансанский"], "en": ["Dwarf Turk''s cap cactus"]}', '{}'::text[],
   '{"ru": "Маленький шаровидный кактус с красной «шапочкой»-цефалием."}', 'суккулент', 3, false, false, false),
  ('Microsorum', 'microsorum-musifolium', 'Microsorum musifolium',
   '{"ru": ["Микросорум банановолистный", "Крокодиловый папоротник"], "en": ["Crocodile fern"]}', '{}'::text[],
   '{"ru": "Папоротник с цельными листьями в рисунке «кожи крокодила»."}', 'папоротник', 3, false, false, true),
  ('Muehlenbeckia', 'muehlenbeckia-complexa', 'Muehlenbeckia complexa',
   '{"ru": ["Мюленбекия спутанная"], "en": ["Wire vine", "Maidenhair vine"]}', '{}'::text[],
   '{"ru": "Тонкие проволочные стебли с мелкими округлыми листочками; красиво в ампеле."}', 'лиана', 2, null, false, false),
  ('Cupressus', 'cupressus-macrocarpa', 'Cupressus macrocarpa',
   '{"ru": ["Кипарис крупноплодный", "Кипарис «Голдкрест»"], "en": ["Monterey cypress", "Goldcrest"]}', '{"Hesperocyparis macrocarpa"}'::text[],
   '{"ru": "Хвойное деревце с золотистой ароматной хвоей; продаётся к Новому году."}', 'дерево', 4, null, false, true),
  ('Gerbera', 'gerbera-jamesonii', 'Gerbera jamesonii',
   '{"ru": ["Гербера Джеймсона", "Гербера"], "en": ["Barberton daisy", "Gerbera"]}', '{}'::text[],
   '{"ru": "Крупные ромашки ярких цветов; горшечные сорта компактные."}', 'травянистое', 3, false, false, false),
  ('Pleiospilos', 'pleiospilos-nelii', 'Pleiospilos nelii',
   '{"ru": ["Плейоспилос Нела", "Расщеплённый камень"], "en": ["Split rock"]}', '{}'::text[],
   '{"ru": "Пара толстых листьев, похожих на расколотый камень."}', 'суккулент', 4, false, false, false),
  ('Pogonatherum', 'pogonatherum-paniceum', 'Pogonatherum paniceum',
   '{"ru": ["Погонатерум метельчатый", "Комнатный бамбук"], "en": ["Baby panda bamboo", "House bamboo"]}', '{}'::text[],
   '{"ru": "Злак, похожий на миниатюрный бамбук; образует пышную кочку."}', 'травянистое', 2, false, false, false),
  ('Stapelia', 'stapelia-grandiflora', 'Stapelia grandiflora',
   '{"ru": ["Стапелия крупноцветковая"], "en": ["Carrion flower", "Starfish flower"]}', '{}'::text[],
   '{"ru": "Суккулент с мохнатыми цветками-звёздами; цветки пахнут неприятно."}', 'суккулент', 1, null, false, false)
) as s(genus, slug, latin_name, common_names, synonyms, description, plant_type,
       difficulty, toxic_pets, toxic_humans, air_purifying)
join public.genera g on g.latin_name = s.genus
on conflict do nothing;

insert into public.care_profiles
  (species_id, light, water_interval_summer, water_interval_winter, soil_dryness_before_watering,
   humidity_min_pct, temp_min_c, temp_max_c, fertilize_interval_days, fertilize_months,
   repot_every_years, propagation, tips)
select sp.id, c.light, c.summer, c.winter, c.dryness::jsonb, c.humidity, c.tmin, c.tmax,
       c.fert_days, c.fert_months, c.repot, c.propagation, c.tips::jsonb
from (values
  ('ficus-altissima', 'bright_indirect', 7, 14, '{"ru": "верхние 3 см"}', 40, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","воздушные отводки"}'::text[],
   '{"ru": ["Не переставляйте — сбрасывает листья"]}'),
  ('ficus-binnendijkii', 'bright_indirect', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Спокойнее переносит перестановку, чем другие фикусы"]}'),
  ('ficus-cyathistipula', 'bright_indirect', 7, 12, '{"ru": "верхние 2–3 см"}', 40, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Любит стабильное место без сквозняков"]}'),
  ('ficus-triangularis', 'bright_indirect', 6, 12, '{"ru": "верхние 2 см"}', 40, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Пёстрому сорту нужно больше света"]}'),
  ('philodendron-pedatum', 'bright_indirect', 7, 12, '{"ru": "верхние 3 см"}', 50, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Нужна опора из мха или кокоса"]}'),
  ('philodendron-melinonii', 'bright_indirect', 7, 12, '{"ru": "верхние 3 см"}', 50, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление","семена"}'::text[],
   '{"ru": ["Занимает много места вширь"]}'),
  ('goeppertia-rufibarba', 'medium', 4, 7, '{"ru": "верхний слой"}', 55, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Не опрыскивайте бархатные листья — повышайте влажность иначе"]}'),
  ('goeppertia-lietzei', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Пёстрые листья легко обжечь солнцем"]}'),
  ('crassula-muscosa', 'bright_indirect', 10, 25, '{"ru": "полностью"}', 20, 8, 28, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Лучше растёт в неглубокой плошке"]}'),
  ('kalanchoe-thyrsiflora', 'direct', 12, 25, '{"ru": "полностью"}', 20, 10, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки","черенки"}'::text[],
   '{"ru": ["После цветения розетка отмирает — оставляйте деток"]}'),
  ('monstera-siltepecana', 'bright_indirect', 6, 10, '{"ru": "верхние 2–3 см"}', 55, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Хорошо растёт в подвесном кашпо или на опоре"]}'),
  ('anthurium-hookeri', 'bright_indirect', 6, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление","семена"}'::text[],
   '{"ru": ["Грунт с корой, как для орхидей"]}'),
  ('alocasia-reginula', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"клубеньки"}'::text[],
   '{"ru": ["Очень рыхлый грунт и осторожный полив"]}'),
  ('alocasia-baginda', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"клубеньки","деление"}'::text[],
   '{"ru": ["Не переливайте — корни гниют"]}'),
  ('alocasia-micholitziana', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"клубеньки","деление"}'::text[],
   '{"ru": ["Зимой может отдыхать — полив сократите"]}'),
  ('alocasia-cuprea', 'medium', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"клубеньки"}'::text[],
   '{"ru": ["Прямое солнце выжигает блестящие листья"]}'),
  ('dracaena-reflexa', 'bright_indirect', 7, 14, '{"ru": "верхние 3 см"}', 40, 16, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"черенки"}'::text[],
   '{"ru": ["Пёстрые сорта ярче при хорошем свете"]}'),
  ('euphorbia-meloformis', 'direct', 14, 30, '{"ru": "полностью"}', 20, 10, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена","детки"}'::text[],
   '{"ru": ["Сок едкий"]}'),
  ('polyscias-scutellaria', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Не любит холода и сквозняков"]}'),
  ('chlorophytum-orchidastrum', 'medium', 5, 8, '{"ru": "верхние 2 см"}', 50, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление","семена"}'::text[],
   '{"ru": ["Удаляйте цветоносы, чтобы черешки оставались яркими"]}'),
  ('tillandsia-cyanea', 'bright_indirect', 7, 12, '{"ru": "верхний слой"}', 55, 18, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки"}'::text[],
   '{"ru": ["Опрыскивайте, но не заливайте грунт"]}'),
  ('gymnocalycium-baldianum', 'direct', 14, 40, '{"ru": "полностью"}', 20, 5, 32, 30,
   '{5,6,7,8}'::smallint[], 2, '{"семена","детки"}'::text[],
   '{"ru": ["Прохладная сухая зимовка для цветения"]}'),
  ('acalypha-hispida', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 16, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Сок раздражает кожу", "Любит влажный воздух"]}'),
  ('anacampseros-rufescens', 'direct', 10, 25, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Нужно солнце для яркой окраски"]}'),
  ('aucuba-japonica', 'medium', 5, 10, '{"ru": "верхние 2 см"}', 40, 5, 22, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Зимой прохлада +5–10 °C", "Выносит тень"]}'),
  ('blechnum-gibbum', 'medium', 4, 7, '{"ru": "не пересыхает"}', 60, 16, 26, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"споры"}'::text[],
   '{"ru": ["Не лейте в центр розетки"]}'),
  ('davallia-fejeensis', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 50, 15, 26, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"корневища","деление"}'::text[],
   '{"ru": ["Корневища не засыпайте землёй"]}'),
  ('crossandra-infundibuliformis', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"черенки","семена"}'::text[],
   '{"ru": ["Сухой воздух — причина опадания бутонов"]}'),
  ('cryptanthus-bivittatus', 'bright_indirect', 5, 10, '{"ru": "верхний слой"}', 60, 18, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки"}'::text[],
   '{"ru": ["Хорош для флорариумов"]}'),
  ('xerosicyos-danguyi', 'bright_indirect', 10, 21, '{"ru": "полностью"}', 30, 12, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Нужна опора — цепляется усиками"]}'),
  ('saxifraga-stolonifera', 'medium', 4, 7, '{"ru": "верхний слой"}', 50, 5, 24, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки на усах"}'::text[],
   '{"ru": ["Любит прохладу, зимой +10–15 °C"]}'),
  ('melocactus-matanzanus', 'direct', 10, 30, '{"ru": "полностью"}', 30, 15, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Не любит холода ниже +15 °C"]}'),
  ('microsorum-musifolium', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление"}'::text[],
   '{"ru": ["Нужна высокая влажность"]}'),
  ('muehlenbeckia-complexa', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 40, 8, 24, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Пересыхание — листопад", "Зимой прохлада"]}'),
  ('cupressus-macrocarpa', 'direct', 3, 7, '{"ru": "не пересыхает"}', 50, 5, 20, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Зимой только прохлада +5–10 °C — в тепле сохнет", "Не допускайте пересыхания"]}'),
  ('gerbera-jamesonii', 'direct', 3, 7, '{"ru": "верхний слой"}', 50, 12, 26, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"деление","семена"}'::text[],
   '{"ru": ["Поливайте по краю горшка — розетка легко загнивает"]}'),
  ('pleiospilos-nelii', 'direct', 14, 60, '{"ru": "полностью"}', 20, 8, 32, null,
   '{}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Когда растут новые листья, не поливайте — старые их питают"]}'),
  ('pogonatherum-paniceum', 'bright_indirect', 2, 4, '{"ru": "не пересыхает"}', 50, 16, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Корни не должны пересыхать — стойте в поддоне с водой"]}'),
  ('stapelia-grandiflora', 'direct', 10, 30, '{"ru": "полностью"}', 30, 10, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Цветки привлекают мух — летом лучше на балконе"]}')
) as c(slug, light, summer, winter, dryness, humidity, tmin, tmax, fert_days, fert_months,
       repot, propagation, tips)
join public.species sp on sp.slug = c.slug
on conflict (species_id) do nothing;
