-- Расширение базы знаний, часть 2: ещё 66 растений — калатеи, суккуленты и кактусы, папоротники,
-- пальмы, бромелии, хищные растения, цветущие и пряные травы для подоконника.
-- Латинские названия — актуальные (POWO); прежние названия в synonyms, чтобы распознавание
-- (Pl@ntNet, модель на телефоне) и поиск находили вид и по ним. Токсичность для животных — по ASPCA.
-- Миграция идемпотентна: повторный запуск и уже существующие записи ничего не дублируют.

insert into public.families (latin_name, name_ru) values
  ('Acanthaceae', 'Акантовые'),
  ('Aizoaceae', 'Аизовые'),
  ('Amaryllidaceae', 'Амариллисовые'),
  ('Araceae', 'Ароидные'),
  ('Araliaceae', 'Аралиевые'),
  ('Arecaceae', 'Пальмы'),
  ('Asphodelaceae', 'Асфоделовые'),
  ('Asteraceae', 'Астровые'),
  ('Bignoniaceae', 'Бигнониевые'),
  ('Bromeliaceae', 'Бромелиевые'),
  ('Cactaceae', 'Кактусовые'),
  ('Commelinaceae', 'Коммелиновые'),
  ('Crassulaceae', 'Толстянковые'),
  ('Cycadaceae', 'Саговниковые'),
  ('Didiereaceae', 'Дидиереевые'),
  ('Droseraceae', 'Росянковые'),
  ('Gesneriaceae', 'Геснериевые'),
  ('Lamiaceae', 'Яснотковые'),
  ('Lauraceae', 'Лавровые'),
  ('Malvaceae', 'Мальвовые'),
  ('Marantaceae', 'Марантовые'),
  ('Moraceae', 'Тутовые'),
  ('Musaceae', 'Банановые'),
  ('Nepenthaceae', 'Непентесовые'),
  ('Oleaceae', 'Маслиновые'),
  ('Piperaceae', 'Перечные'),
  ('Polypodiaceae', 'Многоножковые'),
  ('Pteridaceae', 'Птерисовые'),
  ('Rubiaceae', 'Мареновые'),
  ('Rutaceae', 'Рутовые'),
  ('Selaginellaceae', 'Селагинелловые'),
  ('Urticaceae', 'Крапивные'),
  ('Vitaceae', 'Виноградовые'),
  ('Zamiaceae', 'Замиевые')
on conflict (latin_name) do nothing;

insert into public.genera (family_id, latin_name, name_ru)
select f.id, g.latin_name, g.name_ru
from (values
  ('Pteridaceae', 'Adiantum', 'Адиантум'),
  ('Crassulaceae', 'Aeonium', 'Эониум'),
  ('Gesneriaceae', 'Aeschynanthus', 'Эсхинантус'),
  ('Araceae', 'Alocasia', 'Алоказия'),
  ('Araceae', 'Anthurium', 'Антуриум'),
  ('Acanthaceae', 'Aphelandra', 'Афеландра'),
  ('Asphodelaceae', 'Aristaloe', 'Аристалоэ'),
  ('Araceae', 'Caladium', 'Каладиум'),
  ('Commelinaceae', 'Callisia', 'Каллизия'),
  ('Vitaceae', 'Cissus', 'Циссус'),
  ('Rutaceae', 'Citrus', 'Цитрус'),
  ('Amaryllidaceae', 'Clivia', 'Кливия'),
  ('Lamiaceae', 'Coleus', 'Колеус'),
  ('Crassulaceae', 'Crassula', 'Толстянка'),
  ('Marantaceae', 'Ctenanthe', 'Ктенанта'),
  ('Asteraceae', 'Curio', 'Курио'),
  ('Cycadaceae', 'Cycas', 'Саговник'),
  ('Droseraceae', 'Dionaea', 'Дионея'),
  ('Cactaceae', 'Epiphyllum', 'Эпифиллум'),
  ('Gesneriaceae', 'Episcia', 'Эписция'),
  ('Araliaceae', 'Fatsia', 'Фатсия'),
  ('Moraceae', 'Ficus', 'Фикус'),
  ('Acanthaceae', 'Fittonia', 'Фиттония'),
  ('Rubiaceae', 'Gardenia', 'Гардения'),
  ('Asphodelaceae', 'Gasteria', 'Гастерия'),
  ('Marantaceae', 'Goeppertia', 'Гёпперция'),
  ('Crassulaceae', 'Graptopetalum', 'Граптопеталум'),
  ('Cactaceae', 'Gymnocalycium', 'Гимнокалициум'),
  ('Malvaceae', 'Hibiscus', 'Гибискус'),
  ('Amaryllidaceae', 'Hippeastrum', 'Гиппеаструм'),
  ('Acanthaceae', 'Hypoestes', 'Гипоэстес'),
  ('Oleaceae', 'Jasminum', 'Жасмин'),
  ('Crassulaceae', 'Kalanchoe', 'Каланхоэ'),
  ('Lauraceae', 'Laurus', 'Лавр'),
  ('Aizoaceae', 'Lithops', 'Литопс'),
  ('Arecaceae', 'Livistona', 'Ливистона'),
  ('Cactaceae', 'Mammillaria', 'Маммиллярия'),
  ('Musaceae', 'Musa', 'Банан'),
  ('Bromeliaceae', 'Neoregelia', 'Неорегелия'),
  ('Nepenthaceae', 'Nepenthes', 'Непентес'),
  ('Lamiaceae', 'Ocimum', 'Базилик'),
  ('Malvaceae', 'Pachira', 'Пахира'),
  ('Piperaceae', 'Peperomia', 'Пеперомия'),
  ('Araceae', 'Philodendron', 'Филодендрон'),
  ('Polypodiaceae', 'Phlebodium', 'Флебодиум'),
  ('Arecaceae', 'Phoenix', 'Финик'),
  ('Urticaceae', 'Pilea', 'Пилея'),
  ('Polypodiaceae', 'Platycerium', 'Платицериум'),
  ('Araliaceae', 'Polyscias', 'Полисциас'),
  ('Didiereaceae', 'Portulacaria', 'Портулакария'),
  ('Bignoniaceae', 'Radermachera', 'Радермахера'),
  ('Araceae', 'Rhaphidophora', 'Рафидофора'),
  ('Cactaceae', 'Rhipsalis', 'Рипсалис'),
  ('Lamiaceae', 'Salvia', 'Шалфей'),
  ('Selaginellaceae', 'Selaginella', 'Селагинелла'),
  ('Urticaceae', 'Soleirolia', 'Солейролия'),
  ('Gesneriaceae', 'Streptocarpus', 'Стрептокарпус'),
  ('Marantaceae', 'Stromanthe', 'Строманта'),
  ('Bromeliaceae', 'Tillandsia', 'Тилландсия'),
  ('Commelinaceae', 'Tradescantia', 'Традесканция'),
  ('Bromeliaceae', 'Vriesea', 'Вриезия'),
  ('Zamiaceae', 'Zamia', 'Замия')
) as g(family, latin_name, name_ru)
join public.families f on f.latin_name = g.family
on conflict (latin_name) do nothing;

insert into public.species
  (genus_id, slug, latin_name, common_names, synonyms, description, plant_type,
   difficulty, toxic_to_pets, toxic_to_humans, air_purifying)
select g.id, s.slug, s.latin_name, s.common_names::jsonb, s.synonyms, s.description::jsonb,
       s.plant_type, s.difficulty, s.toxic_pets, s.toxic_humans, s.air_purifying
from (values
  ('Goeppertia', 'goeppertia-lancifolia', 'Goeppertia lancifolia',
   '{"ru": ["Калатея ланцетолистная", "Калатея инсигнис"], "en": ["Rattlesnake plant"]}', '{"Calathea lancifolia","Calathea insignis"}'::text[],
   '{"ru": "Длинные волнистые листья с тёмными пятнами и бордовой изнанкой; одна из самых выносливых калатей."}', 'травянистое', 3, false, false, false),
  ('Goeppertia', 'goeppertia-roseopicta', 'Goeppertia roseopicta',
   '{"ru": ["Калатея расписная", "Калатея розеопикта"], "en": ["Rose-painted calathea"]}', '{"Calathea roseopicta"}'::text[],
   '{"ru": "Округлые листья с розовым или серебристым рисунком; цвет зависит от сорта."}', 'травянистое', 4, false, false, false),
  ('Ctenanthe', 'ctenanthe-burle-marxii', 'Ctenanthe burle-marxii',
   '{"ru": ["Ктенанта Бурле-Маркса", "Ктенанта"], "en": ["Fishbone prayer plant", "Never-never plant"]}', '{}'::text[],
   '{"ru": "Серебристые листья с тёмными полосками «ёлочкой»; вечером листья приподнимаются."}', 'травянистое', 3, false, false, false),
  ('Stromanthe', 'stromanthe-thalia', 'Stromanthe thalia',
   '{"ru": ["Строманта", "Строманта кровавая"], "en": ["Triostar stromanthe"]}', '{"Stromanthe sanguinea"}'::text[],
   '{"ru": "Пёстрые бело-розово-зелёные листья с малиновой изнанкой."}', 'травянистое', 4, false, false, false),
  ('Fittonia', 'fittonia-albivenis', 'Fittonia albivenis',
   '{"ru": ["Фиттония", "Фиттония беложилковая"], "en": ["Nerve plant", "Mosaic plant"]}', '{"Fittonia verschaffeltii"}'::text[],
   '{"ru": "Невысокое растение с сеткой белых или розовых жилок; хорошо для флорариумов."}', 'травянистое', 3, false, false, false),
  ('Hypoestes', 'hypoestes-phyllostachya', 'Hypoestes phyllostachya',
   '{"ru": ["Гипоэстес", "Гипоэстес листоколосый"], "en": ["Polka dot plant", "Freckle face"]}', '{}'::text[],
   '{"ru": "Листья в розовых, красных или белых крапинках; быстро растёт."}', 'травянистое', 2, false, false, false),
  ('Aphelandra', 'aphelandra-squarrosa', 'Aphelandra squarrosa',
   '{"ru": ["Афеландра оттопыренная", "Афеландра"], "en": ["Zebra plant"]}', '{}'::text[],
   '{"ru": "Тёмные листья с белыми жилками и жёлтые колосья соцветий."}', 'кустарник', 4, false, false, false),
  ('Tradescantia', 'tradescantia-fluminensis', 'Tradescantia fluminensis',
   '{"ru": ["Традесканция приречная"], "en": ["Small-leaf spiderwort", "Wandering Jew"]}', '{"Tradescantia albiflora"}'::text[],
   '{"ru": "Классическая ампельная традесканция с мелкими листьями; есть пёстрые сорта."}', 'травянистое', 1, true, false, true),
  ('Tradescantia', 'tradescantia-pallida', 'Tradescantia pallida',
   '{"ru": ["Традесканция бледная", "Сеткреазия пурпурная"], "en": ["Purple heart"]}', '{"Setcreasea pallida","Setcreasea purpurea"}'::text[],
   '{"ru": "Фиолетовые листья и стебли; на солнце окраска ярче."}', 'травянистое', 1, true, false, false),
  ('Callisia', 'callisia-repens', 'Callisia repens',
   '{"ru": ["Каллизия ползучая"], "en": ["Turtle vine", "Creeping inch plant"]}', '{}'::text[],
   '{"ru": "Плотный ковёр мелких листьев; красиво в подвесном кашпо."}', 'травянистое', 1, true, false, false),
  ('Curio', 'curio-rowleyanus', 'Curio rowleyanus',
   '{"ru": ["Крестовник Роули", "Зелёный жемчуг"], "en": ["String of pearls"]}', '{"Senecio rowleyanus"}'::text[],
   '{"ru": "Ампельный суккулент с нитями листьев-горошин."}', 'суккулент', 2, true, true, false),
  ('Portulacaria', 'portulacaria-afra', 'Portulacaria afra',
   '{"ru": ["Портулакария африканская", "Слоновий куст"], "en": ["Elephant bush", "Dwarf jade"]}', '{}'::text[],
   '{"ru": "Суккулентный кустарник с мелкими мясистыми листьями; хорош для бонсай."}', 'суккулент', 1, false, false, false),
  ('Aristaloe', 'aristaloe-aristata', 'Aristaloe aristata',
   '{"ru": ["Алоэ остистое", "Аристалоэ"], "en": ["Lace aloe", "Guinea-fowl aloe"]}', '{"Aloe aristata"}'::text[],
   '{"ru": "Компактная розетка с белыми бугорками и мягкими остями на кончиках листьев."}', 'суккулент', 1, true, false, false),
  ('Gasteria', 'gasteria-bicolor', 'Gasteria bicolor',
   '{"ru": ["Гастерия двуцветная", "Гастерия"], "en": ["Ox tongue", "Lawyer''s tongue"]}', '{"Gasteria obliqua"}'::text[],
   '{"ru": "Суккулент с языковидными пятнистыми листьями; мирится с полутенью."}', 'суккулент', 1, false, false, false),
  ('Aeonium', 'aeonium-arboreum', 'Aeonium arboreum',
   '{"ru": ["Эониум древовидный"], "en": ["Tree aeonium", "Irish rose"]}', '{}'::text[],
   '{"ru": "Розетки на ветвящихся стволиках; зимой растёт, летом может впадать в покой."}', 'суккулент', 2, false, false, false),
  ('Graptopetalum', 'graptopetalum-paraguayense', 'Graptopetalum paraguayense',
   '{"ru": ["Граптопеталум парагвайский", "Каменная роза"], "en": ["Ghost plant", "Mother-of-pearl plant"]}', '{}'::text[],
   '{"ru": "Розетки перламутровых листьев на свисающих стеблях."}', 'суккулент', 1, false, false, false),
  ('Crassula', 'crassula-perforata', 'Crassula perforata',
   '{"ru": ["Толстянка пронзённолистная"], "en": ["String of buttons"]}', '{}'::text[],
   '{"ru": "Стебли словно нанизаны на треугольные листья с красной каймой."}', 'суккулент', 1, true, false, false),
  ('Kalanchoe', 'kalanchoe-daigremontiana', 'Kalanchoe daigremontiana',
   '{"ru": ["Каланхоэ Дегремона", "Бриофиллум"], "en": ["Mother of thousands"]}', '{"Bryophyllum daigremontianum"}'::text[],
   '{"ru": "По краям листьев образует множество деток-«малышей»."}', 'суккулент', 1, true, true, false),
  ('Kalanchoe', 'kalanchoe-tomentosa', 'Kalanchoe tomentosa',
   '{"ru": ["Каланхоэ войлочное", "Кошачьи ушки"], "en": ["Panda plant", "Pussy ears"]}', '{}'::text[],
   '{"ru": "Пушистые серебристые листья с коричневыми кончиками."}', 'суккулент', 1, true, false, false),
  ('Lithops', 'lithops-lesliei', 'Lithops lesliei',
   '{"ru": ["Литопс Лесли", "Живые камни"], "en": ["Living stones"]}', '{}'::text[],
   '{"ru": "Пара мясистых листьев, похожих на камешки; цветёт осенью."}', 'суккулент', 4, false, false, false),
  ('Mammillaria', 'mammillaria-elongata', 'Mammillaria elongata',
   '{"ru": ["Маммиллярия удлинённая"], "en": ["Ladyfinger cactus", "Gold lace cactus"]}', '{}'::text[],
   '{"ru": "Кактус из множества «пальчиков» в золотистых колючках."}', 'суккулент', 1, false, false, false),
  ('Gymnocalycium', 'gymnocalycium-mihanovichii', 'Gymnocalycium mihanovichii',
   '{"ru": ["Гимнокалициум Михановича", "Лунный кактус"], "en": ["Moon cactus", "Chin cactus"]}', '{}'::text[],
   '{"ru": "Яркие красные и жёлтые формы без хлорофилла продают привитыми на другой кактус."}', 'суккулент', 2, false, false, false),
  ('Rhipsalis', 'rhipsalis-baccifera', 'Rhipsalis baccifera',
   '{"ru": ["Рипсалис ягодоносный", "Прутовидник"], "en": ["Mistletoe cactus"]}', '{}'::text[],
   '{"ru": "Лесной кактус без колючек с тонкими свисающими побегами."}', 'эпифит', 1, false, false, false),
  ('Epiphyllum', 'epiphyllum-oxypetalum', 'Epiphyllum oxypetalum',
   '{"ru": ["Эпифиллум остролепестный", "Царица ночи"], "en": ["Queen of the night", "Dutchman''s pipe cactus"]}', '{}'::text[],
   '{"ru": "Лесной кактус с плоскими стеблями; огромные душистые цветки раскрываются на одну ночь."}', 'эпифит', 2, false, false, false),
  ('Adiantum', 'adiantum-raddianum', 'Adiantum raddianum',
   '{"ru": ["Адиантум Радди", "Венерин волос"], "en": ["Maidenhair fern"]}', '{"Adiantum cuneatum"}'::text[],
   '{"ru": "Нежный папоротник с тонкими чёрными черешками и веерами мелких листочков."}', 'папоротник', 4, false, false, true),
  ('Platycerium', 'platycerium-bifurcatum', 'Platycerium bifurcatum',
   '{"ru": ["Платицериум двувильчатый", "Олений рог"], "en": ["Staghorn fern"]}', '{}'::text[],
   '{"ru": "Эпифитный папоротник с вайями, похожими на оленьи рога; часто растят на доске."}', 'папоротник', 3, false, false, false),
  ('Phlebodium', 'phlebodium-aureum', 'Phlebodium aureum',
   '{"ru": ["Флебодиум золотистый", "Голубой папоротник"], "en": ["Blue star fern", "Golden polypody"]}', '{"Polypodium aureum"}'::text[],
   '{"ru": "Папоротник с сизо-голубыми рассечёнными вайями и мохнатыми корневищами."}', 'папоротник', 2, false, false, true),
  ('Phoenix', 'phoenix-roebelenii', 'Phoenix roebelenii',
   '{"ru": ["Финик Робелена", "Карликовая финиковая пальма"], "en": ["Pygmy date palm"]}', '{}'::text[],
   '{"ru": "Невысокая изящная пальма с тонкими перистыми листьями."}', 'пальма', 2, false, false, true),
  ('Livistona', 'livistona-chinensis', 'Livistona chinensis',
   '{"ru": ["Ливистона китайская"], "en": ["Chinese fan palm"]}', '{}'::text[],
   '{"ru": "Веерная пальма с поникающими кончиками листьев."}', 'пальма', 2, false, false, true),
  ('Cycas', 'cycas-revoluta', 'Cycas revoluta',
   '{"ru": ["Саговник поникающий", "Цикас"], "en": ["Sago palm", "King sago"]}', '{}'::text[],
   '{"ru": "Древнее растение с жёсткими перистыми листьями на толстом стволе; очень ядовит."}', 'дерево', 2, true, true, false),
  ('Zamia', 'zamia-furfuracea', 'Zamia furfuracea',
   '{"ru": ["Замия чешуйчатая", "Замия"], "en": ["Cardboard palm"]}', '{}'::text[],
   '{"ru": "Плотные «картонные» листья на коротком стволе; все части ядовиты."}', 'дерево', 2, true, true, false),
  ('Clivia', 'clivia-miniata', 'Clivia miniata',
   '{"ru": ["Кливия киноварная"], "en": ["Natal lily", "Bush lily"]}', '{}'::text[],
   '{"ru": "Тёмные ремневидные листья и зонтики оранжевых цветков в конце зимы."}', 'травянистое', 2, true, true, false),
  ('Hippeastrum', 'hippeastrum-hybridum', 'Hippeastrum × hybridum',
   '{"ru": ["Гиппеаструм", "Амариллис"], "en": ["Amaryllis"]}', '{"Hippeastrum hybridum"}'::text[],
   '{"ru": "Луковичное растение с огромными цветками-граммофонами на высоком цветоносе."}', 'травянистое', 2, true, true, false),
  ('Gardenia', 'gardenia-jasminoides', 'Gardenia jasminoides',
   '{"ru": ["Гардения жасминовидная"], "en": ["Gardenia", "Cape jasmine"]}', '{"Gardenia augusta"}'::text[],
   '{"ru": "Кустарник с глянцевыми листьями и белыми цветками с сильным ароматом."}', 'кустарник', 5, true, false, false),
  ('Jasminum', 'jasminum-polyanthum', 'Jasminum polyanthum',
   '{"ru": ["Жасмин многоцветковый"], "en": ["Pink jasmine", "Winter jasmine"]}', '{}'::text[],
   '{"ru": "Вьющийся кустарник с облаками душистых белых цветков в конце зимы."}', 'лиана', 3, false, false, false),
  ('Hibiscus', 'hibiscus-rosa-sinensis', 'Hibiscus rosa-sinensis',
   '{"ru": ["Гибискус китайский", "Китайская роза"], "en": ["Chinese hibiscus"]}', '{}'::text[],
   '{"ru": "Кустарник с крупными яркими цветками, каждый живёт день-два."}', 'кустарник', 2, false, false, false),
  ('Citrus', 'citrus-limon', 'Citrus × limon',
   '{"ru": ["Лимон"], "en": ["Lemon tree"]}', '{"Citrus limon"}'::text[],
   '{"ru": "Цитрусовое деревце, которое цветёт и плодоносит в квартире."}', 'дерево', 3, true, false, false),
  ('Aeschynanthus', 'aeschynanthus-radicans', 'Aeschynanthus radicans',
   '{"ru": ["Эсхинантус"], "en": ["Lipstick plant"]}', '{"Aeschynanthus lobbianus"}'::text[],
   '{"ru": "Ампельное растение с красными трубчатыми цветками, выглядывающими из чашечек."}', 'эпифит', 3, false, false, false),
  ('Episcia', 'episcia-cupreata', 'Episcia cupreata',
   '{"ru": ["Эписция медно-красная"], "en": ["Flame violet"]}', '{}'::text[],
   '{"ru": "Бархатистые медные листья с узором и красные цветки; растёт усами, как клубника."}', 'травянистое', 3, false, false, false),
  ('Streptocarpus', 'streptocarpus-hybridus', 'Streptocarpus × hybridus',
   '{"ru": ["Стрептокарпус гибридный"], "en": ["Cape primrose"]}', '{"Streptocarpus hybridus"}'::text[],
   '{"ru": "Розетка морщинистых листьев и облако цветков-колокольчиков почти круглый год."}', 'травянистое', 3, false, false, false),
  ('Dionaea', 'dionaea-muscipula', 'Dionaea muscipula',
   '{"ru": ["Венерина мухоловка", "Дионея"], "en": ["Venus flytrap"]}', '{}'::text[],
   '{"ru": "Хищное растение, ловящее насекомых зубчатыми ловушками."}', 'травянистое', 5, false, false, false),
  ('Nepenthes', 'nepenthes-ventrata', 'Nepenthes × ventrata',
   '{"ru": ["Непентес", "Кувшиночник"], "en": ["Pitcher plant"]}', '{"Nepenthes ventrata"}'::text[],
   '{"ru": "Хищная лиана с кувшинчиками-ловушками на концах листьев."}', 'эпифит', 4, false, false, false),
  ('Ficus', 'ficus-microcarpa', 'Ficus microcarpa',
   '{"ru": ["Фикус микрокарпа", "Фикус «Гинсенг»"], "en": ["Chinese banyan", "Ginseng ficus"]}', '{"Ficus retusa"}'::text[],
   '{"ru": "Фикус с утолщёнными корнями; популярен как бонсай."}', 'дерево', 2, true, false, true),
  ('Pachira', 'pachira-aquatica', 'Pachira aquatica',
   '{"ru": ["Пахира водная", "Денежное дерево"], "en": ["Money tree", "Guiana chestnut"]}', '{"Pachira glabra"}'::text[],
   '{"ru": "Дерево с пальчатыми листьями; стволы часто переплетают косичкой."}', 'дерево', 1, false, false, true),
  ('Radermachera', 'radermachera-sinica', 'Radermachera sinica',
   '{"ru": ["Радермахера китайская"], "en": ["China doll"]}', '{}'::text[],
   '{"ru": "Кустистое деревце с блестящими резными листьями."}', 'дерево', 3, false, false, true),
  ('Fatsia', 'fatsia-japonica', 'Fatsia japonica',
   '{"ru": ["Фатсия японская", "Японская аралия"], "en": ["Japanese aralia", "Paperplant"]}', '{"Aralia japonica"}'::text[],
   '{"ru": "Крупные глянцевые пальчато-лопастные листья; любит прохладу."}', 'кустарник', 2, true, false, true),
  ('Polyscias', 'polyscias-fruticosa', 'Polyscias fruticosa',
   '{"ru": ["Полисциас кустарниковый", "Аралия Мин"], "en": ["Ming aralia"]}', '{}'::text[],
   '{"ru": "Кружевные перисто-рассечённые листья на ветвистом стволе."}', 'кустарник', 4, true, false, false),
  ('Cissus', 'cissus-rhombifolia', 'Cissus rhombifolia',
   '{"ru": ["Циссус ромболистный", "Комнатный виноград"], "en": ["Grape ivy"]}', '{"Rhoicissus rhomboidea"}'::text[],
   '{"ru": "Лиана с усиками и тройчатыми листьями; выносит тень."}', 'лиана', 1, false, false, true),
  ('Soleirolia', 'soleirolia-soleirolii', 'Soleirolia soleirolii',
   '{"ru": ["Солейролия", "Гельксина"], "en": ["Baby''s tears", "Mind-your-own-business"]}', '{"Helxine soleirolii"}'::text[],
   '{"ru": "Густой ковёр из крошечных листочков."}', 'травянистое', 2, false, false, false),
  ('Tillandsia', 'tillandsia-ionantha', 'Tillandsia ionantha',
   '{"ru": ["Тилландсия фиолетовоцветковая", "Атмосферная тилландсия"], "en": ["Air plant", "Sky plant"]}', '{}'::text[],
   '{"ru": "Атмосферная бромелия без грунта: влагу и питание берёт листьями."}', 'эпифит', 2, false, false, true),
  ('Vriesea', 'vriesea-splendens', 'Vriesea splendens',
   '{"ru": ["Вриезия блестящая"], "en": ["Flaming sword"]}', '{}'::text[],
   '{"ru": "Бромелия с полосатыми листьями и ярким красным «мечом» прицветника."}', 'эпифит', 2, false, false, true),
  ('Neoregelia', 'neoregelia-carolinae', 'Neoregelia carolinae',
   '{"ru": ["Неорегелия Каролины"], "en": ["Blushing bromeliad"]}', '{}'::text[],
   '{"ru": "Бромелия, у которой перед цветением краснеет центр розетки."}', 'эпифит', 2, false, false, true),
  ('Coleus', 'coleus-scutellarioides', 'Coleus scutellarioides',
   '{"ru": ["Колеус", "Колеус Блюме"], "en": ["Coleus", "Painted nettle"]}', '{"Plectranthus scutellarioides","Solenostemon scutellarioides"}'::text[],
   '{"ru": "Листья невероятных расцветок — от лаймовых до почти чёрных."}', 'травянистое', 1, true, false, false),
  ('Salvia', 'salvia-rosmarinus', 'Salvia rosmarinus',
   '{"ru": ["Розмарин"], "en": ["Rosemary"]}', '{"Rosmarinus officinalis"}'::text[],
   '{"ru": "Ароматный полукустарник для кухни; на подоконнике нужен максимум света."}', 'кустарник', 3, false, false, false),
  ('Ocimum', 'ocimum-basilicum', 'Ocimum basilicum',
   '{"ru": ["Базилик"], "en": ["Basil", "Sweet basil"]}', '{}'::text[],
   '{"ru": "Пряная трава; на солнечном окне даёт урожай несколько месяцев."}', 'травянистое', 2, false, false, false),
  ('Laurus', 'laurus-nobilis', 'Laurus nobilis',
   '{"ru": ["Лавр благородный"], "en": ["Bay laurel", "Sweet bay"]}', '{}'::text[],
   '{"ru": "Вечнозелёное деревце; листья — та самая лавровая приправа."}', 'дерево', 2, true, false, false),
  ('Musa', 'musa-acuminata', 'Musa acuminata',
   '{"ru": ["Банан остроконечный", "Комнатный банан"], "en": ["Dwarf banana", "Dwarf Cavendish"]}', '{}'::text[],
   '{"ru": "Огромные листья-паруса; карликовые сорта растут в квартире."}', 'травянистое', 3, false, false, false),
  ('Peperomia', 'peperomia-caperata', 'Peperomia caperata',
   '{"ru": ["Пеперомия морщинистая"], "en": ["Emerald ripple peperomia"]}', '{}'::text[],
   '{"ru": "Компактная розетка гофрированных листьев и «хвостики» соцветий."}', 'травянистое', 1, false, false, false),
  ('Peperomia', 'peperomia-prostrata', 'Peperomia prostrata',
   '{"ru": ["Пеперомия распростёртая", "Черепашки"], "en": ["String of turtles"]}', '{}'::text[],
   '{"ru": "Ампельная пеперомия с круглыми листиками в узоре «черепаший панцирь»."}', 'травянистое', 3, false, false, false),
  ('Pilea', 'pilea-cadierei', 'Pilea cadierei',
   '{"ru": ["Пилея Кадье", "Алюминиевое растение"], "en": ["Aluminum plant"]}', '{}'::text[],
   '{"ru": "Листья с серебристыми, будто металлическими пятнами."}', 'травянистое', 1, false, false, false),
  ('Philodendron', 'philodendron-erubescens', 'Philodendron erubescens',
   '{"ru": ["Филодендрон краснеющий"], "en": ["Blushing philodendron", "Red-leaf philodendron"]}', '{}'::text[],
   '{"ru": "Лиана с глянцевыми стреловидными листьями и красноватыми черешками; популярны сорта «Pink Princess»."}', 'лиана', 2, true, true, true),
  ('Rhaphidophora', 'rhaphidophora-tetrasperma', 'Rhaphidophora tetrasperma',
   '{"ru": ["Рафидофора четырёхсемянная", "Мини-монстера"], "en": ["Mini monstera", "Philodendron ginny"]}', '{}'::text[],
   '{"ru": "Быстрорастущая лиана с резными листьями, похожими на маленькую монстеру."}', 'лиана', 2, true, true, true),
  ('Alocasia', 'alocasia-zebrina', 'Alocasia zebrina',
   '{"ru": ["Алоказия зебрина"], "en": ["Zebra alocasia"]}', '{}'::text[],
   '{"ru": "Стреловидные листья на полосатых, как у зебры, черешках."}', 'травянистое', 4, true, true, false),
  ('Anthurium', 'anthurium-clarinervium', 'Anthurium clarinervium',
   '{"ru": ["Антуриум светложилковый"], "en": ["Velvet cardboard anthurium"]}', '{}'::text[],
   '{"ru": "Бархатные сердцевидные листья с белыми жилками."}', 'эпифит', 4, true, true, false),
  ('Caladium', 'caladium-bicolor', 'Caladium bicolor',
   '{"ru": ["Каладиум двуцветный"], "en": ["Heart of Jesus", "Angel wings"]}', '{"Caladium × hortulanum"}'::text[],
   '{"ru": "Тонкие листья-сердца с розовыми, красными и белыми узорами; растёт из клубня."}', 'травянистое', 3, true, true, false),
  ('Selaginella', 'selaginella-martensii', 'Selaginella martensii',
   '{"ru": ["Селагинелла Мартенса"], "en": ["Spike moss", "Frosty fern"]}', '{}'::text[],
   '{"ru": "Кружевное растение, похожее на мох; незаменимо во флорариумах."}', 'травянистое', 4, false, false, false)
) as s(genus, slug, latin_name, common_names, synonyms, description, plant_type,
       difficulty, toxic_pets, toxic_humans, air_purifying)
join public.genera g on g.latin_name = s.genus
on conflict do nothing;

insert into public.care_profiles
  (species_id, light, water_interval_summer, water_interval_winter, soil_dryness_before_watering,
   humidity_min_pct, temp_min_c, temp_max_c, fertilize_interval_days, fertilize_months,
   repot_every_years, propagation, tips)
select sp.id, c.light, c.summer, c.winter, c.dryness::jsonb, c.humidity, c.tmin, c.tmax,
       c.fert_days, c.fert_months, c.repot, c.propagation, c.tips::jsonb
from (values
  ('goeppertia-lancifolia', 'medium', 4, 7, '{"ru": "верхний слой"}', 55, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Поливайте мягкой отстоянной водой", "Скрученные листья — пересыхание или сухой воздух"]}'),
  ('goeppertia-roseopicta', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Нужна высокая влажность и никаких сквозняков", "Прямое солнце выжигает рисунок"]}'),
  ('ctenanthe-burle-marxii', 'medium', 4, 7, '{"ru": "верхний слой"}', 55, 17, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Менее капризна, чем калатеи", "Любит тёплую мягкую воду"]}'),
  ('stromanthe-thalia', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Для яркой окраски нужен хороший рассеянный свет", "Сухие кончики — сухой воздух"]}'),
  ('fittonia-albivenis', 'medium', 3, 5, '{"ru": "не пересыхает"}', 60, 18, 27, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["При пересыхании «падает в обморок» — после полива оживает", "Отлично растёт во флорариуме"]}'),
  ('hypoestes-phyllostachya', 'bright_indirect', 4, 6, '{"ru": "верхние 1–2 см"}', 50, 16, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки","семена"}'::text[],
   '{"ru": ["Прищипывайте, чтобы куст не вытягивался", "Без света пятна бледнеют"]}'),
  ('aphelandra-squarrosa', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 18, 26, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"верхушечные черенки"}'::text[],
   '{"ru": ["После цветения обрежьте соцветие", "Не пересушивайте — сбрасывает листья"]}'),
  ('tradescantia-fluminensis', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 40, 12, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Легко укореняется в воде", "Омолаживайте черенками раз в год"]}'),
  ('tradescantia-pallida', 'direct', 5, 10, '{"ru": "верхние 2 см"}', 30, 10, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Сок может раздражать кожу", "Без солнца зеленеет и вытягивается"]}'),
  ('callisia-repens', 'bright_indirect', 4, 8, '{"ru": "верхний слой"}', 40, 14, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Прищипывайте для густоты", "Перелив зимой — гниль стеблей"]}'),
  ('curio-rowleyanus', 'bright_indirect', 10, 21, '{"ru": "полностью"}', 30, 10, 28, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Сморщенные «жемчужины» — пора поливать", "Неглубокий горшок и лёгкий грунт"]}'),
  ('portulacaria-afra', 'direct', 10, 25, '{"ru": "полностью"}', 20, 10, 32, 30,
   '{5,6,7,8}'::smallint[], 3, '{"черенки"}'::text[],
   '{"ru": ["Легко формируется обрезкой", "Зимой светлое прохладное место"]}'),
  ('aristaloe-aristata', 'direct', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки"}'::text[],
   '{"ru": ["Даёт много деток — рассаживайте весной", "Зимой полив раз в месяц"]}'),
  ('gasteria-bicolor', 'bright_indirect', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки","листья"}'::text[],
   '{"ru": ["В отличие от многих суккулентов, выносит полутень"]}'),
  ('aeonium-arboreum', 'direct', 10, 10, '{"ru": "полностью"}', 30, 8, 28, 30,
   '{10,11,12,1,2,3}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Летом в жару полив сократите — это период покоя", "Тёмные сорта ярче на солнце"]}'),
  ('graptopetalum-paraguayense', 'direct', 12, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"листья","черенки"}'::text[],
   '{"ru": ["Листья легко отламываются и сами укореняются"]}'),
  ('crassula-perforata', 'direct', 12, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Без солнца теряет красную кайму"]}'),
  ('kalanchoe-daigremontiana', 'bright_indirect', 10, 20, '{"ru": "полностью"}', 30, 12, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки"}'::text[],
   '{"ru": ["Детки падают в соседние горшки и прорастают там", "Ядовит для кошек и собак"]}'),
  ('kalanchoe-tomentosa', 'direct', 12, 25, '{"ru": "полностью"}', 20, 10, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"листья","черенки"}'::text[],
   '{"ru": ["Не опрыскивайте опушённые листья"]}'),
  ('lithops-lesliei', 'direct', 14, 60, '{"ru": "полностью"}', 20, 8, 32, null,
   '{}'::smallint[], 4, '{"семена","деление"}'::text[],
   '{"ru": ["Во время смены листьев (зима — весна) не поливайте совсем", "Лучше недолить: перелив губителен"]}'),
  ('mammillaria-elongata', 'direct', 14, 40, '{"ru": "полностью"}', 20, 5, 32, 30,
   '{5,6,7,8}'::smallint[], 2, '{"детки"}'::text[],
   '{"ru": ["Зимой прохлада и сухость — для весеннего цветения"]}'),
  ('gymnocalycium-mihanovichii', 'bright_indirect', 14, 30, '{"ru": "полностью"}', 20, 8, 30, 30,
   '{5,6,7,8}'::smallint[], 2, '{"прививка","детки"}'::text[],
   '{"ru": ["Цветные формы живут только привитыми", "Прямое полуденное солнце обжигает"]}'),
  ('rhipsalis-baccifera', 'bright_indirect', 7, 14, '{"ru": "верхние 2 см"}', 40, 12, 28, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Лучше смотрится в подвесном кашпо", "Любит влажный воздух, в отличие от пустынных кактусов"]}'),
  ('epiphyllum-oxypetalum', 'bright_indirect', 7, 14, '{"ru": "верхние 2–3 см"}', 40, 10, 28, 21,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Для цветения нужна прохладная зимовка +10–15 °C"]}'),
  ('adiantum-raddianum', 'medium', 3, 5, '{"ru": "не пересыхает"}', 60, 15, 25, 21,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Даже однократное пересыхание — сухие вайи", "Держите подальше от батарей"]}'),
  ('platycerium-bifurcatum', 'bright_indirect', 7, 14, '{"ru": "основание подсыхает"}', 50, 15, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"детки","споры"}'::text[],
   '{"ru": ["Поливайте погружением основания", "Не стирайте серебристый налёт с листьев"]}'),
  ('phlebodium-aureum', 'medium', 5, 8, '{"ru": "верхний слой"}', 50, 15, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление","споры"}'::text[],
   '{"ru": ["Мохнатые корневища не засыпайте землёй", "Выносливее большинства папоротников"]}'),
  ('phoenix-roebelenii', 'bright_indirect', 6, 12, '{"ru": "верхние 3 см"}', 50, 15, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["У основания листьев колючки — осторожнее при пересадке"]}'),
  ('livistona-chinensis', 'bright_indirect', 6, 12, '{"ru": "верхние 3 см"}', 50, 12, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Не обрезайте сухие кончики до живой ткани"]}'),
  ('cycas-revoluta', 'direct', 10, 21, '{"ru": "верхняя половина горшка"}', 40, 10, 30, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена","детки"}'::text[],
   '{"ru": ["Все части очень ядовиты для животных и людей", "Новые листья растут розеткой раз в год — не переставляйте в это время"]}'),
  ('zamia-furfuracea', 'bright_indirect', 10, 21, '{"ru": "верхняя половина горшка"}', 40, 12, 30, 30,
   '{5,6,7,8}'::smallint[], 3, '{"семена"}'::text[],
   '{"ru": ["Ядовита для питомцев", "Перелив — главная причина гибели"]}'),
  ('clivia-miniata', 'bright_indirect', 7, 21, '{"ru": "верхние 3 см"}', 40, 10, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 3, '{"деление","семена"}'::text[],
   '{"ru": ["Для цветения нужна прохладная сухая зимовка 6–8 недель", "Цветёт лучше в тесном горшке"]}'),
  ('hippeastrum-hybridum', 'direct', 7, 30, '{"ru": "верхние 2–3 см"}', 40, 15, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"детки","семена"}'::text[],
   '{"ru": ["После цветения растите листья всё лето — они кормят луковицу", "Осенью 2 месяца покоя без полива"]}'),
  ('gardenia-jasminoides', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 16, 24, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Нужна кислая почва и мягкая вода", "Бутоны опадают от холода, сквозняков и перемены места"]}'),
  ('jasminum-polyanthum', 'bright_indirect', 4, 7, '{"ru": "верхние 2 см"}', 50, 8, 26, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки","отводки"}'::text[],
   '{"ru": ["Для закладки бутонов осенью нужна прохлада +8–12 °C"]}'),
  ('hibiscus-rosa-sinensis', 'direct', 3, 7, '{"ru": "верхние 2 см"}', 50, 12, 30, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Весенняя обрезка — больше цветов", "Сбрасывает бутоны при пересыхании и перестановке"]}'),
  ('citrus-limon', 'direct', 4, 10, '{"ru": "верхние 2–3 см"}', 50, 12, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 2, '{"черенки","прививка"}'::text[],
   '{"ru": ["Зимой нужен свет или прохлада +12–14 °C", "Удобрения для цитрусовых с микроэлементами"]}'),
  ('aeschynanthus-radicans', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{3,4,5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Для цветения нужна прохладная зимовка +16 °C"]}'),
  ('episcia-cupreata', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"усы","черенки"}'::text[],
   '{"ru": ["Капли на листьях оставляют пятна — поливайте в поддон"]}'),
  ('streptocarpus-hybridus', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 50, 16, 25, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"листовые черенки","деление"}'::text[],
   '{"ru": ["Широкий неглубокий горшок", "Отцветшие цветоносы срезайте у основания"]}'),
  ('dionaea-muscipula', 'direct', 2, 4, '{"ru": "не пересыхает"}', 50, 5, 32, null,
   '{}'::smallint[], 1, '{"деление","семена"}'::text[],
   '{"ru": ["Поливайте только дистиллированной или дождевой водой", "Зимой обязателен покой при +2–10 °C", "Не кормите мясом и не удобряйте"]}'),
  ('nepenthes-ventrata', 'bright_indirect', 3, 5, '{"ru": "не пересыхает"}', 60, 16, 30, null,
   '{}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Только мягкая вода и грунт из мха и коры", "Без высокой влажности новые кувшины не образуются"]}'),
  ('ficus-microcarpa', 'bright_indirect', 6, 12, '{"ru": "верхние 2 см"}', 50, 15, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","воздушные отводки"}'::text[],
   '{"ru": ["Опрыскивайте в отопительный сезон", "Обрезка весной для формы кроны"]}'),
  ('pachira-aquatica', 'bright_indirect', 7, 14, '{"ru": "верхние 3–5 см"}', 40, 15, 30, 21,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Запасает воду в стволе — не переливайте", "Поворачивайте горшок для ровной кроны"]}'),
  ('radermachera-sinica', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 50, 15, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Сбрасывает листья от сквозняков и пересыхания"]}'),
  ('fatsia-japonica', 'medium', 5, 10, '{"ru": "верхние 2 см"}', 50, 8, 22, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Зимой в тепле страдает — оптимально +10–15 °C"]}'),
  ('polyscias-fruticosa', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Не переносит холодных подоконников и сквозняков"]}'),
  ('cissus-rhombifolia', 'medium', 5, 10, '{"ru": "верхние 2 см"}', 40, 12, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Дайте опору — цепляется усиками"]}'),
  ('soleirolia-soleirolii', 'medium', 3, 5, '{"ru": "не пересыхает"}', 60, 10, 24, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Поливайте в поддон, чтобы не раскрывался ковёр", "Хорошая почвопокровная для флорариума"]}'),
  ('tillandsia-ionantha', 'bright_indirect', 4, 7, '{"ru": "растение высохло после купания"}', 50, 12, 30, 30,
   '{4,5,6,7,8,9}'::smallint[], null, '{"детки"}'::text[],
   '{"ru": ["Раз в неделю купайте 20 минут в мягкой воде", "После купания стряхните воду и просушите вверх ногами"]}'),
  ('vriesea-splendens', 'bright_indirect', 7, 14, '{"ru": "верхний слой"}', 60, 18, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки"}'::text[],
   '{"ru": ["Воду наливайте в розетку листьев", "После цветения розетка отмирает — растите деток"]}'),
  ('neoregelia-carolinae', 'bright_indirect', 7, 14, '{"ru": "верхний слой"}', 60, 16, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"детки"}'::text[],
   '{"ru": ["В центре розетки держите немного воды"]}'),
  ('coleus-scutellarioides', 'bright_indirect', 3, 6, '{"ru": "верхний слой"}', 50, 14, 28, 14,
   '{3,4,5,6,7,8,9}'::smallint[], 1, '{"черенки","семена"}'::text[],
   '{"ru": ["Удаляйте цветоносы — иначе листья мельчают", "Прищипывайте для густоты"]}'),
  ('salvia-rosmarinus', 'direct', 5, 10, '{"ru": "верхние 2 см"}', 40, 5, 28, 21,
   '{5,6,7,8}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Зимой прохлада +5–10 °C и много света", "Пересыхание кома губительно, как и застой воды"]}'),
  ('ocimum-basilicum', 'direct', 2, 4, '{"ru": "верхний слой"}', 40, 15, 30, 14,
   '{3,4,5,6,7,8,9}'::smallint[], null, '{"семена","черенки"}'::text[],
   '{"ru": ["Срезайте верхушки над парой листьев — куст будет ветвиться", "Удаляйте бутоны"]}'),
  ('laurus-nobilis', 'bright_indirect', 6, 14, '{"ru": "верхние 3 см"}', 40, 5, 28, 21,
   '{5,6,7,8}'::smallint[], 3, '{"черенки"}'::text[],
   '{"ru": ["Хорошо переносит стрижку в форму шара", "Зимой прохлада +5–12 °C"]}'),
  ('musa-acuminata', 'direct', 3, 7, '{"ru": "верхние 2 см"}', 60, 16, 32, 7,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"отпрыски"}'::text[],
   '{"ru": ["Много воды и удобрений летом", "Листья рвутся от сквозняка — это нормально"]}'),
  ('peperomia-caperata', 'medium', 8, 14, '{"ru": "верхняя половина горшка"}', 40, 16, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"листовые черенки"}'::text[],
   '{"ru": ["Перелив опаснее засухи"]}'),
  ('peperomia-prostrata', 'bright_indirect', 7, 12, '{"ru": "верхняя половина горшка"}', 50, 18, 28, 30,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Мелкий горшок и рыхлый грунт"]}'),
  ('pilea-cadierei', 'bright_indirect', 5, 8, '{"ru": "верхние 2 см"}', 50, 15, 26, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки"}'::text[],
   '{"ru": ["Прищипывайте — быстро вытягивается"]}'),
  ('philodendron-erubescens', 'bright_indirect', 7, 12, '{"ru": "верхние 3 см"}', 50, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Нужна опора из кокоса или мха"]}'),
  ('rhaphidophora-tetrasperma', 'bright_indirect', 6, 10, '{"ru": "верхние 2–3 см"}', 50, 16, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Растёт быстро — давайте опору"]}'),
  ('alocasia-zebrina', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 18, 30, 14,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"клубеньки","деление"}'::text[],
   '{"ru": ["Не переливайте — клубень гниёт", "Зимой может сбросить листья и отдыхать"]}'),
  ('anthurium-clarinervium', 'bright_indirect', 6, 10, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{4,5,6,7,8,9}'::smallint[], 2, '{"деление","семена"}'::text[],
   '{"ru": ["Грунт — кора, мох и перлит", "Высокая влажность обязательна"]}'),
  ('caladium-bicolor', 'bright_indirect', 4, 30, '{"ru": "верхний слой"}', 60, 20, 30, 14,
   '{4,5,6,7,8}'::smallint[], 1, '{"клубни"}'::text[],
   '{"ru": ["Осенью листья отмирают — клубень хранят сухим при +18 °C", "Весной высаживают снова"]}'),
  ('selaginella-martensii', 'medium', 2, 4, '{"ru": "не пересыхает"}', 70, 16, 26, 30,
   '{4,5,6,7,8,9}'::smallint[], 1, '{"черенки","деление"}'::text[],
   '{"ru": ["Без высокой влажности засыхает — лучше в закрытом флорариуме"]}')
) as c(slug, light, summer, winter, dryness, humidity, tmin, tmax, fert_days, fert_months,
       repot, propagation, tips)
join public.species sp on sp.slug = c.slug
on conflict (species_id) do nothing;
