-- База знаний, часть 2: новые виды — в первую очередь те, что садоводы уже добавили в коллекции,
-- но не нашли в базе. Латинские названия — по POWO, прежние — в synonyms; токсичность — по ASPCA.
-- Миграция идемпотентна.

insert into public.families (latin_name, name_ru) values
  ('Cactaceae', 'Кактусовые'),
  ('Droseraceae', 'Росянковые'),
  ('Lauraceae', 'Лавровые'),
  ('Lentibulariaceae', 'Пузырчатковые'),
  ('Pteridaceae', 'Птерисовые'),
  ('Solanaceae', 'Паслёновые')
on conflict (latin_name) do nothing;

insert into public.genera (family_id, latin_name, name_ru)
select f.id, g.latin_name, g.name_ru
from (values
  ('Cactaceae', 'Cereus', 'Цереус'),
  ('Cactaceae', 'Cleistocactus', 'Клейстокактус'),
  ('Cactaceae', 'Echinopsis', 'Эхинопсис'),
  ('Cactaceae', 'Parodia', 'Пародия'),
  ('Droseraceae', 'Drosera', 'Росянка'),
  ('Lauraceae', 'Persea', 'Персея'),
  ('Lentibulariaceae', 'Pinguicula', 'Жирянка'),
  ('Pteridaceae', 'Pteris', 'Птерис'),
  ('Solanaceae', 'Capsicum', 'Перец')
) as g(family, latin_name, name_ru)
join public.families f on f.latin_name = g.family
on conflict (latin_name) do nothing;

insert into public.species
  (genus_id, slug, latin_name, common_names, synonyms, description, plant_type,
   difficulty, toxic_to_pets, toxic_to_humans, air_purifying)
select g.id, s.slug, s.latin_name, s.common_names::jsonb, s.synonyms, s.description::jsonb,
       s.plant_type, s.difficulty, s.toxic_pets, s.toxic_humans, s.air_purifying
from (values
  ('Anthurium', 'anthurium-scherzerianum', 'Anthurium scherzerianum',
   '{"ru": ["Антуриум Шерцера", "Цветок-фламинго"], "en": ["Flamingo flower"]}', '{}'::text[],
   '{"ru": "Компактный антуриум с яркими покрывалами и закрученным, как хвостик, початком. Цветёт почти круглый год."}', 'травянистое', 3, true, true, true),
  ('Alocasia', 'alocasia-longiloba', 'Alocasia longiloba',
   '{"ru": ["Алоказия длиннолопастная"], "en": ["Tiger taro"]}', '{"Alocasia lowii","Alocasia watsoniana"}'::text[],
   '{"ru": "Алоказия со стреловидными тёмно-зелёными листьями и серебристыми жилками; у разных форм рисунок сильно отличается."}', 'травянистое', 4, true, true, false),
  ('Alocasia', 'alocasia-wentii', 'Alocasia wentii',
   '{"ru": ["Алоказия Вента"], "en": ["Hardy elephant ear", "New Guinea shield"]}', '{}'::text[],
   '{"ru": "Одна из самых неприхотливых алоказий: крупные листья-щиты с металлическим отливом и бордовой изнанкой."}', 'травянистое', 2, true, true, false),
  ('Alocasia', 'alocasia-macrorrhizos', 'Alocasia macrorrhizos',
   '{"ru": ["Алоказия крупнокорневая", "Алоказия «Слоновое ухо»"], "en": ["Giant taro", "Elephant ear"]}', '{"Alocasia macrorrhiza","Alocasia odora"}'::text[],
   '{"ru": "Крупная алоказия с огромными светло-зелёными листьями на высоких черешках; в квартире вырастает выше метра."}', 'травянистое', 2, true, true, true),
  ('Cleistocactus', 'cleistocactus-winteri', 'Cleistocactus winteri',
   '{"ru": ["Клейстокактус Винтера", "Хильдевинтера"], "en": ["Golden rat tail cactus"]}', '{"Hildewintera aureispina","Borzicactus aureispinus","Winterocereus aureispinus"}'::text[],
   '{"ru": "Кактус с длинными свисающими стеблями в золотистых колючках и лососево-оранжевыми цветками."}', 'суккулент', 1, false, false, false),
  ('Drosera', 'drosera-capensis', 'Drosera capensis',
   '{"ru": ["Росянка капская"], "en": ["Cape sundew"]}', '{}'::text[],
   '{"ru": "Хищное растение с узкими листьями в липких волосках-«росинках»: лист медленно заворачивается вокруг пойманной мошки."}', 'травянистое', 2, false, false, false),
  ('Pinguicula', 'pinguicula-moranensis', 'Pinguicula moranensis',
   '{"ru": ["Жирянка моранская"], "en": ["Mexican butterwort"]}', '{"Pinguicula caudata"}'::text[],
   '{"ru": "Мексиканская хищная розетка с липкими листьями: ловит мелких мошек, в том числе грибных комариков из соседних горшков."}', 'травянистое', 2, false, false, false),
  ('Tradescantia', 'tradescantia-sillamontana', 'Tradescantia sillamontana',
   '{"ru": ["Традесканция силламонтана", "Традесканция войлочная"], "en": ["White velvet", "Cobweb spiderwort"]}', '{"Tradescantia pexata"}'::text[],
   '{"ru": "Суккулентная традесканция с листьями в густом белом опушении и розовыми цветками летом."}', 'травянистое', 1, true, false, false),
  ('Solanum', 'solanum-lycopersicum', 'Solanum lycopersicum',
   '{"ru": ["Томат", "Помидор"], "en": ["Tomato"]}', '{"Lycopersicon esculentum"}'::text[],
   '{"ru": "Томаты на подоконнике — низкорослые сорта черри: при хорошем свете дают урожай круглый год."}', 'травянистое', 3, true, false, false),
  ('Mammillaria', 'mammillaria-hahniana', 'Mammillaria hahniana',
   '{"ru": ["Маммиллярия Гана"], "en": ["Old lady cactus"]}', '{}'::text[],
   '{"ru": "Шаровидный кактус в длинных белых волосках; весной цветёт кольцом из пурпурных цветков."}', 'суккулент', 1, false, false, false),
  ('Hoya', 'hoya-kerrii', 'Hoya kerrii',
   '{"ru": ["Хойя Керри", "Хойя «Сердечко»"], "en": ["Sweetheart hoya", "Valentine hoya"]}', '{}'::text[],
   '{"ru": "Хойя с толстыми листьями-сердечками; в продаже часто одиночный лист в горшке."}', 'лиана', 2, false, false, true),
  ('Goeppertia', 'goeppertia-crocata', 'Goeppertia crocata',
   '{"ru": ["Калатея шафрановая", "Калатея кроката"], "en": ["Eternal flame"]}', '{"Calathea crocata"}'::text[],
   '{"ru": "Калатея с тёмными волнистыми листьями, которая цветёт: над листвой поднимаются ярко-оранжевые соцветия."}', 'травянистое', 4, false, false, false),
  ('Goeppertia', 'goeppertia-warszewiczii', 'Goeppertia warszewiczii',
   '{"ru": ["Калатея Варшевича"], "en": ["Jungle velvet calathea"]}', '{"Calathea warszewiczii"}'::text[],
   '{"ru": "Бархатистые тёмно-зелёные листья со светлой «ёлочкой» по центру и бордовой изнанкой."}', 'травянистое', 4, false, false, false),
  ('Asparagus', 'asparagus-aethiopicus', 'Asparagus aethiopicus',
   '{"ru": ["Аспарагус Шпренгера", "Аспарагус густоцветковый"], "en": ["Sprenger''s asparagus", "Asparagus fern"]}', '{"Asparagus densiflorus","Asparagus sprengeri"}'::text[],
   '{"ru": "Пышные свисающие побеги с мягкой хвоей; осенью бывают красные ягоды. Неприхотлив и быстро растёт."}', 'травянистое', 1, true, true, true),
  ('Euphorbia', 'euphorbia-tirucalli', 'Euphorbia tirucalli',
   '{"ru": ["Молочай тирукалли", "Молочай «Карандашный»"], "en": ["Pencil cactus", "Firestick"]}', '{}'::text[],
   '{"ru": "Суккулентное деревце из тонких зелёных «карандашей»; у сорта «Файерстикс» побеги краснеют на солнце."}', 'суккулент', 1, true, true, false),
  ('Echinopsis', 'echinopsis-oxygona', 'Echinopsis oxygona',
   '{"ru": ["Эхинопсис остроугольный"], "en": ["Easter lily cactus"]}', '{"Echinopsis multiplex"}'::text[],
   '{"ru": "Самый «домашний» кактус: рёбристый шар с детками и огромными душистыми розовыми цветками на длинной трубке."}', 'суккулент', 1, false, false, false),
  ('Parodia', 'parodia-magnifica', 'Parodia magnifica',
   '{"ru": ["Пародия великолепная", "Нотокактус великолепный"], "en": ["Balloon cactus"]}', '{"Notocactus magnificus","Eriocactus magnificus"}'::text[],
   '{"ru": "Сизо-голубой рёбристый кактус с золотистыми колючками и жёлтыми шелковистыми цветками."}', 'суккулент', 1, false, false, false),
  ('Cereus', 'cereus-repandus', 'Cereus repandus',
   '{"ru": ["Цереус перуанский", "Цереус"], "en": ["Peruvian apple cactus"]}', '{"Cereus peruvianus","Cereus uruguayanus"}'::text[],
   '{"ru": "Столбовидный сизый кактус, который в комнате растёт до потолка; бывает уродливая скалистая форма «Монстрозус»."}', 'суккулент', 1, false, false, false),
  ('Schlumbergera', 'schlumbergera-gaertneri', 'Schlumbergera gaertneri',
   '{"ru": ["Рипсалидопсис Гартнера", "Пасхальный кактус"], "en": ["Easter cactus"]}', '{"Rhipsalidopsis gaertneri","Hatiora gaertneri"}'::text[],
   '{"ru": "Лесной кактус из плоских члеников, похожий на декабриста, но цветёт весной — звёздчатыми алыми цветками."}', 'эпифит', 2, false, false, false),
  ('Begonia', 'begonia-hiemalis', 'Begonia × hiemalis',
   '{"ru": ["Бегония элатиор", "Бегония зимняя"], "en": ["Rieger begonia", "Elatior begonia"]}', '{"Begonia × elatior"}'::text[],
   '{"ru": "Цветущая бегония с шапкой махровых цветков: красных, розовых, жёлтых, белых. Цветёт месяцами, часто зимой."}', 'травянистое', 3, true, false, false),
  ('Pteris', 'pteris-cretica', 'Pteris cretica',
   '{"ru": ["Птерис критский"], "en": ["Cretan brake fern", "Ribbon fern"]}', '{}'::text[],
   '{"ru": "Нетребовательный папоротник с перистыми вайями; у сорта «Альболинеата» по центру белая полоса."}', 'папоротник', 2, false, false, true),
  ('Persea', 'persea-americana', 'Persea americana',
   '{"ru": ["Авокадо"], "en": ["Avocado"]}', '{}'::text[],
   '{"ru": "Деревце из косточки авокадо: быстро растёт и радует крупными листьями. Плодов в квартире обычно не бывает."}', 'дерево', 2, true, false, false),
  ('Capsicum', 'capsicum-annuum', 'Capsicum annuum',
   '{"ru": ["Перец декоративный", "Перец острый"], "en": ["Chili pepper", "Ornamental pepper"]}', '{}'::text[],
   '{"ru": "Компактный перец с яркими плодами: красными, жёлтыми, фиолетовыми. Острые сорта съедобны."}', 'кустарник', 2, true, false, false),
  ('Peperomia', 'peperomia-polybotrya', 'Peperomia polybotrya',
   '{"ru": ["Пеперомия многоколосовая", "Пеперомия «Капля дождя»"], "en": ["Raindrop peperomia", "Coin-leaf peperomia"]}', '{}'::text[],
   '{"ru": "Пеперомия с глянцевыми мясистыми листьями в форме капли на прямых стеблях."}', 'травянистое', 1, false, false, true)
) as s(genus, slug, latin_name, common_names, synonyms, description, plant_type,
       difficulty, toxic_pets, toxic_humans, air_purifying)
join public.genera g on g.latin_name = s.genus
on conflict do nothing;

insert into public.care_profiles
  (species_id, light, water_interval_summer, water_interval_winter, soil_dryness_before_watering,
   humidity_min_pct, temp_min_c, temp_max_c, fertilize_interval_days, fertilize_months,
   repot_every_years, propagation, tips, soil_mix_slug, soil_note)
select sp.id, c.light, c.summer, c.winter, c.dryness::jsonb, c.humidity, c.tmin, c.tmax,
       c.fert_days, c.fert_months, c.repot, c.propagation, c.tips::jsonb, c.soil, c.soil_note::jsonb
from (values
  ('anthurium-scherzerianum', 'bright_indirect', 5, 10, '{"ru": "верхние 2 см"}', 60, 16, 26, 14,
   '{"3","4","5","6","7","8","9"}'::smallint[], 2, '{"деление","семена"}'::text[],
   '{"ru": ["Для цветения зимой 1,5–2 месяца держите при +15–16 °C и поливайте реже", "Любит высокую влажность — ставьте на поддон с мокрым керамзитом"]}', 'aroid_chunky', null),
  ('alocasia-longiloba', 'bright_indirect', 4, 8, '{"ru": "верхние 2 см"}', 60, 18, 28, 14,
   '{"4","5","6","7","8","9"}'::smallint[], 2, '{"деление","клубеньки"}'::text[],
   '{"ru": ["Зимой может сбросить листья и уйти в покой — полив сократите, клубень не выбрасывайте", "Капризна к сквознякам и холодному подоконнику"]}', 'aroid_moist', null),
  ('alocasia-wentii', 'bright_indirect', 4, 8, '{"ru": "верхние 2–3 см"}', 50, 15, 28, 14,
   '{"4","5","6","7","8","9"}'::smallint[], 2, '{"деление","клубеньки"}'::text[],
   '{"ru": ["Выносливее других алоказий — хороший первый вид", "Капли на кончиках листьев утром — нормально: так уходит лишняя вода"]}', 'aroid_moist', null),
  ('alocasia-macrorrhizos', 'bright_indirect', 3, 7, '{"ru": "верхние 2–3 см"}', 50, 15, 30, 14,
   '{"4","5","6","7","8","9"}'::smallint[], 1, '{"деление","клубеньки"}'::text[],
   '{"ru": ["Растёт быстро и много пьёт летом", "Нужен большой устойчивый горшок"]}', 'aroid_moist', null),
  ('cleistocactus-winteri', 'direct', 7, 30, '{"ru": "полностью"}', 30, 5, 30, 30,
   '{"5","6","7","8"}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Свисающие стебли красивы в подвесном кашпо", "Для цветения нужна прохладная сухая зимовка +5–10 °C"]}', 'cactus_succulent', null),
  ('drosera-capensis', 'direct', 1, 2, '{"ru": "не пересыхает"}', 50, 7, 30, null::smallint,
   '{}'::smallint[], 2, '{"семена","черенки листьев","деление"}'::text[],
   '{"ru": ["Поливайте только дистиллированной или осмосной водой — снизу, через поддон", "Блестящие капли на листьях — признак здоровья; без яркого света они исчезают"]}', 'carnivorous', null),
  ('pinguicula-moranensis', 'bright_indirect', 3, 10, '{"ru": "слегка подсыхает"}', 40, 10, 30, null::smallint,
   '{}'::smallint[], 2, '{"черенки листьев","деление"}'::text[],
   '{"ru": ["Зимой образует мелкую розетку покоя — поливайте реже", "Вода только дистиллированная или осмосная"]}', 'carnivorous', null),
  ('tradescantia-sillamontana', 'direct', 7, 14, '{"ru": "верхние 2–3 см"}', 30, 10, 30, 30,
   '{"4","5","6","7","8"}'::smallint[], 2, '{"черенки","деление"}'::text[],
   '{"ru": ["Опушённые листья не опрыскивайте", "Чем больше солнца, тем плотнее и белее растение"]}', 'universal', '{"ru": "Добавьте 20–30% песка или пемзы: она не любит сырости."}'),
  ('solanum-lycopersicum', 'direct', 2, 3, '{"ru": "верхний слой"}', 40, 16, 30, 10,
   '{"3","4","5","6","7","8","9"}'::smallint[], null::smallint, '{"семена","черенки (пасынки)"}'::text[],
   '{"ru": ["Выбирайте низкорослые сорта черри: «Балконное чудо», «Пиноккио», «Микро Том»", "Зимой без досветки плоды не завяжутся", "Помогайте опылению — слегка встряхивайте цветущие кисти"]}', 'flowering', null),
  ('mammillaria-hahniana', 'direct', 10, 30, '{"ru": "полностью"}', 30, 8, 30, 30,
   '{"5","6","7","8"}'::smallint[], 2, '{"семена","детки"}'::text[],
   '{"ru": ["Кольцо цветков появляется после прохладной сухой зимовки +8–12 °C", "Не мочите волоски при поливе"]}', 'cactus_succulent', null),
  ('hoya-kerrii', 'bright_indirect', 10, 20, '{"ru": "полностью"}', 40, 15, 30, 21,
   '{"4","5","6","7","8","9"}'::smallint[], 3, '{"черенки"}'::text[],
   '{"ru": ["Одиночный лист без узла пустит корни, но стебель так и не вырастет", "Не срезайте старые цветоносы — на них цветёт снова"]}', 'epiphytic_vine', null),
  ('goeppertia-crocata', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 27, 14,
   '{"4","5","6","7","8","9"}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Для цветения зимой нужны короткий день (около 10 часов света) и высокая влажность", "Поливайте мягкой отстоянной водой"]}', 'tropical_moist', null),
  ('goeppertia-warszewiczii', 'medium', 4, 7, '{"ru": "верхний слой"}', 60, 18, 27, 14,
   '{"4","5","6","7","8","9"}'::smallint[], 1, '{"деление"}'::text[],
   '{"ru": ["Бархатистые листья не опрыскивайте — увлажняйте воздух рядом", "Сохнущие края — сухой воздух или жёсткая вода"]}', 'tropical_moist', null),
  ('asparagus-aethiopicus', 'bright_indirect', 4, 10, '{"ru": "верхние 2 см"}', 40, 10, 28, 14,
   '{"4","5","6","7","8","9"}'::smallint[], 1, '{"деление","семена"}'::text[],
   '{"ru": ["Мощные корневые клубни быстро заполняют горшок — пересаживайте каждый год", "Ягоды ядовиты"]}', 'universal', null),
  ('euphorbia-tirucalli', 'direct', 10, 30, '{"ru": "полностью"}', 30, 10, 32, 30,
   '{"5","6","7","8"}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Млечный сок едкий и опасен для глаз — работайте в перчатках и очках", "Черенки перед посадкой подсушите 1–2 дня"]}', 'cactus_succulent', null),
  ('echinopsis-oxygona', 'direct', 7, 30, '{"ru": "полностью"}', 30, 6, 32, 30,
   '{"5","6","7","8"}'::smallint[], 2, '{"детки","семена"}'::text[],
   '{"ru": ["Без прохладной зимовки +6–10 °C не цветёт", "Лишние детки удаляйте — они отнимают силы у цветения"]}', 'cactus_succulent', null),
  ('parodia-magnifica', 'bright_indirect', 7, 30, '{"ru": "полностью"}', 30, 8, 30, 30,
   '{"5","6","7","8"}'::smallint[], 2, '{"детки","семена"}'::text[],
   '{"ru": ["Летом притеняйте от полуденного солнца", "Зимой прохладно и почти сухо"]}', 'cactus_succulent', null),
  ('cereus-repandus', 'direct', 7, 30, '{"ru": "полностью"}', 30, 8, 32, 30,
   '{"5","6","7","8"}'::smallint[], 2, '{"черенки","семена"}'::text[],
   '{"ru": ["Тяжёлый и высокий — нужен устойчивый керамический горшок", "Поворачивайте к свету, иначе растёт с наклоном"]}', 'cactus_succulent', null),
  ('schlumbergera-gaertneri', 'bright_indirect', 5, 12, '{"ru": "верхние 2 см"}', 50, 10, 26, 21,
   '{"3","4","5","6","7","8"}'::smallint[], 2, '{"черенки"}'::text[],
   '{"ru": ["Для бутонов нужна прохлада +10–15 °C с ноября по февраль", "С бутонами горшок не переставляйте — сбросит"]}', 'bromeliad_epiphyte', null),
  ('begonia-hiemalis', 'bright_indirect', 4, 7, '{"ru": "верхний слой"}', 50, 15, 24, 14,
   '{"1","2","3","4","5","6","7","8","9","10","11","12"}'::smallint[], null::smallint, '{"черенки"}'::text[],
   '{"ru": ["Поливайте по краю горшка, не заливая стебли — склонна к гнили", "После цветения обрежьте и дайте отдохнуть или обновите черенками"]}', 'flowering', null),
  ('pteris-cretica', 'medium', 3, 7, '{"ru": "не пересыхает"}', 50, 12, 26, 21,
   '{"4","5","6","7","8","9"}'::smallint[], 2, '{"деление","споры"}'::text[],
   '{"ru": ["Не выносит пересыхания кома", "Засохшие вайи срезайте у основания"]}', 'fern', null),
  ('persea-americana', 'bright_indirect', 5, 10, '{"ru": "верхние 2–3 см"}', 50, 12, 28, 21,
   '{"4","5","6","7","8","9"}'::smallint[], 1, '{"семена (косточка)"}'::text[],
   '{"ru": ["Прищипывайте верхушку на высоте 30–40 см — станет ветвиться", "Листья и косточка ядовиты для кошек, собак и птиц"]}', 'universal', null),
  ('capsicum-annuum', 'direct', 3, 5, '{"ru": "верхний слой"}', 40, 15, 30, 14,
   '{"3","4","5","6","7","8","9","10"}'::smallint[], null::smallint, '{"семена"}'::text[],
   '{"ru": ["Для завязей нужно солнце: зимой — досветка", "После сбора плодов можно обрезать — куст плодоносит 2–3 года", "Не трите глаза после работы с острыми плодами"]}', 'flowering', null),
  ('peperomia-polybotrya', 'bright_indirect', 8, 14, '{"ru": "почти полностью"}', 40, 15, 28, 30,
   '{"4","5","6","7","8","9"}'::smallint[], 2, '{"черенки","листовые черенки"}'::text[],
   '{"ru": ["Запасает воду в листьях — лучше недолить, чем перелить", "Любит тесный горшок"]}', 'epiphytic_vine', null)
) as c(slug, light, summer, winter, dryness, humidity, tmin, tmax, fert_days, fert_months,
       repot, propagation, tips, soil, soil_note)
join public.species sp on sp.slug = c.slug
on conflict (species_id) do nothing;

