-- Фото для видов, добавленных в kb_species_part5 (Wikimedia Commons, свободные лицензии).
update public.species s
   set image_url = v.url, image_credit = v.credit, image_license = v.license, image_source_url = v.src
  from (values
  ('alocasia-longiloba', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Alocasia_watsoniana_3zz.jpg/960px-Alocasia_watsoniana_3zz.jpg', 'Photo by David J. Stang', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Alocasia_watsoniana_3zz.jpg'),
  ('alocasia-macrorrhizos', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Alocasia_macrorrhizos1.jpg/960px-Alocasia_macrorrhizos1.jpg', 'KENPEI', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Alocasia_macrorrhizos1.jpg'),
  ('anthurium-scherzerianum', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Anthurium_scherzerianum_2.jpg/960px-Anthurium_scherzerianum_2.jpg', 'JJ Harrison (https://www.jjharrison.com.au/)', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Anthurium_scherzerianum_2.jpg'),
  ('asparagus-aethiopicus', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Asparagus_densiflorus_%27Myersii%27.jpg/960px-Asparagus_densiflorus_%27Myersii%27.jpg', 'Traumrune', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Asparagus_densiflorus_%27Myersii%27.jpg'),
  ('capsicum-annuum', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d2/Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg/960px-Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg', 'Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg'),
  ('cereus-repandus', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Cereus_repandus_in_Aruba_-_on_the_way_back_from_Altovista_chapel_%282896840490%29.jpg/960px-Cereus_repandus_in_Aruba_-_on_the_way_back_from_Altovista_chapel_%282896840490%29.jpg', 'Serge Melki from Indianapolis, USA', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Cereus_repandus_in_Aruba_-_on_the_way_back_from_Altovista_chapel_(2896840490).jpg'),
  ('cleistocactus-winteri', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Cleistocactus_winteri_HabitusFlower_BotGard0906a.jpg/960px-Cleistocactus_winteri_HabitusFlower_BotGard0906a.jpg', null, 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Cleistocactus_winteri_HabitusFlower_BotGard0906a.jpg'),
  ('drosera-capensis', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Drosera_capensis_bend.JPG', 'NoahElhardt', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Drosera_capensis_bend.JPG'),
  ('echinopsis-oxygona', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Echinopsis_oxygona_%285%29.jpg/960px-Echinopsis_oxygona_%285%29.jpg', 'pollobarca2', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Echinopsis_oxygona_(5).jpg'),
  ('euphorbia-tirucalli', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Pencil_Tree_%28Euphorbia_tirucalli%29.jpg/960px-Pencil_Tree_%28Euphorbia_tirucalli%29.jpg', 'Mokkie', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Pencil_Tree_(Euphorbia_tirucalli).jpg'),
  ('goeppertia-crocata', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Calathea_crocata_2.jpg/960px-Calathea_crocata_2.jpg', 'Assianir', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Calathea_crocata_2.jpg'),
  ('goeppertia-warszewiczii', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Goeppertia_warszewiczii_5.jpg/960px-Goeppertia_warszewiczii_5.jpg', 'Colin Gamache', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Goeppertia_warszewiczii_5.jpg'),
  ('hoya-kerrii', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hoya-kerrii_flowers_op.jpg', 'Hobbykafe', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Hoya-kerrii_flowers_op.jpg'),
  ('mammillaria-hahniana', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/%28MHNT%29_Mammillaria_hahniana_-_Jardin_Botanique_Henri_GAUSSEN.jpg/960px-%28MHNT%29_Mammillaria_hahniana_-_Jardin_Botanique_Henri_GAUSSEN.jpg', 'Didier Descouens', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:(MHNT)_Mammillaria_hahniana_-_Jardin_Botanique_Henri_GAUSSEN.jpg'),
  ('parodia-magnifica', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Eriocactus_magnificus_JPG.jpg/960px-Eriocactus_magnificus_JPG.jpg', 'Jean-Pol GRANDMONT', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Eriocactus_magnificus_JPG.jpg'),
  ('peperomia-polybotrya', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Coin_Leaf_Peperomia_%28Peperomia_polybotrya_%27Jayde%27%29_2.jpg/960px-Coin_Leaf_Peperomia_%28Peperomia_polybotrya_%27Jayde%27%29_2.jpg', 'Mokkie', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Coin_Leaf_Peperomia_(Peperomia_polybotrya_%27Jayde%27)_2.jpg'),
  ('persea-americana', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Persea_americana_fruit_2.JPG/960px-Persea_americana_fruit_2.JPG', 'B.navez', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Persea_americana_fruit_2.JPG'),
  ('pinguicula-moranensis', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Pinguicula_moranensis.jpg/960px-Pinguicula_moranensis.jpg', 'Noah Elhardt', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Pinguicula_moranensis.jpg'),
  ('pteris-cretica', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Starr_030419-0010_Pteris_cretica.jpg/960px-Starr_030419-0010_Pteris_cretica.jpg', 'Forest & Kim Starr', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Starr_030419-0010_Pteris_cretica.jpg'),
  ('schlumbergera-gaertneri', 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Hatiora_gaertneri.jpg', null, 'Public domain', 'https://commons.wikimedia.org/wiki/File:Hatiora_gaertneri.jpg'),
  ('solanum-lycopersicum', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/960px-Tomato_je.jpg', 'Softeis', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Tomato_je.jpg'),
  ('tradescantia-sillamontana', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/04/Tradescantia_sillamontana.jpg/960px-Tradescantia_sillamontana.jpg', 'Michael Wolf', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Tradescantia_sillamontana.jpg')) as v(slug, url, credit, license, src)
 where s.slug = v.slug and s.image_url is null;
