-- Фотографии видов в базе знаний: главное изображение статьи Википедии (только свободные
-- лицензии) или, если его нет, снимок вида с Wikimedia Commons. Картинки не копируем к себе:
-- сайт показывает миниатюры Commons (960 px; если оригинал меньше — сам оригинал) и обязательно
-- подписывает автора и лицензию со ссылкой на страницу файла — этого требуют CC BY / CC BY-SA.

alter table public.species
  add column if not exists image_credit     text,
  add column if not exists image_license    text,
  add column if not exists image_source_url text;

comment on column public.species.image_url is 'Фото вида (миниатюра Wikimedia Commons).';
comment on column public.species.image_credit is 'Автор фото — подписывается рядом с картинкой.';
comment on column public.species.image_license is 'Лицензия фото, например CC BY-SA 4.0.';
comment on column public.species.image_source_url is 'Страница файла на Commons (автор, лицензия, оригинал).';

update public.species s
   set image_url        = case v.kind
                            when 't' then 'https://thumb.wikimedia.org/wikipedia/commons/thumb/' || v.dir || '/' || v.file || '/960px-' || v.file
                            when 'u' then 'https://upload.wikimedia.org/wikipedia/commons/' || v.dir || '/' || v.file
                            else 'https://' || v.dir  -- имя файла в адресе закодировано иначе, чем в названии
                          end,
       image_source_url = 'https://commons.wikimedia.org/wiki/File:' || v.file,
       image_license    = v.license,
       image_credit     = v.credit
  from (values
  ('acalypha-hispida', 't', '7/7b', 'Acalypha_Hispida_DS.jpg', 'CC BY-SA 3.0', 'Augustus Binu/ facebook'),
  ('adenium-obesum', 't', '4/4a', 'Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg', 'CC BY-SA 4.0', 'Timothy A. Gonsalves'),
  ('adiantum-raddianum', 't', '4/45', 'Starr_030807-0143_Adiantum_raddianum.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('adromischus-cristatus', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/%28MHNT%29_Adromischus_cristatus.jpg/960px-%28MHNT%29_Adromischus_cristatus.jpg', '(MHNT)_Adromischus_cristatus.jpg', 'CC BY-SA 4.0', 'Didier Descouens'),
  ('aechmea-fasciata', 't', '2/23', 'Aechmea_fasciata2.jpg', 'CC BY-SA 2.0', 'Paul & Aline Burland'),
  ('aeonium-arboreum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/2/28/Madeira%2C_Palheiro_Gardens_-_Aeonium_arboreum_%28Marokko%29_IMG_2310.JPG/960px-Madeira%2C_Palheiro_Gardens_-_Aeonium_arboreum_%28Marokko%29_IMG_2310.JPG', 'Madeira,_Palheiro_Gardens_-_Aeonium_arboreum_(Marokko)_IMG_2310.JPG', 'CC BY-SA 3.0', 'Hedwig Storch'),
  ('aeschynanthus-radicans', 't', '5/52', 'Aeschynanthus_radicans.jpg', 'CC BY-SA 3.0', 'Michael Wolf'),
  ('agave-attenuata', 't', '0/03', 'Agave_attenuata_001.JPG', 'CC BY-SA 3.0', 'H. Zell'),
  ('aglaonema-commutatum', 't', 'c/c7', 'Aglaonema_commutatum_kz1.jpg', 'CC BY-SA 4.0', 'Krzysztof Ziarnek, Kenraiz'),
  ('alocasia-amazonica', 't', 'c/cf', 'Alocasia_x_amazonica_a1.jpg', 'CC BY-SA 4.0', 'Jerzy Opioła'),
  ('alocasia-baginda', 't', '4/47', 'PXL_20220721_201128151.jpg', 'CC BY-SA 4.0', 'Cs california'),
  ('alocasia-cuprea', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Alocasia_cuprea_-_Victoriahuset%2C_Bergianska_tr%C3%A4dg%C3%A5rden_-_Stockholm%2C_Sweden_-_DSC00282.JPG/960px-Alocasia_cuprea_-_Victoriahuset%2C_Bergianska_tr%C3%A4dg%C3%A5rden_-_Stockholm%2C_Sweden_-_DSC00282.JPG', 'Alocasia_cuprea_-_Victoriahuset,_Bergianska_tr%C3%A4dg%C3%A5rden_-_Stockholm,_Sweden_-_DSC00282.JPG', 'CC0', 'Daderot'),
  ('alocasia-micholitziana', 't', '7/72', 'Alocasia_micholitziana.JPG', 'CC0', 'Dinkum'),
  ('alocasia-reginula', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Alocasia_reginula_%28Philippines%29_01.jpg/960px-Alocasia_reginula_%28Philippines%29_01.jpg', 'Alocasia_reginula_(Philippines)_01.jpg', 'CC0', 'Obsidian Soul'),
  ('alocasia-zebrina', 't', '1/17', 'Alocasia_zebrina_4zz.jpg', 'CC BY-SA 4.0', 'David J. Stang'),
  ('aloe-vera', 't', '4/4b', 'Aloe_vera_flower_inset.png', 'CC BY-SA 3.0', 'Collage by en:User:MidgleyDJ, original images from…'),
  ('anacampseros-rufescens', 'u', '2/2e', 'Anacampseros_rufescens1_ies.jpg', 'CC BY-SA 3.0', 'Frank Vincentz'),
  ('ananas-comosus', 't', '7/74', '%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg', 'CC BY 3.0', 'Suniltg at Malayalam Wikipedia'),
  ('anthurium-andraeanum', 't', '8/8b', 'AnthuriumAndraenum.jpg', 'CC BY 2.5', 'Fanghong'),
  ('anthurium-clarinervium', 't', '6/65', 'Anthurium_clarinervium.jpg', 'CC BY-SA 4.0', 'Nadiatalent'),
  ('anthurium-hookeri', 'u', '9/95', 'Anthurium_hookeri.JPG', 'CC BY 3.0', 'Oeropium'),
  ('aphelandra-squarrosa', 't', 'e/e5', 'AphelandraSquarrosaWPC_edit.jpg', 'CC0', 'WayneRay'),
  ('araucaria-heterophylla', 't', '1/10', 'Norfolk-Island-Pines.jpg', 'CC BY 2.0', 'thinboyfatter'),
  ('ardisia-crenata', 't', '5/51', 'Ardisia_crenata_342476445.jpg', 'CC BY 4.0', 'Alex Abair'),
  ('aristaloe-aristata', 't', 'e/e6', 'AloeAristata.jpg', 'Public domain', 'Chhe'),
  ('asparagus-setaceus', 't', 'e/e8', 'Asparagus_setaceus_Leaves_2760px.jpg', 'CC BY-SA 3.0', 'Derek Ramsey (Ram-Man)'),
  ('aspidistra-elatior', 't', 'f/fc', 'Aspidistra_elatior1.jpg', 'CC BY-SA 3.0', 'KENPEI'),
  ('asplenium-nidus', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg/960px-Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg', 'Asplenium_nidus_(Bukidnon,_Philippines)_02.jpg', 'CC0', 'Obsidian Soul'),
  ('astrophytum-myriostigma', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Astrophytum_myriostigma%2C_Jard%C3%ADn_Bot%C3%A1nico_de_M%C3%BAnich%2C_Alemania%2C_2013-01-27%2C_DD_01.JPG/960px-Astrophytum_myriostigma%2C_Jard%C3%ADn_Bot%C3%A1nico_de_M%C3%BAnich%2C_Alemania%2C_2013-01-27%2C_DD_01.JPG', 'Astrophytum_myriostigma,_Jard%C3%ADn_Bot%C3%A1nico_de_M%C3%BAnich,_Alemania,_2013-01-27,_DD_01.JPG', 'CC BY-SA 3.0', 'Diego Delso'),
  ('aucuba-japonica', 't', 'c/c6', 'Aucuba_japonica_Gold_Dust_NBG_LR.jpg', 'CC BY-SA 4.0', 'PumpkinSky'),
  ('beaucarnea-recurvata', 'x', 'upload.wikimedia.org/wikipedia/commons/7/7e/Beaucarnea_recurvata%2C_Ocampo%2C_Tamaulipas%2C_Mexico_1.jpg', 'Beaucarnea_recurvata,_Ocampo,_Tamaulipas,_Mexico_1.jpg', 'CC BY-SA 4.0', 'juancruzado'),
  ('begonia-maculata', 'u', 'd/df', 'Begonia_maculata3073316230.jpg', 'CC BY 2.0', 'Cliff from I now live in Arlington, VA (Outside…'),
  ('begonia-rex', 't', 'b/b3', 'Begonia_rex_5zz.jpg', 'CC BY-SA 4.0', 'David J. Stang'),
  ('blechnum-gibbum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/4/41/Blechnum_gibbum_%28Washington_DC%29.jpg/960px-Blechnum_gibbum_%28Washington_DC%29.jpg', 'Blechnum_gibbum_(Washington_DC).jpg', 'Public domain', 'Daderot'),
  ('bougainvillea-glabra', 't', 'b/b9', 'Bugenwilla.D%C5%82ugo_kwitnaca_roslina.jpg', 'CC BY-SA 4.0', 'Zbigniew Niepokój'),
  ('brighamia-insignis', 't', '3/30', 'Brighamia_insignis_-_general_view.JPG', 'CC BY-SA 3.0', 'Daderot'),
  ('browallia-speciosa', 't', '8/8c', 'IMG_7246-Browallia_speciosa.jpg', 'CC BY 3.0', 'C T Johansson'),
  ('caladium-bicolor', 't', 'f/f8', 'Caladium_bicolor_2.jpg', 'CC BY-SA 4.0', 'Nativeplants garden'),
  ('calceolaria-herbeohybrida', 't', '5/55', 'CalceolariaHerbeohybrida2.jpg', 'CC BY-SA 3.0', null),
  ('callisia-repens', 't', '7/7c', 'Callisia_repens_starr.jpg', 'CC BY 2.0', 'Forest and Kim Starr'),
  ('camellia-japonica', 't', 'e/e9', 'Camellia_japonica_NBG.jpg', 'CC BY-SA 3.0', 'PumpkinSky'),
  ('carissa-macrocarpa', 't', '1/17', 'Starr_010820-0009_Carissa_macrocarpa.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('cattleya-hybrida', 't', 'c/c1', 'Cattleya_labiata_Orchi_1013.jpg', 'CC BY-SA 3.0', 'Orchi'),
  ('ceropegia-woodii', 'u', '5/55', 'Ceropegia_linearis_subsp_woodii.jpg', 'CC BY-SA 2.5', 'Photo: Dr. David Midgley'),
  ('chamaedorea-elegans', 't', '6/64', 'Chamaedorea_elegans_Mart.JPG', 'CC BY-SA 3.0', 'Bachelot Pierre J-P'),
  ('chamaerops-humilis', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Chamaerops_humilis_%28Zingaro%29015.jpg/960px-Chamaerops_humilis_%28Zingaro%29015.jpg', 'Chamaerops_humilis_(Zingaro)015.jpg', 'CC BY-SA 2.5', 'tato grasso'),
  ('chlorophytum-comosum', 't', 'b/b1', 'Hierbabuena_0611_Revised.jpg', 'Public domain', 'Hierbabuena_0611.JPG: Dtarazona derivative work: Peter…'),
  ('chlorophytum-orchidastrum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Chlorophytum_orchidastrum%2C_University_of_Helsinki_Botanical_Garden%2C_Finland_-_20080821.jpg/960px-Chlorophytum_orchidastrum%2C_University_of_Helsinki_Botanical_Garden%2C_Finland_-_20080821.jpg', 'Chlorophytum_orchidastrum,_University_of_Helsinki_Botanical_Garden,_Finland_-_20080821.jpg', 'CC BY-SA 4.0', 'Retama'),
  ('chrysanthemum-morifolium', 't', '8/84', 'Chrysanthemum.JPG', 'CC BY-SA 3.0', 'Aruna at Malayalam Wikipedia'),
  ('cissus-rhombifolia', 't', '8/8b', 'Cissus_alata_Leaves.JPG', 'GFDL 1.2', 'Derek Ramsey (Ram-Man)'),
  ('citrus-japonica', 't', 'f/f4', 'Citrus_japonica.jpg', 'CC BY 2.0', 'Phuong Tran'),
  ('citrus-limon', 't', 'e/e4', 'P1030323.JPG', 'CC BY-SA 4.0', 'Elena Chochkova'),
  ('citrus-microcarpa', 't', 'b/b6', 'Citrus_%C3%97_microcarpa_kz1.jpg', 'CC BY-SA 4.0', 'Krzysztof Ziarnek, Kenraiz'),
  ('citrus-reticulata', 't', '1/10', 'Citrus_reticulata_April_2013_Nordbaden.JPG', 'CC BY-SA 3.0', '4028mdk09'),
  ('citrus-sinensis', 'u', 'b/b0', 'OrangeBloss_wb.jpg', 'CC BY-SA 3.0', 'Ellen Levy Finch (Elf)'),
  ('clerodendrum-thomsoniae', 'u', 'e/e2', 'Clerodendron_thomsoniae1.jpg', 'CC BY-SA 3.0', 'Kurt Stüber'),
  ('clivia-miniata', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Clivia_miniata%2C_blomme_en_vrugte%2C_Manie_van_der_Schijff_BT%2C_a.jpg/960px-Clivia_miniata%2C_blomme_en_vrugte%2C_Manie_van_der_Schijff_BT%2C_a.jpg', 'Clivia_miniata,_blomme_en_vrugte,_Manie_van_der_Schijff_BT,_a.jpg', 'CC BY-SA 3.0', 'JMK'),
  ('clusia-rosea', 't', '2/2e', 'Starr_010330-0602_Clusia_rosea.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('cocos-nucifera', 't', '2/2c', 'Starr_080610-8073_Cocos_nucifera.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('codiaeum-variegatum', 't', 'b/bf', 'Colpfl05.jpg', 'CC BY-SA 3.0', 'Louise Wolff --darina 23:22, 6 May 2005 (UTC)'),
  ('coffea-arabica', 't', 'c/c7', 'Coffee_Flowers.JPG', 'CC BY-SA 3.0', 'Marcelo Corrêa'),
  ('coleus-scutellarioides', 't', '1/1d', 'Plectranthus_scutellarioides_-_El_Yunque_nat_park_PR_IMG_2120.JPG', 'CC BY-SA 4.0', 'Bjoertvedt'),
  ('columnea-gloriosa', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Columnea_gloriosa_%2849470911201%29.jpg/960px-Columnea_gloriosa_%2849470911201%29.jpg', 'Columnea_gloriosa_(49470911201).jpg', 'CC BY 2.0', 'geoff mckay from Palmerston North, New Zealand'),
  ('cordyline-fruticosa', 'x', 'upload.wikimedia.org/wikipedia/commons/2/2d/Cordyline_fruticosa_%2820262433874%29.jpg', 'Cordyline_fruticosa_(20262433874).jpg', 'CC BY 2.0', 'Dick Culbert from Gibsons, B.C., Canada'),
  ('corokia-cotoneaster', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Corokia_cotoneaster%2C_Tallinn_Botanic_Garden.jpg/960px-Corokia_cotoneaster%2C_Tallinn_Botanic_Garden.jpg', 'Corokia_cotoneaster,_Tallinn_Botanic_Garden.jpg', 'CC BY 4.0', 'Shuvaev'),
  ('cotyledon-orbiculata', 't', '9/90', 'Cotyledon_orbiculata_-_pigs_ear_-_Cape_Point_-_South_Africa_2.JPG', 'Public domain', 'Abu Shawka'),
  ('crassula-muscosa', 't', '5/5e', 'Crassula_muscosa_Grubosz_2006-05-03_01.jpg', 'CC BY 2.5', 'Agnieszka Kwiecień (Nova)'),
  ('crassula-ovata', 'u', '5/5a', 'Crassula_ovata_700.jpg', 'CC BY-SA 3.0', 'sannse'),
  ('crassula-perforata', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Starr-110218-1569-Crassula_perforata-flowering_habit-Ulana_St_Makawao-Maui_%2824449889633%29.jpg/960px-Starr-110218-1569-Crassula_perforata-flowering_habit-Ulana_St_Makawao-Maui_%2824449889633%29.jpg', 'Starr-110218-1569-Crassula_perforata-flowering_habit-Ulana_St_Makawao-Maui_(24449889633).jpg', 'CC BY 3.0 us', 'Forest and Kim Starr'),
  ('crossandra-infundibuliformis', 't', 'b/b9', 'Crossandra_infundibuliformis_kanakambaram_Madhurawada_Visakhapatnam.JPG', 'CC BY-SA 3.0', 'Adityamadhav83'),
  ('cryptanthus-bivittatus', 't', 'd/d1', 'CryptanthusBivittatus.jpg', 'Public domain', 'Chhe'),
  ('ctenanthe-burle-marxii', 't', '7/7d', 'Ctenanthe_burle-marxii.jpg', 'CC BY-SA 2.0 de', 'Benutzer:Callipides'),
  ('cupressus-macrocarpa', 'u', 'd/df', 'Lone_cypress_in_17-mile-drive.jpg', 'CC BY-SA 3.0', null),
  ('curio-rowleyanus', 't', 'f/fd', 'Senecio_rowleyanus_leaves.jpg', 'CC BY 2.0', 'Flickr user Forest and Kim Starr'),
  ('cycas-revoluta', 'u', '3/3b', 'Cycas_inflorescence.jpg', 'CC BY-SA 3.0', null),
  ('cyclamen-persicum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Yagur_%E2%80%93_Nesher%2C_the_Green_Path_%E2%80%93_Mount_Carmel_016.JPG/960px-Yagur_%E2%80%93_Nesher%2C_the_Green_Path_%E2%80%93_Mount_Carmel_016.JPG', 'Yagur_%E2%80%93_Nesher,_the_Green_Path_%E2%80%93_Mount_Carmel_016.JPG', 'CC BY-SA 3.0', 'Hanay'),
  ('cymbidium-hybridum', 't', 'b/be', 'Cymbidium_iridioides-1-bsi-yercaud-salem-India.jpg', 'CC BY-SA 4.0', 'Yercaud-elango'),
  ('davallia-fejeensis', 't', '6/6d', 'DavalliaFejeensis.jpg', 'Public domain', 'Chhe'),
  ('dendrobium-nobile', 'u', 'b/bb', 'Dendrobium_nobile_-_flower_view_01.jpg', 'CC BY-SA 4.0', 'Fan Wen'),
  ('dieffenbachia-seguine', 't', 'e/e0', 'Starr_061212-2331_Dieffenbachia_seguine.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('dionaea-muscipula', 't', '3/37', 'Venus_Flytrap_showing_trigger_hairs.jpg', 'CC BY-SA 2.5', 'Noah Elhardt'),
  ('dracaena-angolensis', 't', 'c/c8', 'Sansevieria_cylindrica_flowers_7.jpg', 'CC BY-SA 3.0', 'Mokkie'),
  ('dracaena-fragrans', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Dracaena_fragrans_%282%29.jpg/960px-Dracaena_fragrans_%282%29.jpg', 'Dracaena_fragrans_(2).jpg', 'CC BY 2.0', 'rojypala'),
  ('dracaena-marginata', 't', '6/61', 'Dracaena_reflexa.JPG', 'CC BY-SA 3.0', 'B.navez'),
  ('dracaena-reflexa', 't', '6/61', 'Dracaena_reflexa.JPG', 'CC BY-SA 3.0', 'B.navez'),
  ('dracaena-sanderiana', 't', 'e/e2', 'Dracaena_sanderiana_2.jpg', 'CC BY-SA 4.0', 'Cataleirxs'),
  ('dracaena-trifasciata', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/960px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg', 'Snake_Plant_(Sansevieria_trifasciata_%27Laurentii%27).jpg', 'CC BY-SA 3.0', 'Mokkie'),
  ('dypsis-lutescens', 't', '2/22', '%E6%95%A3%E5%B0%BE%E8%91%B5Dypsis_lutescens_20210511145013_05.jpg', 'CC BY-SA 4.0', 'Ping an Chang'),
  ('echeveria-elegans', 't', '5/5d', 'Echeveria_elegans_-_1.png', 'CC BY-SA 4.0', 'EriaWei'),
  ('ehretia-microphylla', 't', 'e/e7', 'Starr_010425-0048_Carmona_retusa.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('epiphyllum-oxypetalum', 't', '6/6e', 'Epiphyllum_oxypetalum_flower.JPG', 'CC BY-SA 3.0', null),
  ('epipremnum-aureum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg/960px-Money_Plant_%28Epipremnum_aureum%29_4.jpg', 'Money_Plant_(Epipremnum_aureum)_4.jpg', 'CC BY-SA 3.0', 'Mokkie'),
  ('epipremnum-pinnatum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Wild_Epipremnum_pinnatum_%28tibatib%29_-_Misamis_Oriental%2C_Philippines_04.jpg/960px-Wild_Epipremnum_pinnatum_%28tibatib%29_-_Misamis_Oriental%2C_Philippines_04.jpg', 'Wild_Epipremnum_pinnatum_(tibatib)_-_Misamis_Oriental,_Philippines_04.jpg', 'CC0', 'Obsidian Soul'),
  ('episcia-cupreata', 'x', 'upload.wikimedia.org/wikipedia/commons/8/80/Episcia_cupreata_%289631125202%29.jpg', 'Episcia_cupreata_(9631125202).jpg', 'CC BY 2.0', 'Dick Culbert from Gibsons, B.C., Canada'),
  ('eucharis-grandiflora', 't', '4/48', 'Eucharis_%C3%97_grandiflora.jpg', 'Public domain', 'Planch. & Linden'),
  ('euphorbia-meloformis', 'u', 'a/a5', 'E_meloformis_valida_ies.jpg', 'CC BY-SA 3.0', 'Frank Vincentz'),
  ('euphorbia-milii', 't', '7/77', 'Euphorbia_Milii_flowers.jpg', 'CC BY-SA 3.0', 'Ezra Katz'),
  ('euphorbia-pulcherrima', 't', 'e/e1', 'Weihnachtsstern_-_gro%C3%9F.jpg', 'CC BY-SA 2.5', 'André Karwath aka Aka'),
  ('euphorbia-trigona', 't', '9/93', 'EuphorbiaTrigona.png', 'CC BY-SA 3.0', 'Totteandersson1'),
  ('exacum-affine', 't', 'e/e7', 'Flower-010.jpg', 'CC BY-SA 3.0', 'Danny S'),
  ('fatshedera-lizei', 'u', 'd/d8', 'X_Fatshedera_lizei2.jpg', 'CC BY-SA 3.0', 'KENPEI'),
  ('fatsia-japonica', 't', 'f/f4', 'Old_Fatsia_japonica_with_blosems.jpg', 'CC BY-SA 4.0', 'Orengi Harvey'),
  ('ficus-altissima', 't', '8/8e', 'Ficus_altissima_of_Silpakorn_University_20231223.jpg', 'CC BY 4.0', 'Supanut Arunoprayote'),
  ('ficus-benjamina', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Starr-080608-7576-Ficus_benjamina-habit_with_Laysan_albatross-Gym_Sand_Island-Midway_Atoll_%2824823189861%29.jpg/960px-Starr-080608-7576-Ficus_benjamina-habit_with_Laysan_albatross-Gym_Sand_Island-Midway_Atoll_%2824823189861%29.jpg', 'Starr-080608-7576-Ficus_benjamina-habit_with_Laysan_albatross-Gym_Sand_Island-Midway_Atoll_(24823189861).jpg', 'CC BY 3.0 us', 'Forest and Kim Starr'),
  ('ficus-binnendijkii', 't', '7/7a', 'Ficus_binnendijkii_kz1.JPG', 'CC BY-SA 3.0', 'Kenraiz'),
  ('ficus-cyathistipula', 't', '0/04', 'Ficus_cyathistipula_kz2.JPG', 'CC BY-SA 3.0', 'Krzysztof Ziarnek, Kenraiz'),
  ('ficus-elastica', 't', '1/16', 'Ficus_elastica_leaves_02.JPG', 'CC BY-SA 3.0', 'B.navez'),
  ('ficus-lyrata', 't', '8/84', 'Starr_031108-0130_Ficus_lyrata.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('ficus-microcarpa', 't', '2/24', 'Ficus_microcarpa_-_La_Gomera_01.jpg', 'CC BY-SA 3.0', 'H. Zell'),
  ('ficus-pumila', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Ficus_pumila_%28Leafs%29.jpg/960px-Ficus_pumila_%28Leafs%29.jpg', 'Ficus_pumila_(Leafs).jpg', 'CC BY-SA 3.0', 'Ixitixel'),
  ('ficus-triangularis', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Starr-120522-6205-Ficus_triangularis-habit-Iao_Tropical_Gardens_of_Maui-Maui_%2824847654670%29.jpg/960px-Starr-120522-6205-Ficus_triangularis-habit-Iao_Tropical_Gardens_of_Maui-Maui_%2824847654670%29.jpg', 'Starr-120522-6205-Ficus_triangularis-habit-Iao_Tropical_Gardens_of_Maui-Maui_(24847654670).jpg', 'CC BY 3.0 us', 'Forest and Kim Starr'),
  ('fittonia-albivenis', 't', '7/72', 'Colpfl25.jpg', 'CC BY-SA 3.0', 'Louise Wolff --darina 00:12, 7 May 2005 (UTC)'),
  ('fuchsia-hybrida', 't', 'b/bf', 'Brincos_De_Princesa.jpg', 'CC BY-SA 3.0', 'Gold Bernard'),
  ('gardenia-jasminoides', 't', '5/54', 'Gardenia_jasminoides_flower_Argentina.jpg', 'CC BY-SA 4.0', 'Adriel anv00'),
  ('gasteria-bicolor', 't', '8/8e', 'Gasteria_bicolor_var_bicolor_3.jpg', 'CC BY-SA 3.0', 'Stan Shebs'),
  ('gerbera-jamesonii', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Gerbera_jamesonii_%28Asteraceae%29.jpg/960px-Gerbera_jamesonii_%28Asteraceae%29.jpg', 'Gerbera_jamesonii_(Asteraceae).jpg', 'CC BY-SA 4.0', 'Alexey Yakovlev'),
  ('goeppertia-lancifolia', 't', '7/79', 'CalatheaLancifolia.jpg', 'Public domain', 'Chhe'),
  ('goeppertia-lietzei', 't', '7/7b', 'Calathea_lietzei_-_JBM.jpg', 'CC BY 3.0', 'Montrealais'),
  ('goeppertia-makoyana', 't', 'a/ae', 'CalatheaMakoyana.jpg', 'Public domain', 'Chhe'),
  ('goeppertia-orbifolia', 't', 'f/fa', 'Calathea_orbifolia_2.jpg', 'CC BY-SA 4.0', 'Fregisseur'),
  ('goeppertia-roseopicta', 't', '3/3f', 'Goeppertia_roseopicta.jpg', 'CC BY 4.0', 'Kathy Richardson'),
  ('goeppertia-rufibarba', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Furry_Feather_%28Calathea_rufibarba%29_%283073332096%29_%282%29.jpg/960px-Furry_Feather_%28Calathea_rufibarba%29_%283073332096%29_%282%29.jpg', 'Furry_Feather_(Calathea_rufibarba)_(3073332096)_(2).jpg', 'CC BY 2.0', 'Cliff from Arlington, Virginia, USA'),
  ('graptopetalum-paraguayense', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/5/59/%28MHNT%29_Graptopetalum_paraguayense_-_leaves.jpg/960px-%28MHNT%29_Graptopetalum_paraguayense_-_leaves.jpg', '(MHNT)_Graptopetalum_paraguayense_-_leaves.jpg', 'CC BY-SA 4.0', 'Didier Descouens'),
  ('guzmania-lingulata', 'u', '8/84', 'Bromeliaceae03.jpg', 'CC BY-SA 3.0', null),
  ('gymnocalycium-baldianum', 't', '8/80', 'Gymnocalcium_baldianium.jpg', 'CC BY-SA 3.0', null),
  ('gymnocalycium-mihanovichii', 't', '0/0a', 'Gymnocalycium_mihanovichii_16.JPG', 'CC BY-SA 4.0', 'Petar43'),
  ('gynura-aurantiaca', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/8/85/%28MHNT%29_Gynura_aurantiaca_-_flower_and_leaf.jpg/960px-%28MHNT%29_Gynura_aurantiaca_-_flower_and_leaf.jpg', '(MHNT)_Gynura_aurantiaca_-_flower_and_leaf.jpg', 'CC BY-SA 4.0', 'Didier Descouens'),
  ('haworthia-cooperi', 't', 'a/a8', '1_Haworthia_cooperi_-_Kirstenbosch.jpg', 'CC0', 'Abu Shawka'),
  ('haworthiopsis-attenuata', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Winterbourne_-_Haworthia_attenuata_%286120983526%29.jpg/960px-Winterbourne_-_Haworthia_attenuata_%286120983526%29.jpg', 'Winterbourne_-_Haworthia_attenuata_(6120983526).jpg', 'CC BY 2.0', 'stephen boisvert from Chicago, United States'),
  ('hedera-helix', 't', '5/5a', 'Hedera_helix_Dover.jpg', 'CC BY-SA 4.0', 'kallerna'),
  ('hibiscus-rosa-sinensis', 't', '2/21', 'Hibiscus_Brilliant.jpg', 'CC BY 2.0', 'Andy / Andrew Fogg from near Cambridge, UK'),
  ('hippeastrum-hybridum', 't', '0/08', 'Hippeastrum_reginae.jpg', 'CC BY 2.0', 'Drew Avery'),
  ('homalomena-rubescens', 't', '9/9a', 'Homalomena_rubescens_1zz.jpg', 'CC BY-SA 4.0', 'David J. Stang'),
  ('howea-forsteriana', 't', '9/99', 'Howea_forsteriana_Lord_Howe_Island.jpg', 'CC BY 2.0', 'Black Diamond Images'),
  ('hoya-carnosa', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg/960px-NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg', 'NKN-2007-06-13_114250_Hoya_Carnosa_(Yvan_Leduc_author_for_Wikipedia).jpg', 'CC BY-SA 3.0', 'Yvan leduc'),
  ('hydrangea-macrophylla', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/2/21/%28Natural%29_Hydrangea_macrophylla%2C_Iwafune%2C_Isumi%2C_Chiba%2C_Japan_2.jpg/960px-%28Natural%29_Hydrangea_macrophylla%2C_Iwafune%2C_Isumi%2C_Chiba%2C_Japan_2.jpg', '(Natural)_Hydrangea_macrophylla,_Iwafune,_Isumi,_Chiba,_Japan_2.jpg', 'CC BY 4.0', 'belvedere04'),
  ('hypoestes-phyllostachya', 't', '4/43', 'Starr_080117-1693_Hypoestes_phyllostachya.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('impatiens-walleriana', 't', '2/28', 'Impatienswalleriana.jpg', 'CC BY-SA 3.0', 'Thegreenj'),
  ('iresine-herbstii', 't', '3/34', 'IresineHerbstii.jpg', 'Public domain', 'Chhe'),
  ('jasminum-polyanthum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/%28MHNT%29_Jasminum_polyanthum_%E2%80%93_flowers_and_buds.jpg/960px-%28MHNT%29_Jasminum_polyanthum_%E2%80%93_flowers_and_buds.jpg', '(MHNT)_Jasminum_polyanthum_%E2%80%93_flowers_and_buds.jpg', 'CC BY-SA 4.0', 'Didier Descouens'),
  ('justicia-carnea', 't', 'e/e8', 'Justicia_carnea_-_MHNT_Borderouge.jpg', 'CC BY 3.0', 'PierreSelim'),
  ('kalanchoe-blossfeldiana', 't', '8/8d', 'Kalanchoe_blossfeldiana_3.jpg', 'CC BY-SA 4.0', 'বাক্যবাগীশ'),
  ('kalanchoe-daigremontiana', 't', 'f/fc', 'Vivipary_in_Kalanchoe_daigremontiana.jpg', 'CC BY-SA 3.0 rs', 'Gmihail at Serbian Wikipedia'),
  ('kalanchoe-thyrsiflora', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/Kalanchoe_thyrsiflora%2C_habitus%2C_Spitskop%2C_a.jpg/960px-Kalanchoe_thyrsiflora%2C_habitus%2C_Spitskop%2C_a.jpg', 'Kalanchoe_thyrsiflora,_habitus,_Spitskop,_a.jpg', 'CC BY-SA 4.0', 'JMK'),
  ('kalanchoe-tomentosa', 't', '0/04', 'Kalanchoe_tomentosa_01.jpg', 'CC BY-SA 4.0', 'Agnieszka Kwiecień, Nova'),
  ('kroenleinia-grusonii', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Echinocactus_grusonii_%28aka%29.jpg/960px-Echinocactus_grusonii_%28aka%29.jpg', 'Echinocactus_grusonii_(aka).jpg', 'CC BY-SA 2.5', 'André Karwath aka Aka'),
  ('lantana-camara', 't', '5/52', 'LantanaFlowerLeaves.jpg', 'CC BY-SA 3.0', 'Alvesgaspar'),
  ('laurus-nobilis', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Starr-071024-0195-Laurus_nobilis-leaves-Enchanting_Floral_Gardens_of_Kula-Maui_%2824867859296%29.jpg/960px-Starr-071024-0195-Laurus_nobilis-leaves-Enchanting_Floral_Gardens_of_Kula-Maui_%2824867859296%29.jpg', 'Starr-071024-0195-Laurus_nobilis-leaves-Enchanting_Floral_Gardens_of_Kula-Maui_(24867859296).jpg', 'CC BY 3.0 us', 'Forest and Kim Starr'),
  ('lithops-lesliei', 't', 'd/d2', 'Lithops_lesliei_ssp._lesliei_v._mariae_Cole_141_01.jpg', 'CC BY-SA 3.0', 'Michael Wolf'),
  ('livistona-chinensis', 'u', 'f/f6', 'Livistona-chinensis.jpg', 'CC BY-SA 3.0', 'Cookie'),
  ('ludisia-discolor', 'u', '4/46', 'Haem3.jpg', 'Public domain', 'Nitesh8de at English Wikipedia'),
  ('mammillaria-elongata', 't', '5/50', 'MammillariaElongata2.jpg', 'Public domain', 'Chhe'),
  ('mandevilla-sanderi', 't', '8/8c', 'Flower-center142058.jpg', 'CC BY 2.1 jp', '日:Jnn'),
  ('maranta-leuconeura', 'u', '4/4a', 'Maranta_leuconeura3.jpg', 'CC BY-SA 3.0', 'Kurt Stüber'),
  ('marsdenia-floribunda', 'u', '3/31', 'Stephanotis_floribunda3L._Marie.jpg', 'CC BY 2.0', 'Lenore Edman from Sunnyvale, CA'),
  ('medinilla-magnifica', 't', 'a/a2', 'Medinilla_magnifica_flor.jpg', 'CC BY-SA 3.0', 'Alberto Salguero'),
  ('melocactus-matanzanus', 't', '1/1b', 'Melocactus_matanzanus_2.jpg', 'CC BY-SA 4.0', 'Photograph by Mike Peel (www.mikepeel.net)'),
  ('microsorum-musifolium', 't', 'a/a9', 'Microsorum_musifolium_closeup.JPG', 'GFDL 1.2', 'Derek Ramsey (Ram-Man)'),
  ('miltoniopsis-hybrida', 't', '5/52', 'Miltoniopsis_phalaenopsis_%27Golden_Gate%27.jpg', 'CC BY-SA 3.0', 'Eric in SF'),
  ('monstera-adansonii', 't', 'f/fb', 'Monstera_adansonii_79319231.jpg', 'CC BY 4.0', 'Aitor'),
  ('monstera-deliciosa', 't', '2/2e', 'Monstera_deliciosa2.jpg', 'CC BY-SA 3.0', null),
  ('monstera-siltepecana', 't', 'd/d3', 'Monstera_siltepecana_kz01.jpg', 'CC BY-SA 4.0', 'Krzysztof Ziarnek, Kenraiz'),
  ('muehlenbeckia-complexa', 't', 'f/f1', 'Muehlenbeckia_complexa_in_flower_T2i_IMG_104_1452.jpg', 'GFDL', 'Avenue'),
  ('murraya-paniculata', 't', '8/8b', 'Murraya_paniculata_05.jpg', 'CC BY-SA 3.0', 'Michael Wolf'),
  ('musa-acuminata', 't', '7/7d', 'Musa_acuminata_in_india01.jpg', 'CC BY-SA 3.0', 'Miya.m'),
  ('myrsine-africana', 't', '6/60', 'Myrsine_africana.jpg', 'CC BY 3.0', 'A. Barra'),
  ('myrtus-communis', 't', 'f/fc', 'Myrtus_communis_L._subsp._communis_-_52505075873.png', 'CC BY 2.0', 'LIGURIAN VASCULAR FLORA'),
  ('nematanthus-gregarius', 't', '1/1d', 'Nematanthus_gregarius_-_Kew_Gardens.JPG', 'CC0', 'Dinkum'),
  ('neoregelia-carolinae', 't', '2/27', 'Neoregelia_carolinae_BotGardBln310505a.jpg', 'CC BY-SA 3.0', null),
  ('nepenthes-ventrata', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Pitcher_Plant_%28Nepenthes_%C3%97_ventrata%29.jpg/960px-Pitcher_Plant_%28Nepenthes_%C3%97_ventrata%29.jpg', 'Pitcher_Plant_(Nepenthes_%C3%97_ventrata).jpg', 'CC BY-SA 3.0', 'Mokkie'),
  ('nephrolepis-exaltata', 'x', 'upload.wikimedia.org/wikipedia/commons/3/30/Boston_Fern_%282873392811%29.png', 'Boston_Fern_(2873392811).png', 'CC BY 2.0', 'Homer Edward Price'),
  ('nerium-oleander', 't', 'c/cc', 'Nerium_oleander_flowers_leaves.jpg', 'CC BY 2.5', 'Alvesgaspar'),
  ('ocimum-basilicum', 't', '9/97', 'Ocimum_basilicum_8zz.jpg', 'CC BY-SA 4.0', 'David J. Stang'),
  ('olea-europaea', 't', '2/2d', 'Olea_europaea_cuspidata-africana_Cape_Town.JPG', 'Public domain', 'Abu Shawka'),
  ('oncidium-hybridum', 'u', '9/9e', 'Oncidium_-_flower_view_01.jpg', 'CC BY-SA 4.0', 'Fan Wen'),
  ('opuntia-microdasys', 't', '3/36', 'Opuntia_microdasys_3.jpg', 'CC BY-SA 3.0', 'Stan Shebs'),
  ('oxalis-triangularis', 'u', '1/15', 'Oxalis_triangularis6.jpg', 'CC BY-SA 3.0', 'KENPEI'),
  ('pachira-aquatica', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Flickr_-_archer10_%28Dennis%29_-_Guatemala-1376.jpg/960px-Flickr_-_archer10_%28Dennis%29_-_Guatemala-1376.jpg', 'Flickr_-_archer10_(Dennis)_-_Guatemala-1376.jpg', 'CC BY-SA 2.0', 'Dennis G. Jarvis'),
  ('pachyphytum-oviferum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/%28MHNT%29_Pachyphytum_oviferum_-_Habitus.jpg/960px-%28MHNT%29_Pachyphytum_oviferum_-_Habitus.jpg', '(MHNT)_Pachyphytum_oviferum_-_Habitus.jpg', 'CC BY-SA 4.0', 'Didier Descouens'),
  ('pachypodium-lamerei', 't', '1/1b', 'Pachypodium_lamerei_-_Cactualdea_San_Nicol%C3%A1s.JPG', 'CC BY-SA 3.0', 'H. Zell'),
  ('pachystachys-lutea', 't', '3/31', 'PachystachysLuteaOrlando.JPG', 'CC BY-SA 3.0', 'UpstateNYer'),
  ('paphiopedilum-hybridum', 't', 'e/ec', 'Paphiopedilum_henryanum_Orchi_001.jpg', 'CC BY-SA 3.0', 'Orchi'),
  ('passiflora-caerulea', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Passiflora_caerulea_%282019-06-24%29_frontal-view.jpg/960px-Passiflora_caerulea_%282019-06-24%29_frontal-view.jpg', 'Passiflora_caerulea_(2019-06-24)_frontal-view.jpg', 'CC BY-SA 4.0', 'Franz van Duns'),
  ('pelargonium-hortorum', 'u', 'b/b0', 'Pelargonium_flower.jpg', 'CC BY-SA 3.0', null),
  ('pentas-lanceolata', 't', '9/9a', 'Penta.JPG', 'CC BY-SA 3.0', 'Cody Hough'),
  ('peperomia-argyreia', 't', 'a/ac', 'Peperomia_argyreia.jpg', 'CC BY-SA 3.0', 'James Steakley'),
  ('peperomia-caperata', 't', '1/14', 'Peperomia_caperata_1-OB9.jpg', 'CC BY-SA 4.0', 'Jerzy Opioła'),
  ('peperomia-obtusifolia', 't', '1/19', 'Peperomia_obtusifolia_3-OB9.jpg', 'CC BY-SA 4.0', 'Jerzy Opioła'),
  ('peperomia-prostrata', 't', '6/63', 'Peperomia_prostrata_kz01.jpg', 'CC BY-SA 4.0', 'Krzysztof Ziarnek, Kenraiz'),
  ('phalaenopsis-hybrid', 'u', '1/1e', 'Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg', 'CC BY-SA 3.0', null),
  ('philodendron-erubescens', 't', 'c/c7', 'Philodendron_erubescens_-_Leaves.jpg', 'CC BY-SA 4.0', 'Alialb'),
  ('philodendron-hederaceum', 'u', 'b/bb', 'Philodendron_scandens_subsp_oxycardium2.jpg', 'CC BY-SA 3.0', 'KENPEI'),
  ('philodendron-melinonii', 't', 'c/cc', 'Philodendron_melinonii-3-my_chedi-foot_hill-yercaud-salem-India.jpg', 'CC BY-SA 4.0', 'Yercaud-elango'),
  ('philodendron-pedatum', 't', '9/93', 'Philodendron_pedatum_kz01.jpg', 'CC BY-SA 4.0', 'Krzysztof Ziarnek, Kenraiz'),
  ('phlebodium-aureum', 't', '2/2d', 'Starr_050107-2831_Phlebodium_aureum.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('phoenix-roebelenii', 't', '1/1d', 'Starr_070124-3839_Phoenix_roebelenii.jpg', 'CC BY 3.0', 'Forest & Kim Starr'),
  ('pilea-cadierei', 't', '3/30', 'PileaCadierei.jpg', 'CC BY-SA 3.0', 'Fanghong'),
  ('pilea-peperomioides', 't', '6/6d', 'Pilea_peperomioides_Chinese_money_plant.jpg', 'CC0', 'Husky'),
  ('platycerium-bifurcatum', 't', 'd/d8', 'Platycerium_bifurcatum_612351086.jpg', 'CC0', 'themaskedlapwing'),
  ('pleiospilos-nelii', 't', '8/85', 'Pleiospilos_nelii_flower.jpg', 'CC BY-SA 3.0', 'ZooFari'),
  ('plerandra-elegantissima', 'u', '6/64', 'Schefflera_elegantissima.jpg', 'CC BY-SA 4.0', 'Eric in SF'),
  ('pogonatherum-paniceum', 't', 'e/eb', 'Pogonatherum_paniceum.jpg', 'CC BY-SA 3.0', 'IKAl'),
  ('polyscias-fruticosa', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Polyscias_fruticosa%2C_Hong_Kong_Park%2C_December_2019_16.jpg/960px-Polyscias_fruticosa%2C_Hong_Kong_Park%2C_December_2019_16.jpg', 'Polyscias_fruticosa,_Hong_Kong_Park,_December_2019_16.jpg', 'CC BY-SA 4.0', 'Ahmed'),
  ('polyscias-scutellaria', 't', '7/70', 'Polyscias_scutellaria_-_Krohn_Conservatory_-_DSC03688.JPG', 'CC0', 'Daderot'),
  ('portulacaria-afra', 't', '4/46', 'Portulacaria_afra_02.JPG', 'CC0', 'Dinkum'),
  ('primula-vulgaris', 't', 'a/ad', 'Prole%C4%87no_cve%C4%87e_3.JPG', 'CC BY-SA 3.0', 'Pokrajac'),
  ('radermachera-sinica', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Radermachera_sinica_-_%22China_Doll_tree%22_%283_photos%29_%284400613119%29.jpg/960px-Radermachera_sinica_-_%22China_Doll_tree%22_%283_photos%29_%284400613119%29.jpg', 'Radermachera_sinica_-_%22China_Doll_tree%22_(3_photos)_(4400613119).jpg', 'CC BY 2.0', 'Tatters ❀ from Brisbane, Australia'),
  ('rhaphidophora-tetrasperma', 'u', 'd/db', 'Rhaphidophora_tetrasperma.jpg', 'CC BY-SA 4.0', 'Theoperatingsystem'),
  ('rhapis-excelsa', 't', '0/0c', 'Arya_-_Rhapis_excelsa_at_hotel_citradream_Cirebon_2019_0.jpg', 'CC BY-SA 4.0', 'Aris riyanto'),
  ('rhipsalis-baccifera', 'u', 'b/ba', 'Rhipsalis_baccifera_01_ies.jpg', 'CC BY-SA 3.0', 'Frank Vincentz'),
  ('rhododendron-simsii', 't', '6/67', 'Rhododendron_simsii-bunga_2-Lany_pirna.jpg', 'CC BY-SA 4.0', 'Lany pirna'),
  ('rosa-chinensis', 't', '2/2a', 'Rosa_chinensis.jpg', 'CC BY-SA 3.0', 'Sakurai Midori'),
  ('salvia-rosmarinus', 't', 'a/a3', 'Rosemary_in_bloom.JPG', 'CC BY-SA 4.0', 'Margalob'),
  ('sarracenia-purpurea', 't', '7/7c', 'Sarracenia_purpurea_Flowers.JPG', 'GFDL 1.2', 'Derek Ramsey (Ram-Man)'),
  ('saxifraga-stolonifera', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Saxifraga_stolonifera_%28flower_s5%29.jpg/960px-Saxifraga_stolonifera_%28flower_s5%29.jpg', 'Saxifraga_stolonifera_(flower_s5).jpg', 'CC BY-SA 4.0', 'Alpsdake'),
  ('schefflera-arboricola', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Schefflera_arboricola%2C_vrugte%2C_a%2C_Pretoria.jpg/960px-Schefflera_arboricola%2C_vrugte%2C_a%2C_Pretoria.jpg', 'Schefflera_arboricola,_vrugte,_a,_Pretoria.jpg', 'CC BY-SA 3.0', 'JMK'),
  ('schlumbergera-truncata', 't', '8/8c', 'Schlumbergera_%C3%97_buckleyi_flower.jpg', 'CC BY-SA 2.5 ca', 'The Cosmonaut'),
  ('scindapsus-pictus', 't', 'c/ca', 'Scindapsus_pictus_01.jpg', 'CC BY-SA 3.0', 'Kor!An (Корзун Андрей)'),
  ('sedum-morganianum', 't', 'e/e5', 'Donkey%27s_tail_in_bloom_March_06.jpg', 'CC BY-SA 3.0', 'Morningdew51 at English Wikipedia'),
  ('selaginella-martensii', 't', 'a/aa', 'Selaginella_martensii_-_Berlin_Botanical_Garden_-_IMG_8724.JPG', 'Public domain', 'Daderot'),
  ('sempervivum-tectorum', 't', '5/51', 'Sempervivum_tectorum_Almindelig_Husl%C3%B8g.jpg', 'CC BY-SA 3.0', null),
  ('sinningia-speciosa', 't', '1/13', 'Florada_da_Glox%C3%ADnia.jpg', 'CC BY-SA 4.0', 'Antoninhocd'),
  ('solanum-pseudocapsicum', 't', '3/36', 'Solanum_pseudocapsicum04.jpg', 'CC BY-SA 3.0', 'Paul venter'),
  ('soleirolia-soleirolii', 'u', '2/2f', 'Soleirolia_soleirolii002.JPG', 'CC BY-SA 3.0', 'Hugo.arg'),
  ('spathiphyllum-wallisii', 't', '4/49', 'Peace_lily_-_1_-_cropped.jpg', 'CC BY-SA 4.0', 'W.carter'),
  ('stapelia-grandiflora', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Stapelia_grandiflora_22102013_1_%2810606394434%29.jpg/960px-Stapelia_grandiflora_22102013_1_%2810606394434%29.jpg', 'Stapelia_grandiflora_22102013_1_(10606394434).jpg', 'CC BY 2.0', 'Jean-Michel Moullec from Vern sur Seiche (35, Bretagne),…'),
  ('strelitzia-reginae', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Ave-do-para%C3%ADso%2C_Strelitzia_reginae%2C_em_Bag%C3%A9%2C_Rio_Grande_do_Sul%2C_Brasil_-_55211233712.jpg/960px-Ave-do-para%C3%ADso%2C_Strelitzia_reginae%2C_em_Bag%C3%A9%2C_Rio_Grande_do_Sul%2C_Brasil_-_55211233712.jpg', 'Ave-do-para%C3%ADso,_Strelitzia_reginae,_em_Bag%C3%A9,_Rio_Grande_do_Sul,_Brasil_-_55211233712.jpg', 'CC BY 4.0', 'Gabriel Collares'),
  ('streptocarpus-hybridus', 't', 'e/ee', '2007-03-20Streptocarpus03.jpg', 'CC BY-SA 3.0', 'Wildfeuer'),
  ('streptocarpus-ionanthus', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Saintpaulia_ionantha_%28Claire_Felloni%29.jpg/960px-Saintpaulia_ionantha_%28Claire_Felloni%29.jpg', 'Saintpaulia_ionantha_(Claire_Felloni).jpg', 'CC BY-SA 4.0', 'Felloni claire'),
  ('stromanthe-thalia', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Stromanthe_sanguinea_in_garden_in_Manaus%2C_Brazil.jpg/960px-Stromanthe_sanguinea_in_garden_in_Manaus%2C_Brazil.jpg', 'Stromanthe_sanguinea_in_garden_in_Manaus,_Brazil.jpg', 'CC BY-SA 4.0', 'Aleph500Dadamz'),
  ('syngonium-podophyllum', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Syngonium_podophyllum_%28_Arrowhead_plant%29.jpg/960px-Syngonium_podophyllum_%28_Arrowhead_plant%29.jpg', 'Syngonium_podophyllum_(_Arrowhead_plant).jpg', 'CC BY-SA 4.0', 'Stephanie cheks'),
  ('thaumatophyllum-bipinnatifidum', 'u', 'c/c1', 'Tree1.JPG', 'Public domain', 'VSA.bing'),
  ('tillandsia-cyanea', 'u', '6/65', 'Tillandsia_cyanea1.jpg', 'CC BY-SA 3.0', 'Kurt Stüber'),
  ('tillandsia-ionantha', 't', 'b/b5', 'Purple_sky_plant_-_Andrey_Zharkikh.jpg', 'CC BY 2.0', 'Andrey Zharkikh from Salt Lake City, USA'),
  ('tradescantia-fluminensis', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/Tradescantia_fluminensis_%28Flowers%29.jpg/960px-Tradescantia_fluminensis_%28Flowers%29.jpg', 'Tradescantia_fluminensis_(Flowers).jpg', 'CC BY-SA 3.0', 'Ixitixel'),
  ('tradescantia-pallida', 'x', 'thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Trapoeraba-roxa_%28do_tupi_%2Atarapoeraba%29_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55378584901.jpg/960px-Trapoeraba-roxa_%28do_tupi_%2Atarapoeraba%29_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55378584901.jpg', 'Trapoeraba-roxa_(do_tupi_*tarapoeraba)_em_Bag%C3%A9,_RS,_Brasil_-_55378584901.jpg', 'CC BY 4.0', 'O Tupinólogo'),
  ('tradescantia-zebrina', 'u', 'f/fd', 'Zebrina_pendula_20060521_2_closer.jpg', 'CC BY-SA 3.0', 'Ruestz (upload 13:54, 11 January 2008)'),
  ('vanda-hybrida', 't', '3/3c', 'Vanda_coerulea_Orchi_6052.jpg', 'CC BY-SA 3.0', 'Orchi'),
  ('vriesea-splendens', 'u', 'b/b6', 'Bromelia1.jpg', 'CC BY-SA 3.0', 'El Denis Conrado, en la urbo Lavras, MG., Brazilo'),
  ('washingtonia-robusta', 't', 'b/b8', 'Arecales_-_Washingtonia_robusta_-_1.jpg', 'CC BY-SA 4.0', 'Emőke Dénes'),
  ('xerosicyos-danguyi', 't', '8/8d', 'Xerosicyos_danguyi_2015-05-29_OB_187.jpg', 'CC BY-SA 4.0', 'Salicyna'),
  ('yucca-gigantea', 't', 'b/bd', 'Yucca_gigantea_-_Jard%C3%ADn_Bot%C3%A1nico_Canario_Viera_y_Clavijo_-_Gran_Canaria.jpg', 'CC BY-SA 3.0', 'H. Zell'),
  ('zamia-furfuracea', 't', '7/79', 'Zamia_furfuracea03.jpg', 'CC BY-SA 2.5', null),
  ('zamioculcas-zamiifolia', 't', 'c/cf', 'Zamioculcas_zamiifolia_1.jpg', 'CC BY-SA 3.0', 'User:WeFt')
  ) as v(slug, kind, dir, file, license, credit)
 where s.slug = v.slug
   and (s.image_license is distinct from v.license
        or s.image_credit is distinct from v.credit
        or s.image_source_url is distinct from 'https://commons.wikimedia.org/wiki/File:' || v.file);
