-- База знаний, часть 3: программа подкормки для каждого вида (care_profiles.fertilizer_slug)
-- и популярные сорта (species.cultivars). Миграция идемпотентна.

update public.care_profiles cp set fertilizer_slug = a.fert
from (values
  ('acalypha-hispida', 'universal'),
  ('adenium-obesum', 'cactus'),
  ('adiantum-raddianum', 'fern'),
  ('adromischus-cristatus', 'cactus'),
  ('aechmea-fasciata', 'bromeliad'),
  ('aeonium-arboreum', 'cactus'),
  ('aeschynanthus-radicans', 'flowering'),
  ('agave-attenuata', 'cactus'),
  ('aglaonema-commutatum', 'foliage'),
  ('alocasia-amazonica', 'foliage'),
  ('alocasia-baginda', 'foliage'),
  ('alocasia-cuprea', 'foliage'),
  ('alocasia-longiloba', 'foliage'),
  ('alocasia-macrorrhizos', 'foliage'),
  ('alocasia-micholitziana', 'foliage'),
  ('alocasia-reginula', 'foliage'),
  ('alocasia-wentii', 'foliage'),
  ('alocasia-zebrina', 'foliage'),
  ('aloe-vera', 'cactus'),
  ('anacampseros-rufescens', 'cactus'),
  ('ananas-comosus', 'bromeliad'),
  ('anthurium-andraeanum', 'flowering'),
  ('anthurium-clarinervium', 'foliage'),
  ('anthurium-hookeri', 'foliage'),
  ('anthurium-scherzerianum', 'flowering'),
  ('aphelandra-squarrosa', 'flowering'),
  ('araucaria-heterophylla', 'universal'),
  ('ardisia-crenata', 'flowering'),
  ('aristaloe-aristata', 'cactus'),
  ('asparagus-aethiopicus', 'foliage'),
  ('asparagus-setaceus', 'foliage'),
  ('aspidistra-elatior', 'foliage'),
  ('asplenium-nidus', 'foliage'),
  ('astrophytum-myriostigma', 'cactus'),
  ('aucuba-japonica', 'universal'),
  ('beaucarnea-recurvata', 'cactus'),
  ('begonia-hiemalis', 'flowering'),
  ('begonia-maculata', 'foliage'),
  ('begonia-rex', 'foliage'),
  ('blechnum-gibbum', 'fern'),
  ('bougainvillea-glabra', 'flowering'),
  ('brighamia-insignis', 'flowering'),
  ('browallia-speciosa', 'flowering'),
  ('caladium-bicolor', 'foliage'),
  ('calceolaria-herbeohybrida', 'flowering'),
  ('callisia-repens', 'foliage'),
  ('camellia-japonica', 'acid'),
  ('capsicum-annuum', 'edible'),
  ('carissa-macrocarpa', 'flowering'),
  ('cattleya-hybrida', 'orchid'),
  ('cereus-repandus', 'cactus'),
  ('ceropegia-woodii', 'cactus'),
  ('chamaedorea-elegans', 'palm'),
  ('chamaerops-humilis', 'palm'),
  ('chlorophytum-comosum', 'foliage'),
  ('chlorophytum-orchidastrum', 'foliage'),
  ('chrysanthemum-morifolium', 'flowering'),
  ('cissus-rhombifolia', 'foliage'),
  ('citrus-japonica', 'citrus'),
  ('citrus-limon', 'citrus'),
  ('citrus-microcarpa', 'citrus'),
  ('citrus-reticulata', 'citrus'),
  ('citrus-sinensis', 'citrus'),
  ('cleistocactus-winteri', 'cactus'),
  ('clerodendrum-thomsoniae', 'flowering'),
  ('clivia-miniata', 'flowering'),
  ('clusia-rosea', 'universal'),
  ('cocos-nucifera', 'palm'),
  ('codiaeum-variegatum', 'universal'),
  ('coffea-arabica', 'universal'),
  ('coleus-scutellarioides', 'foliage'),
  ('columnea-gloriosa', 'flowering'),
  ('cordyline-fruticosa', 'universal'),
  ('corokia-cotoneaster', 'universal'),
  ('cotyledon-orbiculata', 'cactus'),
  ('crassula-muscosa', 'cactus'),
  ('crassula-ovata', 'cactus'),
  ('crassula-perforata', 'cactus'),
  ('crossandra-infundibuliformis', 'flowering'),
  ('cryptanthus-bivittatus', 'bromeliad'),
  ('ctenanthe-burle-marxii', 'fern'),
  ('cupressus-macrocarpa', 'universal'),
  ('curio-rowleyanus', 'cactus'),
  ('cycas-revoluta', 'palm'),
  ('cyclamen-persicum', 'flowering'),
  ('cymbidium-hybridum', 'orchid'),
  ('davallia-fejeensis', 'fern'),
  ('dendrobium-nobile', 'orchid'),
  ('dieffenbachia-seguine', 'foliage'),
  ('dionaea-muscipula', 'carnivorous'),
  ('dracaena-angolensis', 'cactus'),
  ('dracaena-fragrans', 'universal'),
  ('dracaena-marginata', 'universal'),
  ('dracaena-reflexa', 'universal'),
  ('dracaena-sanderiana', 'foliage'),
  ('dracaena-trifasciata', 'cactus'),
  ('drosera-capensis', 'carnivorous'),
  ('dypsis-lutescens', 'palm'),
  ('echeveria-elegans', 'cactus'),
  ('echinopsis-oxygona', 'cactus'),
  ('ehretia-microphylla', 'universal'),
  ('epiphyllum-oxypetalum', 'flowering'),
  ('epipremnum-aureum', 'foliage'),
  ('epipremnum-pinnatum', 'foliage'),
  ('episcia-cupreata', 'flowering'),
  ('eucharis-grandiflora', 'flowering'),
  ('euphorbia-meloformis', 'cactus'),
  ('euphorbia-milii', 'cactus'),
  ('euphorbia-pulcherrima', 'flowering'),
  ('euphorbia-tirucalli', 'cactus'),
  ('euphorbia-trigona', 'cactus'),
  ('exacum-affine', 'flowering'),
  ('fatshedera-lizei', 'universal'),
  ('fatsia-japonica', 'universal'),
  ('ficus-altissima', 'universal'),
  ('ficus-benjamina', 'universal'),
  ('ficus-binnendijkii', 'universal'),
  ('ficus-cyathistipula', 'universal'),
  ('ficus-elastica', 'universal'),
  ('ficus-lyrata', 'universal'),
  ('ficus-microcarpa', 'universal'),
  ('ficus-pumila', 'foliage'),
  ('ficus-triangularis', 'universal'),
  ('fittonia-albivenis', 'foliage'),
  ('fuchsia-hybrida', 'flowering'),
  ('gardenia-jasminoides', 'acid'),
  ('gasteria-bicolor', 'cactus'),
  ('gerbera-jamesonii', 'flowering'),
  ('goeppertia-crocata', 'fern'),
  ('goeppertia-lancifolia', 'fern'),
  ('goeppertia-lietzei', 'fern'),
  ('goeppertia-makoyana', 'fern'),
  ('goeppertia-orbifolia', 'fern'),
  ('goeppertia-roseopicta', 'fern'),
  ('goeppertia-rufibarba', 'fern'),
  ('goeppertia-warszewiczii', 'fern'),
  ('graptopetalum-paraguayense', 'cactus'),
  ('guzmania-lingulata', 'bromeliad'),
  ('gymnocalycium-baldianum', 'cactus'),
  ('gymnocalycium-mihanovichii', 'cactus'),
  ('gynura-aurantiaca', 'foliage'),
  ('haworthia-cooperi', 'cactus'),
  ('haworthiopsis-attenuata', 'cactus'),
  ('hedera-helix', 'foliage'),
  ('hibiscus-rosa-sinensis', 'flowering'),
  ('hippeastrum-hybridum', 'flowering'),
  ('homalomena-rubescens', 'foliage'),
  ('howea-forsteriana', 'palm'),
  ('hoya-carnosa', 'flowering'),
  ('hoya-kerrii', 'flowering'),
  ('hydrangea-macrophylla', 'acid'),
  ('hypoestes-phyllostachya', 'foliage'),
  ('impatiens-walleriana', 'flowering'),
  ('iresine-herbstii', 'foliage'),
  ('jasminum-polyanthum', 'flowering'),
  ('justicia-carnea', 'flowering'),
  ('kalanchoe-blossfeldiana', 'flowering'),
  ('kalanchoe-daigremontiana', 'cactus'),
  ('kalanchoe-thyrsiflora', 'cactus'),
  ('kalanchoe-tomentosa', 'cactus'),
  ('kroenleinia-grusonii', 'cactus'),
  ('lantana-camara', 'flowering'),
  ('laurus-nobilis', 'universal'),
  ('lithops-lesliei', 'minimal'),
  ('livistona-chinensis', 'palm'),
  ('ludisia-discolor', 'orchid'),
  ('mammillaria-elongata', 'cactus'),
  ('mammillaria-hahniana', 'cactus'),
  ('mandevilla-sanderi', 'flowering'),
  ('maranta-leuconeura', 'fern'),
  ('marsdenia-floribunda', 'flowering'),
  ('medinilla-magnifica', 'flowering'),
  ('melocactus-matanzanus', 'cactus'),
  ('microsorum-musifolium', 'fern'),
  ('miltoniopsis-hybrida', 'orchid'),
  ('monstera-adansonii', 'foliage'),
  ('monstera-deliciosa', 'foliage'),
  ('monstera-siltepecana', 'foliage'),
  ('muehlenbeckia-complexa', 'foliage'),
  ('murraya-paniculata', 'flowering'),
  ('musa-acuminata', 'foliage'),
  ('myrsine-africana', 'universal'),
  ('myrtus-communis', 'universal'),
  ('nematanthus-gregarius', 'flowering'),
  ('neoregelia-carolinae', 'bromeliad'),
  ('nepenthes-ventrata', 'carnivorous'),
  ('nephrolepis-exaltata', 'fern'),
  ('nerium-oleander', 'flowering'),
  ('ocimum-basilicum', 'edible'),
  ('olea-europaea', 'universal'),
  ('oncidium-hybridum', 'orchid'),
  ('opuntia-microdasys', 'cactus'),
  ('oxalis-triangularis', 'foliage'),
  ('pachira-aquatica', 'universal'),
  ('pachyphytum-oviferum', 'cactus'),
  ('pachypodium-lamerei', 'cactus'),
  ('pachystachys-lutea', 'flowering'),
  ('paphiopedilum-hybridum', 'orchid'),
  ('parodia-magnifica', 'cactus'),
  ('passiflora-caerulea', 'flowering'),
  ('pelargonium-hortorum', 'flowering'),
  ('pentas-lanceolata', 'flowering'),
  ('peperomia-argyreia', 'foliage'),
  ('peperomia-caperata', 'foliage'),
  ('peperomia-obtusifolia', 'foliage'),
  ('peperomia-polybotrya', 'foliage'),
  ('peperomia-prostrata', 'foliage'),
  ('persea-americana', 'universal'),
  ('phalaenopsis-hybrid', 'orchid'),
  ('philodendron-erubescens', 'foliage'),
  ('philodendron-hederaceum', 'foliage'),
  ('philodendron-melinonii', 'foliage'),
  ('philodendron-pedatum', 'foliage'),
  ('phlebodium-aureum', 'fern'),
  ('phoenix-roebelenii', 'palm'),
  ('pilea-cadierei', 'foliage'),
  ('pilea-peperomioides', 'foliage'),
  ('pinguicula-moranensis', 'carnivorous'),
  ('platycerium-bifurcatum', 'fern'),
  ('pleiospilos-nelii', 'minimal'),
  ('plerandra-elegantissima', 'universal'),
  ('pogonatherum-paniceum', 'foliage'),
  ('polyscias-fruticosa', 'universal'),
  ('polyscias-scutellaria', 'universal'),
  ('portulacaria-afra', 'cactus'),
  ('primula-vulgaris', 'flowering'),
  ('pteris-cretica', 'fern'),
  ('radermachera-sinica', 'universal'),
  ('rhaphidophora-tetrasperma', 'foliage'),
  ('rhapis-excelsa', 'palm'),
  ('rhipsalis-baccifera', 'cactus'),
  ('rhododendron-simsii', 'acid'),
  ('rosa-chinensis', 'flowering'),
  ('salvia-rosmarinus', 'edible'),
  ('sarracenia-purpurea', 'carnivorous'),
  ('saxifraga-stolonifera', 'foliage'),
  ('schefflera-arboricola', 'universal'),
  ('schlumbergera-gaertneri', 'flowering'),
  ('schlumbergera-truncata', 'flowering'),
  ('scindapsus-pictus', 'foliage'),
  ('sedum-morganianum', 'cactus'),
  ('selaginella-martensii', 'fern'),
  ('sempervivum-tectorum', 'cactus'),
  ('sinningia-speciosa', 'flowering'),
  ('solanum-lycopersicum', 'edible'),
  ('solanum-pseudocapsicum', 'flowering'),
  ('soleirolia-soleirolii', 'fern'),
  ('spathiphyllum-wallisii', 'flowering'),
  ('stapelia-grandiflora', 'cactus'),
  ('strelitzia-reginae', 'flowering'),
  ('streptocarpus-hybridus', 'flowering'),
  ('streptocarpus-ionanthus', 'flowering'),
  ('stromanthe-thalia', 'fern'),
  ('syngonium-podophyllum', 'foliage'),
  ('thaumatophyllum-bipinnatifidum', 'foliage'),
  ('tillandsia-cyanea', 'bromeliad'),
  ('tillandsia-ionantha', 'bromeliad'),
  ('tradescantia-fluminensis', 'foliage'),
  ('tradescantia-pallida', 'foliage'),
  ('tradescantia-sillamontana', 'cactus'),
  ('tradescantia-zebrina', 'foliage'),
  ('vanda-hybrida', 'orchid'),
  ('vriesea-splendens', 'bromeliad'),
  ('washingtonia-robusta', 'palm'),
  ('xerosicyos-danguyi', 'cactus'),
  ('yucca-gigantea', 'universal'),
  ('zamia-furfuracea', 'palm'),
  ('zamioculcas-zamiifolia', 'cactus')
) as a(slug, fert)
join public.species sp on sp.slug = a.slug
where cp.species_id = sp.id;

update public.species s set cultivars = c.cultivars
from (values
  ('monstera-deliciosa', '[{"name": "Thai Constellation", "ru": "Тай Констелейшн", "note": "Стабильная кремовая «звёздная» пестрота по всему листу; растёт медленнее зелёной."}, {"name": "Albo Variegata", "ru": "Альбо", "note": "Белые сектора и мазки; пестрота нестабильна, нужен яркий свет."}, {"name": "Aurea", "ru": "Ауреа", "note": "Жёлтая пестрота секторами."}, {"name": "Borsigiana", "ru": "Борсигиана", "note": "Компактная форма с более тонкими черешками и мелкими листьями."}]'::jsonb),
  ('monstera-adansonii', '[{"name": "Albo Variegata", "ru": "Альбо", "note": "Белая пестрота, редкая и капризная."}]'::jsonb),
  ('epipremnum-aureum', '[{"name": "Marble Queen", "ru": "Марбл Квин", "note": "Много кремово-белого, растёт медленнее."}, {"name": "N''Joy", "ru": "Энджой", "note": "Компактный, чёткие белые пятна по краю листа."}, {"name": "Neon", "ru": "Неон", "note": "Ярко-лимонные листья без пестроты; нужен свет, иначе зеленеет."}, {"name": "Manjula", "ru": "Манжула", "note": "Широкие волнистые листья с кремовыми и серебристыми мазками."}, {"name": "Golden", "ru": "Голден", "note": "Классический: зелёный с жёлтыми штрихами."}]'::jsonb),
  ('epipremnum-pinnatum', '[{"name": "Cebu Blue", "ru": "Себу Блю", "note": "Узкие листья с серебристо-голубым отливом; у взрослых — с прорезями."}]'::jsonb),
  ('philodendron-hederaceum', '[{"name": "Brasil", "ru": "Бразил", "note": "Жёлто-зелёная полоса по центру листа."}, {"name": "Micans", "ru": "Микан", "note": "Бархатистые бронзово-зелёные листья."}, {"name": "Lemon Lime", "ru": "Лемон Лайм", "note": "Лимонно-зелёные листья."}]'::jsonb),
  ('philodendron-erubescens', '[{"name": "Pink Princess", "ru": "Пинк Принцесс", "note": "Тёмные листья с розовыми секторами; чем больше розового, тем капризнее."}, {"name": "Birkin", "ru": "Биркин", "note": "Тёмно-зелёные листья в тонких белых штрихах."}, {"name": "Imperial Red", "ru": "Империал Ред", "note": "Молодые листья бордовые, со временем темнеют."}, {"name": "Imperial Green", "ru": "Империал Грин", "note": "Крупные глянцевые ярко-зелёные листья, компактная розетка."}]'::jsonb),
  ('ficus-elastica', '[{"name": "Robusta", "ru": "Робуста", "note": "Классический тёмно-зелёный, самый неприхотливый."}, {"name": "Tineke", "ru": "Тинеке", "note": "Кремово-зелёная пестрота с розоватой серединой."}, {"name": "Ruby", "ru": "Руби", "note": "Розово-кремовая пестрота, ярче на свету."}, {"name": "Belize", "ru": "Белиз", "note": "Кремовые и розовые мазки по краям."}, {"name": "Abidjan", "ru": "Абиджан", "note": "Почти чёрно-бордовые листья."}]'::jsonb),
  ('ficus-benjamina', '[{"name": "Danielle", "ru": "Даниэль", "note": "Глянцевые тёмно-зелёные листья, плотная крона."}, {"name": "Kinky", "ru": "Кинки", "note": "Мелкие листья с кремовой каймой, компактный."}, {"name": "Starlight", "ru": "Старлайт", "note": "Белая кайма и пятна; нужен яркий свет."}, {"name": "Natasha", "ru": "Наташа", "note": "Мелколистный, хорош для бонсай."}]'::jsonb),
  ('ficus-lyrata', '[{"name": "Bambino", "ru": "Бамбино", "note": "Компактный, листья вдвое мельче."}]'::jsonb),
  ('dracaena-trifasciata', '[{"name": "Laurentii", "ru": "Лаурентии", "note": "Жёлтая кайма по краю листа."}, {"name": "Hahnii", "ru": "Ханни", "note": "Низкая розетка-«гнездо»."}, {"name": "Moonshine", "ru": "Муншайн", "note": "Серебристо-зелёные листья."}, {"name": "Futura Superba", "ru": "Футура Суперба", "note": "Короткие широкие листья с жёлтой каймой."}]'::jsonb),
  ('zamioculcas-zamiifolia', '[{"name": "Raven", "ru": "Рейвен", "note": "Молодые листья зелёные, потом почти чёрные."}, {"name": "Zenzi", "ru": "Зензи", "note": "Компактный, листочки плотно прижаты и закручены."}]'::jsonb),
  ('spathiphyllum-wallisii', '[{"name": "Sensation", "ru": "Сенсейшн", "note": "Крупный, до метра, с рифлёными листьями."}, {"name": "Domino", "ru": "Домино", "note": "Белые штрихи на листьях."}, {"name": "Picasso", "ru": "Пикассо", "note": "Крупные белые сектора; нужен свет."}, {"name": "Chopin", "ru": "Шопен", "note": "Компактный, с ароматными цветками."}]'::jsonb),
  ('aglaonema-commutatum', '[{"name": "Silver Bay", "ru": "Сильвер Бэй", "note": "Серебристый центр листа, выносливый."}, {"name": "Maria", "ru": "Мария", "note": "Тёмно-зелёные листья с серебристыми мазками; мирится с тенью."}, {"name": "Silver Queen", "ru": "Сильвер Квин", "note": "Почти серебристые узкие листья."}]'::jsonb),
  ('hoya-carnosa', '[{"name": "Krimson Queen", "ru": "Кримсон Квин", "note": "Кремово-розовая кайма (другое название — «Трёхцветная»)."}, {"name": "Krimson Princess", "ru": "Кримсон Принцесс", "note": "Кремово-розовый центр листа."}, {"name": "Compacta", "ru": "Компакта", "note": "Скрученные листья-«верёвочки» (Hindu Rope); поливать осторожнее."}]'::jsonb),
  ('syngonium-podophyllum', '[{"name": "White Butterfly", "ru": "Уайт Баттерфлай", "note": "Светлые, почти белые листья с зелёной каймой."}, {"name": "Neon Robusta", "ru": "Неон Робуста", "note": "Нежно-розовые листья."}, {"name": "Albo Variegata", "ru": "Альбо", "note": "Белые сектора; редкий и медленный."}]'::jsonb),
  ('maranta-leuconeura', '[{"name": "Fascinator", "ru": "Фасцинатор", "note": "Красные жилки и салатовый рисунок (Tricolor)."}, {"name": "Kerchoveana", "ru": "Керховеана", "note": "Тёмные пятна между жилками — «следы кролика»."}, {"name": "Lemon Lime", "ru": "Лемон Лайм", "note": "Лимонные жилки на тёмно-зелёном."}]'::jsonb),
  ('dieffenbachia-seguine', '[{"name": "Camille", "ru": "Камилла", "note": "Светлый кремовый центр, компактная."}, {"name": "Tropic Snow", "ru": "Тропик Сноу", "note": "Крупная, с белыми мазками по центру."}, {"name": "Compacta", "ru": "Компакта", "note": "Невысокая, кустится."}]'::jsonb),
  ('alocasia-baginda', '[{"name": "Silver Dragon", "ru": "Сильвер Драгон", "note": "Серебристые листья с тёмными жилками."}, {"name": "Dragon Scale", "ru": "Драгон Скейл", "note": "Тёмно-зелёная рельефная «чешуя»."}]'::jsonb),
  ('alocasia-amazonica', '[{"name": "Polly", "ru": "Полли", "note": "Компактная, до 40 см; самая частая в продаже."}]'::jsonb),
  ('scindapsus-pictus', '[{"name": "Argyraeus", "ru": "Аргирэус", "note": "Мелкие серебристые пятна и кайма."}, {"name": "Exotica", "ru": "Экзотика", "note": "Крупные серебристые мазки на весь лист."}]'::jsonb),
  ('chlorophytum-comosum', '[{"name": "Vittatum", "ru": "Виттатум", "note": "Белая полоса по центру листа."}, {"name": "Variegatum", "ru": "Вариегатум", "note": "Белая кайма по краям."}, {"name": "Bonnie", "ru": "Бонни", "note": "Закрученные «кудрявые» листья."}]'::jsonb),
  ('crassula-ovata', '[{"name": "Gollum", "ru": "Голлум", "note": "Трубчатые листья с присосками на концах."}, {"name": "Hobbit", "ru": "Хоббит", "note": "Листья, закрученные в трубочки; компактнее «Голлума»."}, {"name": "Tricolor", "ru": "Триколор", "note": "Кремово-розовая пестрота; нужно солнце."}]'::jsonb),
  ('kalanchoe-blossfeldiana', '[{"name": "Calandiva", "ru": "Каландива", "note": "Махровые цветки-розочки."}]'::jsonb),
  ('peperomia-obtusifolia', '[{"name": "Variegata", "ru": "Вариегата", "note": "Кремово-зелёная пестрота."}]'::jsonb),
  ('tradescantia-fluminensis', '[{"name": "Quicksilver", "ru": "Квиксильвер", "note": "Серебристо-белые полоски."}, {"name": "Tricolor", "ru": "Триколор", "note": "Бело-розово-зелёные полосы; розовеет на свету."}]'::jsonb),
  ('pilea-peperomioides', '[{"name": "Mojito", "ru": "Мохито", "note": "Зелёные листья с салатовыми и кремовыми мазками."}]'::jsonb),
  ('goeppertia-roseopicta', '[{"name": "Dottie", "ru": "Дотти", "note": "Почти чёрные листья с розовым рисунком."}, {"name": "Medallion", "ru": "Медальон", "note": "Серебристо-зелёный «медальон» и бордовая изнанка."}, {"name": "Rosy", "ru": "Рози", "note": "Розовый центр листа с зелёной каймой."}]'::jsonb),
  ('hedera-helix', '[{"name": "Glacier", "ru": "Глейшер", "note": "Серо-зелёные листья с белой каймой."}, {"name": "Goldchild", "ru": "Голдчайлд", "note": "Жёлтая кайма."}, {"name": "Eva", "ru": "Ева", "note": "Мелкие листья с кремовой каймой, компактный."}]'::jsonb),
  ('nephrolepis-exaltata', '[{"name": "Bostoniensis", "ru": "Бостонский", "note": "Длинные изогнутые вайи — классика подвесных кашпо."}, {"name": "Green Lady", "ru": "Грин Леди", "note": "Пышный шар из прямых вай."}, {"name": "Fluffy Ruffles", "ru": "Флаффи Раффлз", "note": "Кружевные курчавые вайи."}]'::jsonb),
  ('dracaena-fragrans', '[{"name": "Massangeana", "ru": "Массанжеана", "note": "Жёлтая полоса по центру листа."}, {"name": "Janet Craig", "ru": "Джанет Крейг", "note": "Тёмно-зелёные глянцевые листья; терпит тень."}, {"name": "Lemon Lime", "ru": "Лемон Лайм", "note": "Лаймовые полосы по краям листа."}, {"name": "Compacta", "ru": "Компакта", "note": "Короткие листья плотными розетками."}]'::jsonb),
  ('dracaena-marginata', '[{"name": "Bicolor", "ru": "Биколор", "note": "Красно-зелёные полоски."}, {"name": "Tricolor", "ru": "Триколор", "note": "Кремовые и красные полосы."}, {"name": "Colorama", "ru": "Колорама", "note": "Широкая розово-красная кайма; нужен яркий свет."}]'::jsonb),
  ('schefflera-arboricola', '[{"name": "Gold Capella", "ru": "Голд Капелла", "note": "Жёлтые пятна на листьях."}, {"name": "Janine", "ru": "Жанин", "note": "Кремовая пестрота, листочки с зазубринами."}]'::jsonb),
  ('codiaeum-variegatum', '[{"name": "Petra", "ru": "Петра", "note": "Широкие листья с жёлтыми, оранжевыми и красными жилками."}, {"name": "Mammy", "ru": "Мамми", "note": "Закрученные узкие листья."}, {"name": "Excellent", "ru": "Экселлент", "note": "Листья «дубового» типа, жёлто-красные."}]'::jsonb),
  ('citrus-limon', '[{"name": "Павловский", "ru": "Павловский", "note": "Старинный комнатный сорт: терпит сухой воздух и мало света."}, {"name": "Lunario", "ru": "Лунарио", "note": "Ремонтантный: цветёт и плодоносит почти круглый год."}, {"name": "Eureka", "ru": "Эврика", "note": "Урожайный, почти без колючек."}]'::jsonb),
  ('ocimum-basilicum', '[{"name": "Genovese", "ru": "Дженовезе", "note": "Классический зелёный базилик для песто."}, {"name": "Ереванский", "ru": "Ереванский", "note": "Фиолетовые листья с гвоздичным ароматом."}, {"name": "Thai", "ru": "Тайский", "note": "Фиолетовые стебли, анисовый аромат."}]'::jsonb),
  ('solanum-lycopersicum', '[{"name": "Балконное чудо", "ru": "Балконное чудо", "note": "Низкорослый черри, до 40 см; самый популярный для подоконника."}, {"name": "Пиноккио", "ru": "Пиноккио", "note": "Штамбовый, 20–30 см, красные черри."}, {"name": "Micro Tom", "ru": "Микро Том", "note": "Самый маленький томат, 15–20 см."}]'::jsonb),
  ('capsicum-annuum', '[{"name": "Огонёк", "ru": "Огонёк", "note": "Острый декоративный перец с красными плодами."}, {"name": "Medusa", "ru": "Медуза", "note": "Неострые плоды-«щупальца» разных цветов."}]'::jsonb),
  ('begonia-hiemalis', '[{"name": "Borias", "ru": "Бориас", "note": "Махровые розовые цветки с белым краем."}]'::jsonb),
  ('pteris-cretica', '[{"name": "Albolineata", "ru": "Альболинеата", "note": "Белая полоса по центру вай."}, {"name": "Wimsettii", "ru": "Вимсетти", "note": "Вайи с гребенчатыми кончиками."}]'::jsonb),
  ('euphorbia-tirucalli', '[{"name": "Firesticks", "ru": "Файерстикс", "note": "Побеги краснеют и оранжевеют на солнце."}]'::jsonb),
  ('cereus-repandus', '[{"name": "Monstrosus", "ru": "Монстрозус", "note": "Уродливая скалистая форма с причудливыми наростами."}]'::jsonb)
) as c(slug, cultivars)
where s.slug = c.slug;

-- Садоводы ищут фаленопсис просто как «Орхидея».
update public.species
   set common_names = jsonb_set(common_names, '{ru}', (common_names -> 'ru') || '["Орхидея"]'::jsonb)
 where slug = 'phalaenopsis-hybrid' and not (common_names -> 'ru') ? 'Орхидея';
